// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: policy/v1/policy.proto

package policyv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect int32

const (
	Effect_EFFECT_UNSPECIFIED Effect = 0
	Effect_EFFECT_ALLOW       Effect = 1
	Effect_EFFECT_DENY        Effect = 2
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "EFFECT_ALLOW",
		2: "EFFECT_DENY",
	}
	Effect_value = map[string]int32{
		"EFFECT_UNSPECIFIED": 0,
		"EFFECT_ALLOW":       1,
		"EFFECT_DENY":        2,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_v1_policy_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_policy_v1_policy_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

type PublishCerbosPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCerbosPolicyRequest) Reset() {
	*x = PublishCerbosPolicyRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCerbosPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCerbosPolicyRequest) ProtoMessage() {}

func (x *PublishCerbosPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCerbosPolicyRequest.ProtoReflect.Descriptor instead.
func (*PublishCerbosPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

type PublishCerbosPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCerbosPolicyResponse) Reset() {
	*x = PublishCerbosPolicyResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCerbosPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCerbosPolicyResponse) ProtoMessage() {}

func (x *PublishCerbosPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCerbosPolicyResponse.ProtoReflect.Descriptor instead.
func (*PublishCerbosPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

type GetCerbosPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []string               `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCerbosPolicyRequest) Reset() {
	*x = GetCerbosPolicyRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCerbosPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCerbosPolicyRequest) ProtoMessage() {}

func (x *GetCerbosPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCerbosPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetCerbosPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *GetCerbosPolicyRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetCerbosPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        []byte                 `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCerbosPolicyResponse) Reset() {
	*x = GetCerbosPolicyResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCerbosPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCerbosPolicyResponse) ProtoMessage() {}

func (x *GetCerbosPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCerbosPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetCerbosPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *GetCerbosPolicyResponse) GetPolicy() []byte {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ListCerbosPoliciesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	IncludeDisabled bool                   `protobuf:"varint,2,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	ServerId        string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCerbosPoliciesRequest) Reset() {
	*x = ListCerbosPoliciesRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCerbosPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCerbosPoliciesRequest) ProtoMessage() {}

func (x *ListCerbosPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCerbosPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListCerbosPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *ListCerbosPoliciesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListCerbosPoliciesRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

func (x *ListCerbosPoliciesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ListCerbosPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []byte                 `protobuf:"bytes,1,opt,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCerbosPoliciesResponse) Reset() {
	*x = ListCerbosPoliciesResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCerbosPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCerbosPoliciesResponse) ProtoMessage() {}

func (x *ListCerbosPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCerbosPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListCerbosPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *ListCerbosPoliciesResponse) GetPolicies() []byte {
	if x != nil {
		return x.Policies
	}
	return nil
}

type EnableCerbosPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []string               `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCerbosPolicyRequest) Reset() {
	*x = EnableCerbosPolicyRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCerbosPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCerbosPolicyRequest) ProtoMessage() {}

func (x *EnableCerbosPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCerbosPolicyRequest.ProtoReflect.Descriptor instead.
func (*EnableCerbosPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *EnableCerbosPolicyRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type EnableCerbosPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCerbosPolicyResponse) Reset() {
	*x = EnableCerbosPolicyResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCerbosPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCerbosPolicyResponse) ProtoMessage() {}

func (x *EnableCerbosPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCerbosPolicyResponse.ProtoReflect.Descriptor instead.
func (*EnableCerbosPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{7}
}

type DisableCerbosPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []string               `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCerbosPolicyRequest) Reset() {
	*x = DisableCerbosPolicyRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCerbosPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCerbosPolicyRequest) ProtoMessage() {}

func (x *DisableCerbosPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCerbosPolicyRequest.ProtoReflect.Descriptor instead.
func (*DisableCerbosPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *DisableCerbosPolicyRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type DisableCerbosPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCerbosPolicyResponse) Reset() {
	*x = DisableCerbosPolicyResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCerbosPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCerbosPolicyResponse) ProtoMessage() {}

func (x *DisableCerbosPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCerbosPolicyResponse.ProtoReflect.Descriptor instead.
func (*DisableCerbosPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{9}
}

type EnableRestrictionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RestrictionName string                 `protobuf:"bytes,1,opt,name=restriction_name,json=restrictionName,proto3" json:"restriction_name,omitempty"`
	Id              []string               `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnableRestrictionRequest) Reset() {
	*x = EnableRestrictionRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRestrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRestrictionRequest) ProtoMessage() {}

func (x *EnableRestrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRestrictionRequest.ProtoReflect.Descriptor instead.
func (*EnableRestrictionRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{10}
}

func (x *EnableRestrictionRequest) GetRestrictionName() string {
	if x != nil {
		return x.RestrictionName
	}
	return ""
}

func (x *EnableRestrictionRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type EnableRestrictionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRestrictionResponse) Reset() {
	*x = EnableRestrictionResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRestrictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRestrictionResponse) ProtoMessage() {}

func (x *EnableRestrictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRestrictionResponse.ProtoReflect.Descriptor instead.
func (*EnableRestrictionResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{11}
}

type DisableRestrictionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RestrictionName string                 `protobuf:"bytes,1,opt,name=restriction_name,json=restrictionName,proto3" json:"restriction_name,omitempty"`
	Id              []string               `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DisableRestrictionRequest) Reset() {
	*x = DisableRestrictionRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRestrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRestrictionRequest) ProtoMessage() {}

func (x *DisableRestrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRestrictionRequest.ProtoReflect.Descriptor instead.
func (*DisableRestrictionRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{12}
}

func (x *DisableRestrictionRequest) GetRestrictionName() string {
	if x != nil {
		return x.RestrictionName
	}
	return ""
}

func (x *DisableRestrictionRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type DisableRestrictionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRestrictionResponse) Reset() {
	*x = DisableRestrictionResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRestrictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRestrictionResponse) ProtoMessage() {}

func (x *DisableRestrictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRestrictionResponse.ProtoReflect.Descriptor instead.
func (*DisableRestrictionResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{13}
}

type ReloadCerbosCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadCerbosCacheRequest) Reset() {
	*x = ReloadCerbosCacheRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadCerbosCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCerbosCacheRequest) ProtoMessage() {}

func (x *ReloadCerbosCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCerbosCacheRequest.ProtoReflect.Descriptor instead.
func (*ReloadCerbosCacheRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{14}
}

type ReloadCerbosCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadCerbosCacheResponse) Reset() {
	*x = ReloadCerbosCacheResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadCerbosCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCerbosCacheResponse) ProtoMessage() {}

func (x *ReloadCerbosCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCerbosCacheResponse.ProtoReflect.Descriptor instead.
func (*ReloadCerbosCacheResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{15}
}

type CheckToolAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpServerId   string                 `protobuf:"bytes,1,opt,name=mcp_server_id,json=mcpServerId,proto3" json:"mcp_server_id,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	ServerSource  string                 `protobuf:"bytes,3,opt,name=server_source,json=serverSource,proto3" json:"server_source,omitempty"`
	ResourceAttrs map[string]string      `protobuf:"bytes,4,rep,name=resource_attrs,json=resourceAttrs,proto3" json:"resource_attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckToolAccessRequest) Reset() {
	*x = CheckToolAccessRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckToolAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckToolAccessRequest) ProtoMessage() {}

func (x *CheckToolAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckToolAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckToolAccessRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{16}
}

func (x *CheckToolAccessRequest) GetMcpServerId() string {
	if x != nil {
		return x.McpServerId
	}
	return ""
}

func (x *CheckToolAccessRequest) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CheckToolAccessRequest) GetServerSource() string {
	if x != nil {
		return x.ServerSource
	}
	return ""
}

func (x *CheckToolAccessRequest) GetResourceAttrs() map[string]string {
	if x != nil {
		return x.ResourceAttrs
	}
	return nil
}

type CheckToolAccessDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effect        Effect                 `protobuf:"varint,1,opt,name=effect,proto3,enum=barndoor.policy.v1.Effect" json:"effect,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckToolAccessDecision) Reset() {
	*x = CheckToolAccessDecision{}
	mi := &file_policy_v1_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckToolAccessDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckToolAccessDecision) ProtoMessage() {}

func (x *CheckToolAccessDecision) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckToolAccessDecision.ProtoReflect.Descriptor instead.
func (*CheckToolAccessDecision) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{17}
}

func (x *CheckToolAccessDecision) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}

func (x *CheckToolAccessDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CheckToolAccessResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Decisions     map[string]*CheckToolAccessDecision `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckToolAccessResponse) Reset() {
	*x = CheckToolAccessResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckToolAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckToolAccessResponse) ProtoMessage() {}

func (x *CheckToolAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckToolAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckToolAccessResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{18}
}

func (x *CheckToolAccessResponse) GetDecisions() map[string]*CheckToolAccessDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{19}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{20}
}

var File_policy_v1_policy_proto protoreflect.FileDescriptor

const file_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x16policy/v1/policy.proto\x12\x12barndoor.policy.v1\x1a\x1bbuf/validate/validate.proto\"\x1c\n" +
	"\x1aPublishCerbosPolicyRequest\"\x1d\n" +
	"\x1bPublishCerbosPolicyResponse\"2\n" +
	"\x16GetCerbosPolicyRequest\x12\x18\n" +
	"\x02id\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x02id\"1\n" +
	"\x17GetCerbosPolicyResponse\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\fR\x06policy\"~\n" +
	"\x19ListCerbosPoliciesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10include_disabled\x18\x02 \x01(\bR\x0fincludeDisabled\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"8\n" +
	"\x1aListCerbosPoliciesResponse\x12\x1a\n" +
	"\bpolicies\x18\x01 \x01(\fR\bpolicies\"5\n" +
	"\x19EnableCerbosPolicyRequest\x12\x18\n" +
	"\x02id\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x02id\"\x1c\n" +
	"\x1aEnableCerbosPolicyResponse\"6\n" +
	"\x1aDisableCerbosPolicyRequest\x12\x18\n" +
	"\x02id\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x02id\"\x1d\n" +
	"\x1bDisableCerbosPolicyResponse\"h\n" +
	"\x18EnableRestrictionRequest\x122\n" +
	"\x10restriction_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0frestrictionName\x12\x18\n" +
	"\x02id\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x02id\"\x1b\n" +
	"\x19EnableRestrictionResponse\"i\n" +
	"\x19DisableRestrictionRequest\x122\n" +
	"\x10restriction_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0frestrictionName\x12\x18\n" +
	"\x02id\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x02id\"\x1c\n" +
	"\x1aDisableRestrictionResponse\"\x1a\n" +
	"\x18ReloadCerbosCacheRequest\"\x1b\n" +
	"\x19ReloadCerbosCacheResponse\"\xb7\x02\n" +
	"\x16CheckToolAccessRequest\x12,\n" +
	"\rmcp_server_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\vmcpServerId\x12\"\n" +
	"\aactions\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\aactions\x12#\n" +
	"\rserver_source\x18\x03 \x01(\tR\fserverSource\x12d\n" +
	"\x0eresource_attrs\x18\x04 \x03(\v2=.barndoor.policy.v1.CheckToolAccessRequest.ResourceAttrsEntryR\rresourceAttrs\x1a@\n" +
	"\x12ResourceAttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x17CheckToolAccessDecision\x122\n" +
	"\x06effect\x18\x01 \x01(\x0e2\x1a.barndoor.policy.v1.EffectR\x06effect\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xde\x01\n" +
	"\x17CheckToolAccessResponse\x12X\n" +
	"\tdecisions\x18\x01 \x03(\v2:.barndoor.policy.v1.CheckToolAccessResponse.DecisionsEntryR\tdecisions\x1ai\n" +
	"\x0eDecisionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.barndoor.policy.v1.CheckToolAccessDecisionR\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse*C\n" +
	"\x06Effect\x12\x16\n" +
	"\x12EFFECT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fEFFECT_ALLOW\x10\x01\x12\x0f\n" +
	"\vEFFECT_DENY\x10\x022\xfa\b\n" +
	"\rPolicyService\x12v\n" +
	"\x13PublishCerbosPolicy\x12..barndoor.policy.v1.PublishCerbosPolicyRequest\x1a/.barndoor.policy.v1.PublishCerbosPolicyResponse\x12j\n" +
	"\x0fGetCerbosPolicy\x12*.barndoor.policy.v1.GetCerbosPolicyRequest\x1a+.barndoor.policy.v1.GetCerbosPolicyResponse\x12s\n" +
	"\x12ListCerbosPolicies\x12-.barndoor.policy.v1.ListCerbosPoliciesRequest\x1a..barndoor.policy.v1.ListCerbosPoliciesResponse\x12s\n" +
	"\x12EnableCerbosPolicy\x12-.barndoor.policy.v1.EnableCerbosPolicyRequest\x1a..barndoor.policy.v1.EnableCerbosPolicyResponse\x12v\n" +
	"\x13DisableCerbosPolicy\x12..barndoor.policy.v1.DisableCerbosPolicyRequest\x1a/.barndoor.policy.v1.DisableCerbosPolicyResponse\x12p\n" +
	"\x11EnableRestriction\x12,.barndoor.policy.v1.EnableRestrictionRequest\x1a-.barndoor.policy.v1.EnableRestrictionResponse\x12s\n" +
	"\x12DisableRestriction\x12-.barndoor.policy.v1.DisableRestrictionRequest\x1a..barndoor.policy.v1.DisableRestrictionResponse\x12p\n" +
	"\x11ReloadCerbosCache\x12,.barndoor.policy.v1.ReloadCerbosCacheRequest\x1a-.barndoor.policy.v1.ReloadCerbosCacheResponse\x12j\n" +
	"\x0fCheckToolAccess\x12*.barndoor.policy.v1.CheckToolAccessRequest\x1a+.barndoor.policy.v1.CheckToolAccessResponse\x12^\n" +
	"\vHealthCheck\x12&.barndoor.policy.v1.HealthCheckRequest\x1a'.barndoor.policy.v1.HealthCheckResponseB\x1dZ\x1bbarndoor/policy/v1;policyv1b\x06proto3"

var (
	file_policy_v1_policy_proto_rawDescOnce sync.Once
	file_policy_v1_policy_proto_rawDescData []byte
)

func file_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)))
	})
	return file_policy_v1_policy_proto_rawDescData
}

var file_policy_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_policy_v1_policy_proto_goTypes = []any{
	(Effect)(0),                         // 0: barndoor.policy.v1.Effect
	(*PublishCerbosPolicyRequest)(nil),  // 1: barndoor.policy.v1.PublishCerbosPolicyRequest
	(*PublishCerbosPolicyResponse)(nil), // 2: barndoor.policy.v1.PublishCerbosPolicyResponse
	(*GetCerbosPolicyRequest)(nil),      // 3: barndoor.policy.v1.GetCerbosPolicyRequest
	(*GetCerbosPolicyResponse)(nil),     // 4: barndoor.policy.v1.GetCerbosPolicyResponse
	(*ListCerbosPoliciesRequest)(nil),   // 5: barndoor.policy.v1.ListCerbosPoliciesRequest
	(*ListCerbosPoliciesResponse)(nil),  // 6: barndoor.policy.v1.ListCerbosPoliciesResponse
	(*EnableCerbosPolicyRequest)(nil),   // 7: barndoor.policy.v1.EnableCerbosPolicyRequest
	(*EnableCerbosPolicyResponse)(nil),  // 8: barndoor.policy.v1.EnableCerbosPolicyResponse
	(*DisableCerbosPolicyRequest)(nil),  // 9: barndoor.policy.v1.DisableCerbosPolicyRequest
	(*DisableCerbosPolicyResponse)(nil), // 10: barndoor.policy.v1.DisableCerbosPolicyResponse
	(*EnableRestrictionRequest)(nil),    // 11: barndoor.policy.v1.EnableRestrictionRequest
	(*EnableRestrictionResponse)(nil),   // 12: barndoor.policy.v1.EnableRestrictionResponse
	(*DisableRestrictionRequest)(nil),   // 13: barndoor.policy.v1.DisableRestrictionRequest
	(*DisableRestrictionResponse)(nil),  // 14: barndoor.policy.v1.DisableRestrictionResponse
	(*ReloadCerbosCacheRequest)(nil),    // 15: barndoor.policy.v1.ReloadCerbosCacheRequest
	(*ReloadCerbosCacheResponse)(nil),   // 16: barndoor.policy.v1.ReloadCerbosCacheResponse
	(*CheckToolAccessRequest)(nil),      // 17: barndoor.policy.v1.CheckToolAccessRequest
	(*CheckToolAccessDecision)(nil),     // 18: barndoor.policy.v1.CheckToolAccessDecision
	(*CheckToolAccessResponse)(nil),     // 19: barndoor.policy.v1.CheckToolAccessResponse
	(*HealthCheckRequest)(nil),          // 20: barndoor.policy.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 21: barndoor.policy.v1.HealthCheckResponse
	nil,                                 // 22: barndoor.policy.v1.CheckToolAccessRequest.ResourceAttrsEntry
	nil,                                 // 23: barndoor.policy.v1.CheckToolAccessResponse.DecisionsEntry
}
var file_policy_v1_policy_proto_depIdxs = []int32{
	22, // 0: barndoor.policy.v1.CheckToolAccessRequest.resource_attrs:type_name -> barndoor.policy.v1.CheckToolAccessRequest.ResourceAttrsEntry
	0,  // 1: barndoor.policy.v1.CheckToolAccessDecision.effect:type_name -> barndoor.policy.v1.Effect
	23, // 2: barndoor.policy.v1.CheckToolAccessResponse.decisions:type_name -> barndoor.policy.v1.CheckToolAccessResponse.DecisionsEntry
	18, // 3: barndoor.policy.v1.CheckToolAccessResponse.DecisionsEntry.value:type_name -> barndoor.policy.v1.CheckToolAccessDecision
	1,  // 4: barndoor.policy.v1.PolicyService.PublishCerbosPolicy:input_type -> barndoor.policy.v1.PublishCerbosPolicyRequest
	3,  // 5: barndoor.policy.v1.PolicyService.GetCerbosPolicy:input_type -> barndoor.policy.v1.GetCerbosPolicyRequest
	5,  // 6: barndoor.policy.v1.PolicyService.ListCerbosPolicies:input_type -> barndoor.policy.v1.ListCerbosPoliciesRequest
	7,  // 7: barndoor.policy.v1.PolicyService.EnableCerbosPolicy:input_type -> barndoor.policy.v1.EnableCerbosPolicyRequest
	9,  // 8: barndoor.policy.v1.PolicyService.DisableCerbosPolicy:input_type -> barndoor.policy.v1.DisableCerbosPolicyRequest
	11, // 9: barndoor.policy.v1.PolicyService.EnableRestriction:input_type -> barndoor.policy.v1.EnableRestrictionRequest
	13, // 10: barndoor.policy.v1.PolicyService.DisableRestriction:input_type -> barndoor.policy.v1.DisableRestrictionRequest
	15, // 11: barndoor.policy.v1.PolicyService.ReloadCerbosCache:input_type -> barndoor.policy.v1.ReloadCerbosCacheRequest
	17, // 12: barndoor.policy.v1.PolicyService.CheckToolAccess:input_type -> barndoor.policy.v1.CheckToolAccessRequest
	20, // 13: barndoor.policy.v1.PolicyService.HealthCheck:input_type -> barndoor.policy.v1.HealthCheckRequest
	2,  // 14: barndoor.policy.v1.PolicyService.PublishCerbosPolicy:output_type -> barndoor.policy.v1.PublishCerbosPolicyResponse
	4,  // 15: barndoor.policy.v1.PolicyService.GetCerbosPolicy:output_type -> barndoor.policy.v1.GetCerbosPolicyResponse
	6,  // 16: barndoor.policy.v1.PolicyService.ListCerbosPolicies:output_type -> barndoor.policy.v1.ListCerbosPoliciesResponse
	8,  // 17: barndoor.policy.v1.PolicyService.EnableCerbosPolicy:output_type -> barndoor.policy.v1.EnableCerbosPolicyResponse
	10, // 18: barndoor.policy.v1.PolicyService.DisableCerbosPolicy:output_type -> barndoor.policy.v1.DisableCerbosPolicyResponse
	12, // 19: barndoor.policy.v1.PolicyService.EnableRestriction:output_type -> barndoor.policy.v1.EnableRestrictionResponse
	14, // 20: barndoor.policy.v1.PolicyService.DisableRestriction:output_type -> barndoor.policy.v1.DisableRestrictionResponse
	16, // 21: barndoor.policy.v1.PolicyService.ReloadCerbosCache:output_type -> barndoor.policy.v1.ReloadCerbosCacheResponse
	19, // 22: barndoor.policy.v1.PolicyService.CheckToolAccess:output_type -> barndoor.policy.v1.CheckToolAccessResponse
	21, // 23: barndoor.policy.v1.PolicyService.HealthCheck:output_type -> barndoor.policy.v1.HealthCheckResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_policy_v1_policy_proto_init() }
func file_policy_v1_policy_proto_init() {
	if File_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_policy_v1_policy_proto_depIdxs,
		EnumInfos:         file_policy_v1_policy_proto_enumTypes,
		MessageInfos:      file_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_policy_v1_policy_proto = out.File
	file_policy_v1_policy_proto_goTypes = nil
	file_policy_v1_policy_proto_depIdxs = nil
}
