/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListRoutingRulesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRoutingRulesResponse{}

// ListRoutingRulesResponse struct for ListRoutingRulesResponse
type ListRoutingRulesResponse struct {
	// Pairs of rule names whose constraints cannot both be satisfied.  Returned on the listing as well as on writes so the admin UI can show a standing warning, not just a transient toast at save time — a conflict created yesterday is still a conflict today.
	Conflicts []RuleConflict `json:"conflicts"`
	Rules []RoutingRule `json:"rules"`
}

type _ListRoutingRulesResponse ListRoutingRulesResponse

// NewListRoutingRulesResponse instantiates a new ListRoutingRulesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRoutingRulesResponse(conflicts []RuleConflict, rules []RoutingRule) *ListRoutingRulesResponse {
	this := ListRoutingRulesResponse{}
	this.Conflicts = conflicts
	this.Rules = rules
	return &this
}

// NewListRoutingRulesResponseWithDefaults instantiates a new ListRoutingRulesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRoutingRulesResponseWithDefaults() *ListRoutingRulesResponse {
	this := ListRoutingRulesResponse{}
	return &this
}

// GetConflicts returns the Conflicts field value
func (o *ListRoutingRulesResponse) GetConflicts() []RuleConflict {
	if o == nil {
		var ret []RuleConflict
		return ret
	}

	return o.Conflicts
}

// GetConflictsOk returns a tuple with the Conflicts field value
// and a boolean to check if the value has been set.
func (o *ListRoutingRulesResponse) GetConflictsOk() ([]RuleConflict, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conflicts, true
}

// SetConflicts sets field value
func (o *ListRoutingRulesResponse) SetConflicts(v []RuleConflict) {
	o.Conflicts = v
}

// GetRules returns the Rules field value
func (o *ListRoutingRulesResponse) GetRules() []RoutingRule {
	if o == nil {
		var ret []RoutingRule
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *ListRoutingRulesResponse) GetRulesOk() ([]RoutingRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules, true
}

// SetRules sets field value
func (o *ListRoutingRulesResponse) SetRules(v []RoutingRule) {
	o.Rules = v
}

func (o ListRoutingRulesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRoutingRulesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conflicts"] = o.Conflicts
	toSerialize["rules"] = o.Rules
	return toSerialize, nil
}

func (o *ListRoutingRulesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conflicts",
		"rules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListRoutingRulesResponse := _ListRoutingRulesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListRoutingRulesResponse)

	if err != nil {
		return err
	}

	*o = ListRoutingRulesResponse(varListRoutingRulesResponse)

	return err
}

type NullableListRoutingRulesResponse struct {
	value *ListRoutingRulesResponse
	isSet bool
}

func (v NullableListRoutingRulesResponse) Get() *ListRoutingRulesResponse {
	return v.value
}

func (v *NullableListRoutingRulesResponse) Set(val *ListRoutingRulesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListRoutingRulesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListRoutingRulesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRoutingRulesResponse(val *ListRoutingRulesResponse) *NullableListRoutingRulesResponse {
	return &NullableListRoutingRulesResponse{value: val, isSet: true}
}

func (v NullableListRoutingRulesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRoutingRulesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


