/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpsertAzureAiLanguagePiiRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertAzureAiLanguagePiiRequest{}

// UpsertAzureAiLanguagePiiRequest struct for UpsertAzureAiLanguagePiiRequest
type UpsertAzureAiLanguagePiiRequest struct {
	// Supply to set or rotate the API key; omit to leave unchanged.
	ApiKey NullableString `json:"api_key,omitempty"`
	ApiVersion *string `json:"api_version,omitempty"`
	Endpoint string `json:"endpoint"`
	Language *string `json:"language,omitempty"`
}

type _UpsertAzureAiLanguagePiiRequest UpsertAzureAiLanguagePiiRequest

// NewUpsertAzureAiLanguagePiiRequest instantiates a new UpsertAzureAiLanguagePiiRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertAzureAiLanguagePiiRequest(endpoint string) *UpsertAzureAiLanguagePiiRequest {
	this := UpsertAzureAiLanguagePiiRequest{}
	this.Endpoint = endpoint
	return &this
}

// NewUpsertAzureAiLanguagePiiRequestWithDefaults instantiates a new UpsertAzureAiLanguagePiiRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertAzureAiLanguagePiiRequestWithDefaults() *UpsertAzureAiLanguagePiiRequest {
	this := UpsertAzureAiLanguagePiiRequest{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpsertAzureAiLanguagePiiRequest) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey.Get()) {
		var ret string
		return ret
	}
	return *o.ApiKey.Get()
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpsertAzureAiLanguagePiiRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiKey.Get(), o.ApiKey.IsSet()
}

// HasApiKey returns a boolean if a field has been set.
func (o *UpsertAzureAiLanguagePiiRequest) HasApiKey() bool {
	if o != nil && o.ApiKey.IsSet() {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given NullableString and assigns it to the ApiKey field.
func (o *UpsertAzureAiLanguagePiiRequest) SetApiKey(v string) {
	o.ApiKey.Set(&v)
}
// SetApiKeyNil sets the value for ApiKey to be an explicit nil
func (o *UpsertAzureAiLanguagePiiRequest) SetApiKeyNil() {
	o.ApiKey.Set(nil)
}

// UnsetApiKey ensures that no value is present for ApiKey, not even an explicit nil
func (o *UpsertAzureAiLanguagePiiRequest) UnsetApiKey() {
	o.ApiKey.Unset()
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *UpsertAzureAiLanguagePiiRequest) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertAzureAiLanguagePiiRequest) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *UpsertAzureAiLanguagePiiRequest) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *UpsertAzureAiLanguagePiiRequest) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetEndpoint returns the Endpoint field value
func (o *UpsertAzureAiLanguagePiiRequest) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *UpsertAzureAiLanguagePiiRequest) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *UpsertAzureAiLanguagePiiRequest) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *UpsertAzureAiLanguagePiiRequest) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertAzureAiLanguagePiiRequest) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *UpsertAzureAiLanguagePiiRequest) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *UpsertAzureAiLanguagePiiRequest) SetLanguage(v string) {
	o.Language = &v
}

func (o UpsertAzureAiLanguagePiiRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertAzureAiLanguagePiiRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKey.IsSet() {
		toSerialize["api_key"] = o.ApiKey.Get()
	}
	if !IsNil(o.ApiVersion) {
		toSerialize["api_version"] = o.ApiVersion
	}
	toSerialize["endpoint"] = o.Endpoint
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	return toSerialize, nil
}

func (o *UpsertAzureAiLanguagePiiRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsertAzureAiLanguagePiiRequest := _UpsertAzureAiLanguagePiiRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpsertAzureAiLanguagePiiRequest)

	if err != nil {
		return err
	}

	*o = UpsertAzureAiLanguagePiiRequest(varUpsertAzureAiLanguagePiiRequest)

	return err
}

type NullableUpsertAzureAiLanguagePiiRequest struct {
	value *UpsertAzureAiLanguagePiiRequest
	isSet bool
}

func (v NullableUpsertAzureAiLanguagePiiRequest) Get() *UpsertAzureAiLanguagePiiRequest {
	return v.value
}

func (v *NullableUpsertAzureAiLanguagePiiRequest) Set(val *UpsertAzureAiLanguagePiiRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertAzureAiLanguagePiiRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertAzureAiLanguagePiiRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertAzureAiLanguagePiiRequest(val *UpsertAzureAiLanguagePiiRequest) *NullableUpsertAzureAiLanguagePiiRequest {
	return &NullableUpsertAzureAiLanguagePiiRequest{value: val, isSet: true}
}

func (v NullableUpsertAzureAiLanguagePiiRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertAzureAiLanguagePiiRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


