/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilterCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterCategory{}

// FilterCategory Category of filter options for the advanced filter UI.
type FilterCategory struct {
	Id string `json:"id"`
	Label string `json:"label"`
	Options []FilterOption `json:"options,omitempty"`
}

type _FilterCategory FilterCategory

// NewFilterCategory instantiates a new FilterCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterCategory(id string, label string) *FilterCategory {
	this := FilterCategory{}
	this.Id = id
	this.Label = label
	return &this
}

// NewFilterCategoryWithDefaults instantiates a new FilterCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterCategoryWithDefaults() *FilterCategory {
	this := FilterCategory{}
	return &this
}

// GetId returns the Id field value
func (o *FilterCategory) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FilterCategory) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FilterCategory) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *FilterCategory) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *FilterCategory) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *FilterCategory) SetLabel(v string) {
	o.Label = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *FilterCategory) GetOptions() []FilterOption {
	if o == nil || IsNil(o.Options) {
		var ret []FilterOption
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterCategory) GetOptionsOk() ([]FilterOption, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *FilterCategory) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []FilterOption and assigns it to the Options field.
func (o *FilterCategory) SetOptions(v []FilterOption) {
	o.Options = v
}

func (o FilterCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

func (o *FilterCategory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilterCategory := _FilterCategory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilterCategory)

	if err != nil {
		return err
	}

	*o = FilterCategory(varFilterCategory)

	return err
}

type NullableFilterCategory struct {
	value *FilterCategory
	isSet bool
}

func (v NullableFilterCategory) Get() *FilterCategory {
	return v.value
}

func (v *NullableFilterCategory) Set(val *FilterCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterCategory(val *FilterCategory) *NullableFilterCategory {
	return &NullableFilterCategory{value: val, isSet: true}
}

func (v NullableFilterCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


