/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PolicySummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicySummaryResponse{}

// PolicySummaryResponse Summary counts of policies by status.
type PolicySummaryResponse struct {
	Active *int32 `json:"active,omitempty"`
	Draft *int32 `json:"draft,omitempty"`
	Inactive *int32 `json:"inactive,omitempty"`
	Archived *int32 `json:"archived,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewPolicySummaryResponse instantiates a new PolicySummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicySummaryResponse() *PolicySummaryResponse {
	this := PolicySummaryResponse{}
	var active int32 = 0
	this.Active = &active
	var draft int32 = 0
	this.Draft = &draft
	var inactive int32 = 0
	this.Inactive = &inactive
	var archived int32 = 0
	this.Archived = &archived
	var total int32 = 0
	this.Total = &total
	return &this
}

// NewPolicySummaryResponseWithDefaults instantiates a new PolicySummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicySummaryResponseWithDefaults() *PolicySummaryResponse {
	this := PolicySummaryResponse{}
	var active int32 = 0
	this.Active = &active
	var draft int32 = 0
	this.Draft = &draft
	var inactive int32 = 0
	this.Inactive = &inactive
	var archived int32 = 0
	this.Archived = &archived
	var total int32 = 0
	this.Total = &total
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *PolicySummaryResponse) GetActive() int32 {
	if o == nil || IsNil(o.Active) {
		var ret int32
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicySummaryResponse) GetActiveOk() (*int32, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *PolicySummaryResponse) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given int32 and assigns it to the Active field.
func (o *PolicySummaryResponse) SetActive(v int32) {
	o.Active = &v
}

// GetDraft returns the Draft field value if set, zero value otherwise.
func (o *PolicySummaryResponse) GetDraft() int32 {
	if o == nil || IsNil(o.Draft) {
		var ret int32
		return ret
	}
	return *o.Draft
}

// GetDraftOk returns a tuple with the Draft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicySummaryResponse) GetDraftOk() (*int32, bool) {
	if o == nil || IsNil(o.Draft) {
		return nil, false
	}
	return o.Draft, true
}

// HasDraft returns a boolean if a field has been set.
func (o *PolicySummaryResponse) HasDraft() bool {
	if o != nil && !IsNil(o.Draft) {
		return true
	}

	return false
}

// SetDraft gets a reference to the given int32 and assigns it to the Draft field.
func (o *PolicySummaryResponse) SetDraft(v int32) {
	o.Draft = &v
}

// GetInactive returns the Inactive field value if set, zero value otherwise.
func (o *PolicySummaryResponse) GetInactive() int32 {
	if o == nil || IsNil(o.Inactive) {
		var ret int32
		return ret
	}
	return *o.Inactive
}

// GetInactiveOk returns a tuple with the Inactive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicySummaryResponse) GetInactiveOk() (*int32, bool) {
	if o == nil || IsNil(o.Inactive) {
		return nil, false
	}
	return o.Inactive, true
}

// HasInactive returns a boolean if a field has been set.
func (o *PolicySummaryResponse) HasInactive() bool {
	if o != nil && !IsNil(o.Inactive) {
		return true
	}

	return false
}

// SetInactive gets a reference to the given int32 and assigns it to the Inactive field.
func (o *PolicySummaryResponse) SetInactive(v int32) {
	o.Inactive = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *PolicySummaryResponse) GetArchived() int32 {
	if o == nil || IsNil(o.Archived) {
		var ret int32
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicySummaryResponse) GetArchivedOk() (*int32, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *PolicySummaryResponse) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given int32 and assigns it to the Archived field.
func (o *PolicySummaryResponse) SetArchived(v int32) {
	o.Archived = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PolicySummaryResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicySummaryResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PolicySummaryResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *PolicySummaryResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o PolicySummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicySummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Draft) {
		toSerialize["draft"] = o.Draft
	}
	if !IsNil(o.Inactive) {
		toSerialize["inactive"] = o.Inactive
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullablePolicySummaryResponse struct {
	value *PolicySummaryResponse
	isSet bool
}

func (v NullablePolicySummaryResponse) Get() *PolicySummaryResponse {
	return v.value
}

func (v *NullablePolicySummaryResponse) Set(val *PolicySummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicySummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicySummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicySummaryResponse(val *PolicySummaryResponse) *NullablePolicySummaryResponse {
	return &NullablePolicySummaryResponse{value: val, isSet: true}
}

func (v NullablePolicySummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicySummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


