/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MaskFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaskFormat{}

// MaskFormat The `mask_format` object stored on `dlp.enforcement_policies.mask_format` and carried on the admin REST surface. `deny_unknown_fields` so a typo in a client (or a future key an older server does not understand) fails loudly.
type MaskFormat struct {
	Keep MaskKeep `json:"keep"`
	KeepChars int32 `json:"keep_chars"`
	MaskChar *string `json:"mask_char,omitempty"`
	PreserveSeparators *bool `json:"preserve_separators,omitempty"`
}

type _MaskFormat MaskFormat

// NewMaskFormat instantiates a new MaskFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaskFormat(keep MaskKeep, keepChars int32) *MaskFormat {
	this := MaskFormat{}
	this.Keep = keep
	this.KeepChars = keepChars
	return &this
}

// NewMaskFormatWithDefaults instantiates a new MaskFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaskFormatWithDefaults() *MaskFormat {
	this := MaskFormat{}
	return &this
}

// GetKeep returns the Keep field value
func (o *MaskFormat) GetKeep() MaskKeep {
	if o == nil {
		var ret MaskKeep
		return ret
	}

	return o.Keep
}

// GetKeepOk returns a tuple with the Keep field value
// and a boolean to check if the value has been set.
func (o *MaskFormat) GetKeepOk() (*MaskKeep, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Keep, true
}

// SetKeep sets field value
func (o *MaskFormat) SetKeep(v MaskKeep) {
	o.Keep = v
}

// GetKeepChars returns the KeepChars field value
func (o *MaskFormat) GetKeepChars() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.KeepChars
}

// GetKeepCharsOk returns a tuple with the KeepChars field value
// and a boolean to check if the value has been set.
func (o *MaskFormat) GetKeepCharsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeepChars, true
}

// SetKeepChars sets field value
func (o *MaskFormat) SetKeepChars(v int32) {
	o.KeepChars = v
}

// GetMaskChar returns the MaskChar field value if set, zero value otherwise.
func (o *MaskFormat) GetMaskChar() string {
	if o == nil || IsNil(o.MaskChar) {
		var ret string
		return ret
	}
	return *o.MaskChar
}

// GetMaskCharOk returns a tuple with the MaskChar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaskFormat) GetMaskCharOk() (*string, bool) {
	if o == nil || IsNil(o.MaskChar) {
		return nil, false
	}
	return o.MaskChar, true
}

// HasMaskChar returns a boolean if a field has been set.
func (o *MaskFormat) HasMaskChar() bool {
	if o != nil && !IsNil(o.MaskChar) {
		return true
	}

	return false
}

// SetMaskChar gets a reference to the given string and assigns it to the MaskChar field.
func (o *MaskFormat) SetMaskChar(v string) {
	o.MaskChar = &v
}

// GetPreserveSeparators returns the PreserveSeparators field value if set, zero value otherwise.
func (o *MaskFormat) GetPreserveSeparators() bool {
	if o == nil || IsNil(o.PreserveSeparators) {
		var ret bool
		return ret
	}
	return *o.PreserveSeparators
}

// GetPreserveSeparatorsOk returns a tuple with the PreserveSeparators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaskFormat) GetPreserveSeparatorsOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveSeparators) {
		return nil, false
	}
	return o.PreserveSeparators, true
}

// HasPreserveSeparators returns a boolean if a field has been set.
func (o *MaskFormat) HasPreserveSeparators() bool {
	if o != nil && !IsNil(o.PreserveSeparators) {
		return true
	}

	return false
}

// SetPreserveSeparators gets a reference to the given bool and assigns it to the PreserveSeparators field.
func (o *MaskFormat) SetPreserveSeparators(v bool) {
	o.PreserveSeparators = &v
}

func (o MaskFormat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaskFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keep"] = o.Keep
	toSerialize["keep_chars"] = o.KeepChars
	if !IsNil(o.MaskChar) {
		toSerialize["mask_char"] = o.MaskChar
	}
	if !IsNil(o.PreserveSeparators) {
		toSerialize["preserve_separators"] = o.PreserveSeparators
	}
	return toSerialize, nil
}

func (o *MaskFormat) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keep",
		"keep_chars",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMaskFormat := _MaskFormat{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMaskFormat)

	if err != nil {
		return err
	}

	*o = MaskFormat(varMaskFormat)

	return err
}

type NullableMaskFormat struct {
	value *MaskFormat
	isSet bool
}

func (v NullableMaskFormat) Get() *MaskFormat {
	return v.value
}

func (v *NullableMaskFormat) Set(val *MaskFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableMaskFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableMaskFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaskFormat(val *MaskFormat) *NullableMaskFormat {
	return &NullableMaskFormat{value: val, isSet: true}
}

func (v NullableMaskFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaskFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


