/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PutClientSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutClientSettingsRequest{}

// PutClientSettingsRequest struct for PutClientSettingsRequest
type PutClientSettingsRequest struct {
	Capabilities AgentRuntimeCapabilities `json:"capabilities"`
	// Any subset of the client's slot keys (possibly empty). Each value is a single Model Route or routing-policy alias.
	Preferences map[string]string `json:"preferences,omitempty"`
}

type _PutClientSettingsRequest PutClientSettingsRequest

// NewPutClientSettingsRequest instantiates a new PutClientSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutClientSettingsRequest(capabilities AgentRuntimeCapabilities) *PutClientSettingsRequest {
	this := PutClientSettingsRequest{}
	this.Capabilities = capabilities
	return &this
}

// NewPutClientSettingsRequestWithDefaults instantiates a new PutClientSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutClientSettingsRequestWithDefaults() *PutClientSettingsRequest {
	this := PutClientSettingsRequest{}
	return &this
}

// GetCapabilities returns the Capabilities field value
func (o *PutClientSettingsRequest) GetCapabilities() AgentRuntimeCapabilities {
	if o == nil {
		var ret AgentRuntimeCapabilities
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *PutClientSettingsRequest) GetCapabilitiesOk() (*AgentRuntimeCapabilities, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Capabilities, true
}

// SetCapabilities sets field value
func (o *PutClientSettingsRequest) SetCapabilities(v AgentRuntimeCapabilities) {
	o.Capabilities = v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *PutClientSettingsRequest) GetPreferences() map[string]string {
	if o == nil || IsNil(o.Preferences) {
		var ret map[string]string
		return ret
	}
	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutClientSettingsRequest) GetPreferencesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Preferences) {
		return map[string]string{}, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *PutClientSettingsRequest) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given map[string]string and assigns it to the Preferences field.
func (o *PutClientSettingsRequest) SetPreferences(v map[string]string) {
	o.Preferences = v
}

func (o PutClientSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutClientSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capabilities"] = o.Capabilities
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	return toSerialize, nil
}

func (o *PutClientSettingsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capabilities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutClientSettingsRequest := _PutClientSettingsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutClientSettingsRequest)

	if err != nil {
		return err
	}

	*o = PutClientSettingsRequest(varPutClientSettingsRequest)

	return err
}

type NullablePutClientSettingsRequest struct {
	value *PutClientSettingsRequest
	isSet bool
}

func (v NullablePutClientSettingsRequest) Get() *PutClientSettingsRequest {
	return v.value
}

func (v *NullablePutClientSettingsRequest) Set(val *PutClientSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutClientSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutClientSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutClientSettingsRequest(val *PutClientSettingsRequest) *NullablePutClientSettingsRequest {
	return &NullablePutClientSettingsRequest{value: val, isSet: true}
}

func (v NullablePutClientSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutClientSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


