/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PolicyAttributionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyAttributionResponse{}

// PolicyAttributionResponse struct for PolicyAttributionResponse
type PolicyAttributionResponse struct {
	// Owning enforcement policy id + name when the rule is policy-owned.
	PolicyId NullableString `json:"policy_id,omitempty"`
	PolicyName NullableString `json:"policy_name,omitempty"`
	RuleId string `json:"rule_id"`
	Scope ScopeJson `json:"scope"`
	Source string `json:"source"`
}

type _PolicyAttributionResponse PolicyAttributionResponse

// NewPolicyAttributionResponse instantiates a new PolicyAttributionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyAttributionResponse(ruleId string, scope ScopeJson, source string) *PolicyAttributionResponse {
	this := PolicyAttributionResponse{}
	this.RuleId = ruleId
	this.Scope = scope
	this.Source = source
	return &this
}

// NewPolicyAttributionResponseWithDefaults instantiates a new PolicyAttributionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyAttributionResponseWithDefaults() *PolicyAttributionResponse {
	this := PolicyAttributionResponse{}
	return &this
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyAttributionResponse) GetPolicyId() string {
	if o == nil || IsNil(o.PolicyId.Get()) {
		var ret string
		return ret
	}
	return *o.PolicyId.Get()
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyAttributionResponse) GetPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyId.Get(), o.PolicyId.IsSet()
}

// HasPolicyId returns a boolean if a field has been set.
func (o *PolicyAttributionResponse) HasPolicyId() bool {
	if o != nil && o.PolicyId.IsSet() {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given NullableString and assigns it to the PolicyId field.
func (o *PolicyAttributionResponse) SetPolicyId(v string) {
	o.PolicyId.Set(&v)
}
// SetPolicyIdNil sets the value for PolicyId to be an explicit nil
func (o *PolicyAttributionResponse) SetPolicyIdNil() {
	o.PolicyId.Set(nil)
}

// UnsetPolicyId ensures that no value is present for PolicyId, not even an explicit nil
func (o *PolicyAttributionResponse) UnsetPolicyId() {
	o.PolicyId.Unset()
}

// GetPolicyName returns the PolicyName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyAttributionResponse) GetPolicyName() string {
	if o == nil || IsNil(o.PolicyName.Get()) {
		var ret string
		return ret
	}
	return *o.PolicyName.Get()
}

// GetPolicyNameOk returns a tuple with the PolicyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyAttributionResponse) GetPolicyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyName.Get(), o.PolicyName.IsSet()
}

// HasPolicyName returns a boolean if a field has been set.
func (o *PolicyAttributionResponse) HasPolicyName() bool {
	if o != nil && o.PolicyName.IsSet() {
		return true
	}

	return false
}

// SetPolicyName gets a reference to the given NullableString and assigns it to the PolicyName field.
func (o *PolicyAttributionResponse) SetPolicyName(v string) {
	o.PolicyName.Set(&v)
}
// SetPolicyNameNil sets the value for PolicyName to be an explicit nil
func (o *PolicyAttributionResponse) SetPolicyNameNil() {
	o.PolicyName.Set(nil)
}

// UnsetPolicyName ensures that no value is present for PolicyName, not even an explicit nil
func (o *PolicyAttributionResponse) UnsetPolicyName() {
	o.PolicyName.Unset()
}

// GetRuleId returns the RuleId field value
func (o *PolicyAttributionResponse) GetRuleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value
// and a boolean to check if the value has been set.
func (o *PolicyAttributionResponse) GetRuleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleId, true
}

// SetRuleId sets field value
func (o *PolicyAttributionResponse) SetRuleId(v string) {
	o.RuleId = v
}

// GetScope returns the Scope field value
func (o *PolicyAttributionResponse) GetScope() ScopeJson {
	if o == nil {
		var ret ScopeJson
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *PolicyAttributionResponse) GetScopeOk() (*ScopeJson, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *PolicyAttributionResponse) SetScope(v ScopeJson) {
	o.Scope = v
}

// GetSource returns the Source field value
func (o *PolicyAttributionResponse) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *PolicyAttributionResponse) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *PolicyAttributionResponse) SetSource(v string) {
	o.Source = v
}

func (o PolicyAttributionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyAttributionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PolicyId.IsSet() {
		toSerialize["policy_id"] = o.PolicyId.Get()
	}
	if o.PolicyName.IsSet() {
		toSerialize["policy_name"] = o.PolicyName.Get()
	}
	toSerialize["rule_id"] = o.RuleId
	toSerialize["scope"] = o.Scope
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *PolicyAttributionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rule_id",
		"scope",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyAttributionResponse := _PolicyAttributionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyAttributionResponse)

	if err != nil {
		return err
	}

	*o = PolicyAttributionResponse(varPolicyAttributionResponse)

	return err
}

type NullablePolicyAttributionResponse struct {
	value *PolicyAttributionResponse
	isSet bool
}

func (v NullablePolicyAttributionResponse) Get() *PolicyAttributionResponse {
	return v.value
}

func (v *NullablePolicyAttributionResponse) Set(val *PolicyAttributionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyAttributionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyAttributionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyAttributionResponse(val *PolicyAttributionResponse) *NullablePolicyAttributionResponse {
	return &NullablePolicyAttributionResponse{value: val, isSet: true}
}

func (v NullablePolicyAttributionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyAttributionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


