/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedResponseAllowListEntryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseAllowListEntryResponse{}

// PaginatedResponseAllowListEntryResponse struct for PaginatedResponseAllowListEntryResponse
type PaginatedResponseAllowListEntryResponse struct {
	Items []PaginatedResponseAllowListEntryResponseItemsInner `json:"items"`
	NextPageToken string `json:"next_page_token"`
	TotalCount int64 `json:"total_count"`
}

type _PaginatedResponseAllowListEntryResponse PaginatedResponseAllowListEntryResponse

// NewPaginatedResponseAllowListEntryResponse instantiates a new PaginatedResponseAllowListEntryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseAllowListEntryResponse(items []PaginatedResponseAllowListEntryResponseItemsInner, nextPageToken string, totalCount int64) *PaginatedResponseAllowListEntryResponse {
	this := PaginatedResponseAllowListEntryResponse{}
	this.Items = items
	this.NextPageToken = nextPageToken
	this.TotalCount = totalCount
	return &this
}

// NewPaginatedResponseAllowListEntryResponseWithDefaults instantiates a new PaginatedResponseAllowListEntryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseAllowListEntryResponseWithDefaults() *PaginatedResponseAllowListEntryResponse {
	this := PaginatedResponseAllowListEntryResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *PaginatedResponseAllowListEntryResponse) GetItems() []PaginatedResponseAllowListEntryResponseItemsInner {
	if o == nil {
		var ret []PaginatedResponseAllowListEntryResponseItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAllowListEntryResponse) GetItemsOk() ([]PaginatedResponseAllowListEntryResponseItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PaginatedResponseAllowListEntryResponse) SetItems(v []PaginatedResponseAllowListEntryResponseItemsInner) {
	o.Items = v
}

// GetNextPageToken returns the NextPageToken field value
func (o *PaginatedResponseAllowListEntryResponse) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAllowListEntryResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *PaginatedResponseAllowListEntryResponse) SetNextPageToken(v string) {
	o.NextPageToken = v
}

// GetTotalCount returns the TotalCount field value
func (o *PaginatedResponseAllowListEntryResponse) GetTotalCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAllowListEntryResponse) GetTotalCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *PaginatedResponseAllowListEntryResponse) SetTotalCount(v int64) {
	o.TotalCount = v
}

func (o PaginatedResponseAllowListEntryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseAllowListEntryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["next_page_token"] = o.NextPageToken
	toSerialize["total_count"] = o.TotalCount
	return toSerialize, nil
}

func (o *PaginatedResponseAllowListEntryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"next_page_token",
		"total_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseAllowListEntryResponse := _PaginatedResponseAllowListEntryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedResponseAllowListEntryResponse)

	if err != nil {
		return err
	}

	*o = PaginatedResponseAllowListEntryResponse(varPaginatedResponseAllowListEntryResponse)

	return err
}

type NullablePaginatedResponseAllowListEntryResponse struct {
	value *PaginatedResponseAllowListEntryResponse
	isSet bool
}

func (v NullablePaginatedResponseAllowListEntryResponse) Get() *PaginatedResponseAllowListEntryResponse {
	return v.value
}

func (v *NullablePaginatedResponseAllowListEntryResponse) Set(val *PaginatedResponseAllowListEntryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseAllowListEntryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseAllowListEntryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseAllowListEntryResponse(val *PaginatedResponseAllowListEntryResponse) *NullablePaginatedResponseAllowListEntryResponse {
	return &NullablePaginatedResponseAllowListEntryResponse{value: val, isSet: true}
}

func (v NullablePaginatedResponseAllowListEntryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseAllowListEntryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


