/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FieldControlPolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldControlPolicyResponse{}

// FieldControlPolicyResponse struct for FieldControlPolicyResponse
type FieldControlPolicyResponse struct {
	CreatedAt string `json:"created_at"`
	CreatedBy string `json:"created_by"`
	Enabled bool `json:"enabled"`
	Id string `json:"id"`
	McpServerId string `json:"mcp_server_id"`
	Name string `json:"name"`
	OrgId string `json:"org_id"`
	Rules interface{} `json:"rules"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy string `json:"updated_by"`
	Version int32 `json:"version"`
}

type _FieldControlPolicyResponse FieldControlPolicyResponse

// NewFieldControlPolicyResponse instantiates a new FieldControlPolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldControlPolicyResponse(createdAt string, createdBy string, enabled bool, id string, mcpServerId string, name string, orgId string, rules interface{}, updatedAt string, updatedBy string, version int32) *FieldControlPolicyResponse {
	this := FieldControlPolicyResponse{}
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.Enabled = enabled
	this.Id = id
	this.McpServerId = mcpServerId
	this.Name = name
	this.OrgId = orgId
	this.Rules = rules
	this.UpdatedAt = updatedAt
	this.UpdatedBy = updatedBy
	this.Version = version
	return &this
}

// NewFieldControlPolicyResponseWithDefaults instantiates a new FieldControlPolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldControlPolicyResponseWithDefaults() *FieldControlPolicyResponse {
	this := FieldControlPolicyResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *FieldControlPolicyResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *FieldControlPolicyResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *FieldControlPolicyResponse) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *FieldControlPolicyResponse) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetEnabled returns the Enabled field value
func (o *FieldControlPolicyResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *FieldControlPolicyResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetId returns the Id field value
func (o *FieldControlPolicyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FieldControlPolicyResponse) SetId(v string) {
	o.Id = v
}

// GetMcpServerId returns the McpServerId field value
func (o *FieldControlPolicyResponse) GetMcpServerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.McpServerId
}

// GetMcpServerIdOk returns a tuple with the McpServerId field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetMcpServerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpServerId, true
}

// SetMcpServerId sets field value
func (o *FieldControlPolicyResponse) SetMcpServerId(v string) {
	o.McpServerId = v
}

// GetName returns the Name field value
func (o *FieldControlPolicyResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FieldControlPolicyResponse) SetName(v string) {
	o.Name = v
}

// GetOrgId returns the OrgId field value
func (o *FieldControlPolicyResponse) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *FieldControlPolicyResponse) SetOrgId(v string) {
	o.OrgId = v
}

// GetRules returns the Rules field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *FieldControlPolicyResponse) GetRules() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FieldControlPolicyResponse) GetRulesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return &o.Rules, true
}

// SetRules sets field value
func (o *FieldControlPolicyResponse) SetRules(v interface{}) {
	o.Rules = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *FieldControlPolicyResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *FieldControlPolicyResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetUpdatedBy returns the UpdatedBy field value
func (o *FieldControlPolicyResponse) GetUpdatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedBy, true
}

// SetUpdatedBy sets field value
func (o *FieldControlPolicyResponse) SetUpdatedBy(v string) {
	o.UpdatedBy = v
}

// GetVersion returns the Version field value
func (o *FieldControlPolicyResponse) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *FieldControlPolicyResponse) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *FieldControlPolicyResponse) SetVersion(v int32) {
	o.Version = v
}

func (o FieldControlPolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldControlPolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["enabled"] = o.Enabled
	toSerialize["id"] = o.Id
	toSerialize["mcp_server_id"] = o.McpServerId
	toSerialize["name"] = o.Name
	toSerialize["org_id"] = o.OrgId
	if o.Rules != nil {
		toSerialize["rules"] = o.Rules
	}
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["updated_by"] = o.UpdatedBy
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *FieldControlPolicyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"created_by",
		"enabled",
		"id",
		"mcp_server_id",
		"name",
		"org_id",
		"rules",
		"updated_at",
		"updated_by",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldControlPolicyResponse := _FieldControlPolicyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldControlPolicyResponse)

	if err != nil {
		return err
	}

	*o = FieldControlPolicyResponse(varFieldControlPolicyResponse)

	return err
}

type NullableFieldControlPolicyResponse struct {
	value *FieldControlPolicyResponse
	isSet bool
}

func (v NullableFieldControlPolicyResponse) Get() *FieldControlPolicyResponse {
	return v.value
}

func (v *NullableFieldControlPolicyResponse) Set(val *FieldControlPolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldControlPolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldControlPolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldControlPolicyResponse(val *FieldControlPolicyResponse) *NullableFieldControlPolicyResponse {
	return &NullableFieldControlPolicyResponse{value: val, isSet: true}
}

func (v NullableFieldControlPolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldControlPolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


