/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// OfInner1 - struct for OfInner1
type OfInner1 struct {
	Expression *Expression
	OperatorAllOutput *OperatorAllOutput
	OperatorAnyOutput *OperatorAnyOutput
	OperatorNoneOutput *OperatorNoneOutput
}

// ExpressionAsOfInner1 is a convenience function that returns Expression wrapped in OfInner1
func ExpressionAsOfInner1(v *Expression) OfInner1 {
	return OfInner1{
		Expression: v,
	}
}

// OperatorAllOutputAsOfInner1 is a convenience function that returns OperatorAllOutput wrapped in OfInner1
func OperatorAllOutputAsOfInner1(v *OperatorAllOutput) OfInner1 {
	return OfInner1{
		OperatorAllOutput: v,
	}
}

// OperatorAnyOutputAsOfInner1 is a convenience function that returns OperatorAnyOutput wrapped in OfInner1
func OperatorAnyOutputAsOfInner1(v *OperatorAnyOutput) OfInner1 {
	return OfInner1{
		OperatorAnyOutput: v,
	}
}

// OperatorNoneOutputAsOfInner1 is a convenience function that returns OperatorNoneOutput wrapped in OfInner1
func OperatorNoneOutputAsOfInner1(v *OperatorNoneOutput) OfInner1 {
	return OfInner1{
		OperatorNoneOutput: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OfInner1) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Expression
	err = newStrictDecoder(data).Decode(&dst.Expression)
	if err == nil {
		jsonExpression, _ := json.Marshal(dst.Expression)
		if string(jsonExpression) == "{}" { // empty struct
			dst.Expression = nil
		} else {
			if err = validator.Validate(dst.Expression); err != nil {
				dst.Expression = nil
			} else {
				match++
			}
		}
	} else {
		dst.Expression = nil
	}

	// try to unmarshal data into OperatorAllOutput
	err = newStrictDecoder(data).Decode(&dst.OperatorAllOutput)
	if err == nil {
		jsonOperatorAllOutput, _ := json.Marshal(dst.OperatorAllOutput)
		if string(jsonOperatorAllOutput) == "{}" { // empty struct
			dst.OperatorAllOutput = nil
		} else {
			if err = validator.Validate(dst.OperatorAllOutput); err != nil {
				dst.OperatorAllOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperatorAllOutput = nil
	}

	// try to unmarshal data into OperatorAnyOutput
	err = newStrictDecoder(data).Decode(&dst.OperatorAnyOutput)
	if err == nil {
		jsonOperatorAnyOutput, _ := json.Marshal(dst.OperatorAnyOutput)
		if string(jsonOperatorAnyOutput) == "{}" { // empty struct
			dst.OperatorAnyOutput = nil
		} else {
			if err = validator.Validate(dst.OperatorAnyOutput); err != nil {
				dst.OperatorAnyOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperatorAnyOutput = nil
	}

	// try to unmarshal data into OperatorNoneOutput
	err = newStrictDecoder(data).Decode(&dst.OperatorNoneOutput)
	if err == nil {
		jsonOperatorNoneOutput, _ := json.Marshal(dst.OperatorNoneOutput)
		if string(jsonOperatorNoneOutput) == "{}" { // empty struct
			dst.OperatorNoneOutput = nil
		} else {
			if err = validator.Validate(dst.OperatorNoneOutput); err != nil {
				dst.OperatorNoneOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperatorNoneOutput = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Expression = nil
		dst.OperatorAllOutput = nil
		dst.OperatorAnyOutput = nil
		dst.OperatorNoneOutput = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OfInner1)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(OfInner1): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(OfInner1)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OfInner1) MarshalJSON() ([]byte, error) {
	if src.Expression != nil {
		return json.Marshal(&src.Expression)
	}

	if src.OperatorAllOutput != nil {
		return json.Marshal(&src.OperatorAllOutput)
	}

	if src.OperatorAnyOutput != nil {
		return json.Marshal(&src.OperatorAnyOutput)
	}

	if src.OperatorNoneOutput != nil {
		return json.Marshal(&src.OperatorNoneOutput)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OfInner1) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Expression != nil {
		return obj.Expression
	}

	if obj.OperatorAllOutput != nil {
		return obj.OperatorAllOutput
	}

	if obj.OperatorAnyOutput != nil {
		return obj.OperatorAnyOutput
	}

	if obj.OperatorNoneOutput != nil {
		return obj.OperatorNoneOutput
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OfInner1) GetActualInstanceValue() (interface{}) {
	if obj.Expression != nil {
		return *obj.Expression
	}

	if obj.OperatorAllOutput != nil {
		return *obj.OperatorAllOutput
	}

	if obj.OperatorAnyOutput != nil {
		return *obj.OperatorAnyOutput
	}

	if obj.OperatorNoneOutput != nil {
		return *obj.OperatorNoneOutput
	}

	// all schemas are nil
	return nil
}

type NullableOfInner1 struct {
	value *OfInner1
	isSet bool
}

func (v NullableOfInner1) Get() *OfInner1 {
	return v.value
}

func (v *NullableOfInner1) Set(val *OfInner1) {
	v.value = val
	v.isSet = true
}

func (v NullableOfInner1) IsSet() bool {
	return v.isSet
}

func (v *NullableOfInner1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfInner1(val *OfInner1) *NullableOfInner1 {
	return &NullableOfInner1{value: val, isSet: true}
}

func (v NullableOfInner1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfInner1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


