/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProviderConnectionResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderConnectionResponseOneOf1{}

// ProviderConnectionResponseOneOf1 struct for ProviderConnectionResponseOneOf1
type ProviderConnectionResponseOneOf1 struct {
	Endpoint string `json:"endpoint"`
	// Whether a bearer token is configured. The token value is never returned.
	HasBearerToken bool `json:"has_bearer_token"`
	Location string `json:"location"`
	OrgId string `json:"org_id"`
	ProjectId string `json:"project_id"`
	Provider string `json:"provider"`
}

type _ProviderConnectionResponseOneOf1 ProviderConnectionResponseOneOf1

// NewProviderConnectionResponseOneOf1 instantiates a new ProviderConnectionResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderConnectionResponseOneOf1(endpoint string, hasBearerToken bool, location string, orgId string, projectId string, provider string) *ProviderConnectionResponseOneOf1 {
	this := ProviderConnectionResponseOneOf1{}
	this.Endpoint = endpoint
	this.HasBearerToken = hasBearerToken
	this.Location = location
	this.OrgId = orgId
	this.ProjectId = projectId
	this.Provider = provider
	return &this
}

// NewProviderConnectionResponseOneOf1WithDefaults instantiates a new ProviderConnectionResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderConnectionResponseOneOf1WithDefaults() *ProviderConnectionResponseOneOf1 {
	this := ProviderConnectionResponseOneOf1{}
	return &this
}

// GetEndpoint returns the Endpoint field value
func (o *ProviderConnectionResponseOneOf1) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf1) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *ProviderConnectionResponseOneOf1) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetHasBearerToken returns the HasBearerToken field value
func (o *ProviderConnectionResponseOneOf1) GetHasBearerToken() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasBearerToken
}

// GetHasBearerTokenOk returns a tuple with the HasBearerToken field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf1) GetHasBearerTokenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasBearerToken, true
}

// SetHasBearerToken sets field value
func (o *ProviderConnectionResponseOneOf1) SetHasBearerToken(v bool) {
	o.HasBearerToken = v
}

// GetLocation returns the Location field value
func (o *ProviderConnectionResponseOneOf1) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf1) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *ProviderConnectionResponseOneOf1) SetLocation(v string) {
	o.Location = v
}

// GetOrgId returns the OrgId field value
func (o *ProviderConnectionResponseOneOf1) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf1) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ProviderConnectionResponseOneOf1) SetOrgId(v string) {
	o.OrgId = v
}

// GetProjectId returns the ProjectId field value
func (o *ProviderConnectionResponseOneOf1) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf1) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ProviderConnectionResponseOneOf1) SetProjectId(v string) {
	o.ProjectId = v
}

// GetProvider returns the Provider field value
func (o *ProviderConnectionResponseOneOf1) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf1) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ProviderConnectionResponseOneOf1) SetProvider(v string) {
	o.Provider = v
}

func (o ProviderConnectionResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderConnectionResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["has_bearer_token"] = o.HasBearerToken
	toSerialize["location"] = o.Location
	toSerialize["org_id"] = o.OrgId
	toSerialize["project_id"] = o.ProjectId
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *ProviderConnectionResponseOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint",
		"has_bearer_token",
		"location",
		"org_id",
		"project_id",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderConnectionResponseOneOf1 := _ProviderConnectionResponseOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderConnectionResponseOneOf1)

	if err != nil {
		return err
	}

	*o = ProviderConnectionResponseOneOf1(varProviderConnectionResponseOneOf1)

	return err
}

type NullableProviderConnectionResponseOneOf1 struct {
	value *ProviderConnectionResponseOneOf1
	isSet bool
}

func (v NullableProviderConnectionResponseOneOf1) Get() *ProviderConnectionResponseOneOf1 {
	return v.value
}

func (v *NullableProviderConnectionResponseOneOf1) Set(val *ProviderConnectionResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderConnectionResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderConnectionResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderConnectionResponseOneOf1(val *ProviderConnectionResponseOneOf1) *NullableProviderConnectionResponseOneOf1 {
	return &NullableProviderConnectionResponseOneOf1{value: val, isSet: true}
}

func (v NullableProviderConnectionResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderConnectionResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


