/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"github.com/barndoor-ai/barndoor-go-sdk/v2/bdtime"
	"bytes"
	"fmt"
)

// checks if the ModelMappingWithProviderAndBudgetStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelMappingWithProviderAndBudgetStatus{}

// ModelMappingWithProviderAndBudgetStatus Same wrapper but for the cross-provider listing endpoint that returns `ModelMappingWithProvider` (extra `provider_name` field).
type ModelMappingWithProviderAndBudgetStatus struct {
	CreatedByEmail *string `json:"created_by_email,omitempty"`
	CreatedByName *string `json:"created_by_name,omitempty"`
	CreatedByUserId *string `json:"created_by_user_id,omitempty"`
	// Optional free text explaining *why* the last change was made (\"Raised for the Q3 batch job\", \"Vendor deprecated the old endpoint\").  Admin-authored and rendered in the portal, so it is untrusted input: length-capped here, escaped on render.
	LastChangeNote *string `json:"last_change_note,omitempty"`
	// When the change named by `last_modified_by_*` happened.  Its own column rather than the row's `updated_at`, because `updated_at` is bumped by writes nobody is attributed for -- pairing the two would date a named admin's edit to a background job's clock. See the V75 migration for the full reasoning.
	LastModifiedAt *bdtime.Time `json:"last_modified_at,omitempty"`
	LastModifiedByEmail *string `json:"last_modified_by_email,omitempty"`
	LastModifiedByName *string `json:"last_modified_by_name,omitempty"`
	LastModifiedByUserId *string `json:"last_modified_by_user_id,omitempty"`
	// See [`ModelMapping::auto_disabled_reason`].
	AutoDisabledReason *AutoDisabledReason `json:"auto_disabled_reason,omitempty"`
	BareAlias bool `json:"bare_alias"`
	// When this mapping was created. Rows predating the column are backfilled from the owning provider — see migration V58.
	CreatedAt bdtime.Time `json:"created_at"`
	Enabled bool `json:"enabled"`
	Id string `json:"id"`
	ModelAlias string `json:"model_alias"`
	Priority int32 `json:"priority"`
	ProviderAuthType string `json:"provider_auth_type"`
	ProviderId string `json:"provider_id"`
	ProviderName string `json:"provider_name"`
	RequestTimeoutSecs *int32 `json:"request_timeout_secs,omitempty"`
	RetryOn429Count int32 `json:"retry_on_429_count"`
	RetryOn429MaxWaitSecs int32 `json:"retry_on_429_max_wait_secs"`
	// See [`ModelMapping::source`].
	Source ModelSource `json:"source"`
	StreamIdleTimeoutSecs *int32 `json:"stream_idle_timeout_secs,omitempty"`
	UpstreamModel string `json:"upstream_model"`
	BudgetStatus NullableBudgetTargetStatus `json:"budget_status,omitempty"`
	EffectivePricing EffectivePricing `json:"effective_pricing"`
	RouteHealthStatus NullableRouteHealthStatus `json:"route_health_status,omitempty"`
	// See [`ModelMappingWithBudgetStatus::stale_status`].
	StaleStatus NullableModelStaleStatus `json:"stale_status,omitempty"`
}

type _ModelMappingWithProviderAndBudgetStatus ModelMappingWithProviderAndBudgetStatus

// NewModelMappingWithProviderAndBudgetStatus instantiates a new ModelMappingWithProviderAndBudgetStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelMappingWithProviderAndBudgetStatus(bareAlias bool, createdAt bdtime.Time, enabled bool, id string, modelAlias string, priority int32, providerAuthType string, providerId string, providerName string, retryOn429Count int32, retryOn429MaxWaitSecs int32, source ModelSource, upstreamModel string, effectivePricing EffectivePricing) *ModelMappingWithProviderAndBudgetStatus {
	this := ModelMappingWithProviderAndBudgetStatus{}
	this.BareAlias = bareAlias
	this.CreatedAt = createdAt
	this.Enabled = enabled
	this.Id = id
	this.ModelAlias = modelAlias
	this.Priority = priority
	this.ProviderAuthType = providerAuthType
	this.ProviderId = providerId
	this.ProviderName = providerName
	this.RetryOn429Count = retryOn429Count
	this.RetryOn429MaxWaitSecs = retryOn429MaxWaitSecs
	this.Source = source
	this.UpstreamModel = upstreamModel
	this.EffectivePricing = effectivePricing
	return &this
}

// NewModelMappingWithProviderAndBudgetStatusWithDefaults instantiates a new ModelMappingWithProviderAndBudgetStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelMappingWithProviderAndBudgetStatusWithDefaults() *ModelMappingWithProviderAndBudgetStatus {
	this := ModelMappingWithProviderAndBudgetStatus{}
	return &this
}

// GetCreatedByEmail returns the CreatedByEmail field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedByEmail() string {
	if o == nil || IsNil(o.CreatedByEmail) {
		var ret string
		return ret
	}
	return *o.CreatedByEmail
}

// GetCreatedByEmailOk returns a tuple with the CreatedByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedByEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByEmail) {
		return nil, false
	}
	return o.CreatedByEmail, true
}

// HasCreatedByEmail returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasCreatedByEmail() bool {
	if o != nil && !IsNil(o.CreatedByEmail) {
		return true
	}

	return false
}

// SetCreatedByEmail gets a reference to the given string and assigns it to the CreatedByEmail field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetCreatedByEmail(v string) {
	o.CreatedByEmail = &v
}

// GetCreatedByName returns the CreatedByName field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedByName() string {
	if o == nil || IsNil(o.CreatedByName) {
		var ret string
		return ret
	}
	return *o.CreatedByName
}

// GetCreatedByNameOk returns a tuple with the CreatedByName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedByNameOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByName) {
		return nil, false
	}
	return o.CreatedByName, true
}

// HasCreatedByName returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasCreatedByName() bool {
	if o != nil && !IsNil(o.CreatedByName) {
		return true
	}

	return false
}

// SetCreatedByName gets a reference to the given string and assigns it to the CreatedByName field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetCreatedByName(v string) {
	o.CreatedByName = &v
}

// GetCreatedByUserId returns the CreatedByUserId field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedByUserId() string {
	if o == nil || IsNil(o.CreatedByUserId) {
		var ret string
		return ret
	}
	return *o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByUserId) {
		return nil, false
	}
	return o.CreatedByUserId, true
}

// HasCreatedByUserId returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasCreatedByUserId() bool {
	if o != nil && !IsNil(o.CreatedByUserId) {
		return true
	}

	return false
}

// SetCreatedByUserId gets a reference to the given string and assigns it to the CreatedByUserId field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetCreatedByUserId(v string) {
	o.CreatedByUserId = &v
}

// GetLastChangeNote returns the LastChangeNote field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastChangeNote() string {
	if o == nil || IsNil(o.LastChangeNote) {
		var ret string
		return ret
	}
	return *o.LastChangeNote
}

// GetLastChangeNoteOk returns a tuple with the LastChangeNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastChangeNoteOk() (*string, bool) {
	if o == nil || IsNil(o.LastChangeNote) {
		return nil, false
	}
	return o.LastChangeNote, true
}

// HasLastChangeNote returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasLastChangeNote() bool {
	if o != nil && !IsNil(o.LastChangeNote) {
		return true
	}

	return false
}

// SetLastChangeNote gets a reference to the given string and assigns it to the LastChangeNote field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetLastChangeNote(v string) {
	o.LastChangeNote = &v
}

// GetLastModifiedAt returns the LastModifiedAt field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedAt() bdtime.Time {
	if o == nil || IsNil(o.LastModifiedAt) {
		var ret bdtime.Time
		return ret
	}
	return *o.LastModifiedAt
}

// GetLastModifiedAtOk returns a tuple with the LastModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedAtOk() (*bdtime.Time, bool) {
	if o == nil || IsNil(o.LastModifiedAt) {
		return nil, false
	}
	return o.LastModifiedAt, true
}

// HasLastModifiedAt returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasLastModifiedAt() bool {
	if o != nil && !IsNil(o.LastModifiedAt) {
		return true
	}

	return false
}

// SetLastModifiedAt gets a reference to the given bdtime.Time and assigns it to the LastModifiedAt field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetLastModifiedAt(v bdtime.Time) {
	o.LastModifiedAt = &v
}

// GetLastModifiedByEmail returns the LastModifiedByEmail field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedByEmail() string {
	if o == nil || IsNil(o.LastModifiedByEmail) {
		var ret string
		return ret
	}
	return *o.LastModifiedByEmail
}

// GetLastModifiedByEmailOk returns a tuple with the LastModifiedByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedByEmailOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedByEmail) {
		return nil, false
	}
	return o.LastModifiedByEmail, true
}

// HasLastModifiedByEmail returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasLastModifiedByEmail() bool {
	if o != nil && !IsNil(o.LastModifiedByEmail) {
		return true
	}

	return false
}

// SetLastModifiedByEmail gets a reference to the given string and assigns it to the LastModifiedByEmail field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetLastModifiedByEmail(v string) {
	o.LastModifiedByEmail = &v
}

// GetLastModifiedByName returns the LastModifiedByName field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedByName() string {
	if o == nil || IsNil(o.LastModifiedByName) {
		var ret string
		return ret
	}
	return *o.LastModifiedByName
}

// GetLastModifiedByNameOk returns a tuple with the LastModifiedByName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedByNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedByName) {
		return nil, false
	}
	return o.LastModifiedByName, true
}

// HasLastModifiedByName returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasLastModifiedByName() bool {
	if o != nil && !IsNil(o.LastModifiedByName) {
		return true
	}

	return false
}

// SetLastModifiedByName gets a reference to the given string and assigns it to the LastModifiedByName field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetLastModifiedByName(v string) {
	o.LastModifiedByName = &v
}

// GetLastModifiedByUserId returns the LastModifiedByUserId field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedByUserId() string {
	if o == nil || IsNil(o.LastModifiedByUserId) {
		var ret string
		return ret
	}
	return *o.LastModifiedByUserId
}

// GetLastModifiedByUserIdOk returns a tuple with the LastModifiedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetLastModifiedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedByUserId) {
		return nil, false
	}
	return o.LastModifiedByUserId, true
}

// HasLastModifiedByUserId returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasLastModifiedByUserId() bool {
	if o != nil && !IsNil(o.LastModifiedByUserId) {
		return true
	}

	return false
}

// SetLastModifiedByUserId gets a reference to the given string and assigns it to the LastModifiedByUserId field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetLastModifiedByUserId(v string) {
	o.LastModifiedByUserId = &v
}

// GetAutoDisabledReason returns the AutoDisabledReason field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetAutoDisabledReason() AutoDisabledReason {
	if o == nil || IsNil(o.AutoDisabledReason) {
		var ret AutoDisabledReason
		return ret
	}
	return *o.AutoDisabledReason
}

// GetAutoDisabledReasonOk returns a tuple with the AutoDisabledReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetAutoDisabledReasonOk() (*AutoDisabledReason, bool) {
	if o == nil || IsNil(o.AutoDisabledReason) {
		return nil, false
	}
	return o.AutoDisabledReason, true
}

// HasAutoDisabledReason returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasAutoDisabledReason() bool {
	if o != nil && !IsNil(o.AutoDisabledReason) {
		return true
	}

	return false
}

// SetAutoDisabledReason gets a reference to the given AutoDisabledReason and assigns it to the AutoDisabledReason field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetAutoDisabledReason(v AutoDisabledReason) {
	o.AutoDisabledReason = &v
}

// GetBareAlias returns the BareAlias field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetBareAlias() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BareAlias
}

// GetBareAliasOk returns a tuple with the BareAlias field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetBareAliasOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BareAlias, true
}

// SetBareAlias sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetBareAlias(v bool) {
	o.BareAlias = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedAt() bdtime.Time {
	if o == nil {
		var ret bdtime.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetCreatedAtOk() (*bdtime.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetCreatedAt(v bdtime.Time) {
	o.CreatedAt = v
}

// GetEnabled returns the Enabled field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetEnabled(v bool) {
	o.Enabled = v
}

// GetId returns the Id field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetId(v string) {
	o.Id = v
}

// GetModelAlias returns the ModelAlias field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetModelAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelAlias
}

// GetModelAliasOk returns a tuple with the ModelAlias field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetModelAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelAlias, true
}

// SetModelAlias sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetModelAlias(v string) {
	o.ModelAlias = v
}

// GetPriority returns the Priority field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetPriority(v int32) {
	o.Priority = v
}

// GetProviderAuthType returns the ProviderAuthType field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetProviderAuthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderAuthType
}

// GetProviderAuthTypeOk returns a tuple with the ProviderAuthType field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetProviderAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderAuthType, true
}

// SetProviderAuthType sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetProviderAuthType(v string) {
	o.ProviderAuthType = v
}

// GetProviderId returns the ProviderId field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetProviderId(v string) {
	o.ProviderId = v
}

// GetProviderName returns the ProviderName field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetProviderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetProviderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderName, true
}

// SetProviderName sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetProviderName(v string) {
	o.ProviderName = v
}

// GetRequestTimeoutSecs returns the RequestTimeoutSecs field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetRequestTimeoutSecs() int32 {
	if o == nil || IsNil(o.RequestTimeoutSecs) {
		var ret int32
		return ret
	}
	return *o.RequestTimeoutSecs
}

// GetRequestTimeoutSecsOk returns a tuple with the RequestTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetRequestTimeoutSecsOk() (*int32, bool) {
	if o == nil || IsNil(o.RequestTimeoutSecs) {
		return nil, false
	}
	return o.RequestTimeoutSecs, true
}

// HasRequestTimeoutSecs returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasRequestTimeoutSecs() bool {
	if o != nil && !IsNil(o.RequestTimeoutSecs) {
		return true
	}

	return false
}

// SetRequestTimeoutSecs gets a reference to the given int32 and assigns it to the RequestTimeoutSecs field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetRequestTimeoutSecs(v int32) {
	o.RequestTimeoutSecs = &v
}

// GetRetryOn429Count returns the RetryOn429Count field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetRetryOn429Count() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetryOn429Count
}

// GetRetryOn429CountOk returns a tuple with the RetryOn429Count field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetRetryOn429CountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryOn429Count, true
}

// SetRetryOn429Count sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetRetryOn429Count(v int32) {
	o.RetryOn429Count = v
}

// GetRetryOn429MaxWaitSecs returns the RetryOn429MaxWaitSecs field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetRetryOn429MaxWaitSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetryOn429MaxWaitSecs
}

// GetRetryOn429MaxWaitSecsOk returns a tuple with the RetryOn429MaxWaitSecs field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetRetryOn429MaxWaitSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryOn429MaxWaitSecs, true
}

// SetRetryOn429MaxWaitSecs sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetRetryOn429MaxWaitSecs(v int32) {
	o.RetryOn429MaxWaitSecs = v
}

// GetSource returns the Source field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetSource() ModelSource {
	if o == nil {
		var ret ModelSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetSourceOk() (*ModelSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetSource(v ModelSource) {
	o.Source = v
}

// GetStreamIdleTimeoutSecs returns the StreamIdleTimeoutSecs field value if set, zero value otherwise.
func (o *ModelMappingWithProviderAndBudgetStatus) GetStreamIdleTimeoutSecs() int32 {
	if o == nil || IsNil(o.StreamIdleTimeoutSecs) {
		var ret int32
		return ret
	}
	return *o.StreamIdleTimeoutSecs
}

// GetStreamIdleTimeoutSecsOk returns a tuple with the StreamIdleTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetStreamIdleTimeoutSecsOk() (*int32, bool) {
	if o == nil || IsNil(o.StreamIdleTimeoutSecs) {
		return nil, false
	}
	return o.StreamIdleTimeoutSecs, true
}

// HasStreamIdleTimeoutSecs returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasStreamIdleTimeoutSecs() bool {
	if o != nil && !IsNil(o.StreamIdleTimeoutSecs) {
		return true
	}

	return false
}

// SetStreamIdleTimeoutSecs gets a reference to the given int32 and assigns it to the StreamIdleTimeoutSecs field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetStreamIdleTimeoutSecs(v int32) {
	o.StreamIdleTimeoutSecs = &v
}

// GetUpstreamModel returns the UpstreamModel field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetUpstreamModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpstreamModel
}

// GetUpstreamModelOk returns a tuple with the UpstreamModel field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetUpstreamModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpstreamModel, true
}

// SetUpstreamModel sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetUpstreamModel(v string) {
	o.UpstreamModel = v
}

// GetBudgetStatus returns the BudgetStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelMappingWithProviderAndBudgetStatus) GetBudgetStatus() BudgetTargetStatus {
	if o == nil || IsNil(o.BudgetStatus.Get()) {
		var ret BudgetTargetStatus
		return ret
	}
	return *o.BudgetStatus.Get()
}

// GetBudgetStatusOk returns a tuple with the BudgetStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelMappingWithProviderAndBudgetStatus) GetBudgetStatusOk() (*BudgetTargetStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.BudgetStatus.Get(), o.BudgetStatus.IsSet()
}

// HasBudgetStatus returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasBudgetStatus() bool {
	if o != nil && o.BudgetStatus.IsSet() {
		return true
	}

	return false
}

// SetBudgetStatus gets a reference to the given NullableBudgetTargetStatus and assigns it to the BudgetStatus field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetBudgetStatus(v BudgetTargetStatus) {
	o.BudgetStatus.Set(&v)
}
// SetBudgetStatusNil sets the value for BudgetStatus to be an explicit nil
func (o *ModelMappingWithProviderAndBudgetStatus) SetBudgetStatusNil() {
	o.BudgetStatus.Set(nil)
}

// UnsetBudgetStatus ensures that no value is present for BudgetStatus, not even an explicit nil
func (o *ModelMappingWithProviderAndBudgetStatus) UnsetBudgetStatus() {
	o.BudgetStatus.Unset()
}

// GetEffectivePricing returns the EffectivePricing field value
func (o *ModelMappingWithProviderAndBudgetStatus) GetEffectivePricing() EffectivePricing {
	if o == nil {
		var ret EffectivePricing
		return ret
	}

	return o.EffectivePricing
}

// GetEffectivePricingOk returns a tuple with the EffectivePricing field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) GetEffectivePricingOk() (*EffectivePricing, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectivePricing, true
}

// SetEffectivePricing sets field value
func (o *ModelMappingWithProviderAndBudgetStatus) SetEffectivePricing(v EffectivePricing) {
	o.EffectivePricing = v
}

// GetRouteHealthStatus returns the RouteHealthStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelMappingWithProviderAndBudgetStatus) GetRouteHealthStatus() RouteHealthStatus {
	if o == nil || IsNil(o.RouteHealthStatus.Get()) {
		var ret RouteHealthStatus
		return ret
	}
	return *o.RouteHealthStatus.Get()
}

// GetRouteHealthStatusOk returns a tuple with the RouteHealthStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelMappingWithProviderAndBudgetStatus) GetRouteHealthStatusOk() (*RouteHealthStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteHealthStatus.Get(), o.RouteHealthStatus.IsSet()
}

// HasRouteHealthStatus returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasRouteHealthStatus() bool {
	if o != nil && o.RouteHealthStatus.IsSet() {
		return true
	}

	return false
}

// SetRouteHealthStatus gets a reference to the given NullableRouteHealthStatus and assigns it to the RouteHealthStatus field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetRouteHealthStatus(v RouteHealthStatus) {
	o.RouteHealthStatus.Set(&v)
}
// SetRouteHealthStatusNil sets the value for RouteHealthStatus to be an explicit nil
func (o *ModelMappingWithProviderAndBudgetStatus) SetRouteHealthStatusNil() {
	o.RouteHealthStatus.Set(nil)
}

// UnsetRouteHealthStatus ensures that no value is present for RouteHealthStatus, not even an explicit nil
func (o *ModelMappingWithProviderAndBudgetStatus) UnsetRouteHealthStatus() {
	o.RouteHealthStatus.Unset()
}

// GetStaleStatus returns the StaleStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelMappingWithProviderAndBudgetStatus) GetStaleStatus() ModelStaleStatus {
	if o == nil || IsNil(o.StaleStatus.Get()) {
		var ret ModelStaleStatus
		return ret
	}
	return *o.StaleStatus.Get()
}

// GetStaleStatusOk returns a tuple with the StaleStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelMappingWithProviderAndBudgetStatus) GetStaleStatusOk() (*ModelStaleStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.StaleStatus.Get(), o.StaleStatus.IsSet()
}

// HasStaleStatus returns a boolean if a field has been set.
func (o *ModelMappingWithProviderAndBudgetStatus) HasStaleStatus() bool {
	if o != nil && o.StaleStatus.IsSet() {
		return true
	}

	return false
}

// SetStaleStatus gets a reference to the given NullableModelStaleStatus and assigns it to the StaleStatus field.
func (o *ModelMappingWithProviderAndBudgetStatus) SetStaleStatus(v ModelStaleStatus) {
	o.StaleStatus.Set(&v)
}
// SetStaleStatusNil sets the value for StaleStatus to be an explicit nil
func (o *ModelMappingWithProviderAndBudgetStatus) SetStaleStatusNil() {
	o.StaleStatus.Set(nil)
}

// UnsetStaleStatus ensures that no value is present for StaleStatus, not even an explicit nil
func (o *ModelMappingWithProviderAndBudgetStatus) UnsetStaleStatus() {
	o.StaleStatus.Unset()
}

func (o ModelMappingWithProviderAndBudgetStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelMappingWithProviderAndBudgetStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedByEmail) {
		toSerialize["created_by_email"] = o.CreatedByEmail
	}
	if !IsNil(o.CreatedByName) {
		toSerialize["created_by_name"] = o.CreatedByName
	}
	if !IsNil(o.CreatedByUserId) {
		toSerialize["created_by_user_id"] = o.CreatedByUserId
	}
	if !IsNil(o.LastChangeNote) {
		toSerialize["last_change_note"] = o.LastChangeNote
	}
	if !IsNil(o.LastModifiedAt) {
		toSerialize["last_modified_at"] = o.LastModifiedAt
	}
	if !IsNil(o.LastModifiedByEmail) {
		toSerialize["last_modified_by_email"] = o.LastModifiedByEmail
	}
	if !IsNil(o.LastModifiedByName) {
		toSerialize["last_modified_by_name"] = o.LastModifiedByName
	}
	if !IsNil(o.LastModifiedByUserId) {
		toSerialize["last_modified_by_user_id"] = o.LastModifiedByUserId
	}
	if !IsNil(o.AutoDisabledReason) {
		toSerialize["auto_disabled_reason"] = o.AutoDisabledReason
	}
	toSerialize["bare_alias"] = o.BareAlias
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["enabled"] = o.Enabled
	toSerialize["id"] = o.Id
	toSerialize["model_alias"] = o.ModelAlias
	toSerialize["priority"] = o.Priority
	toSerialize["provider_auth_type"] = o.ProviderAuthType
	toSerialize["provider_id"] = o.ProviderId
	toSerialize["provider_name"] = o.ProviderName
	if !IsNil(o.RequestTimeoutSecs) {
		toSerialize["request_timeout_secs"] = o.RequestTimeoutSecs
	}
	toSerialize["retry_on_429_count"] = o.RetryOn429Count
	toSerialize["retry_on_429_max_wait_secs"] = o.RetryOn429MaxWaitSecs
	toSerialize["source"] = o.Source
	if !IsNil(o.StreamIdleTimeoutSecs) {
		toSerialize["stream_idle_timeout_secs"] = o.StreamIdleTimeoutSecs
	}
	toSerialize["upstream_model"] = o.UpstreamModel
	if o.BudgetStatus.IsSet() {
		toSerialize["budget_status"] = o.BudgetStatus.Get()
	}
	toSerialize["effective_pricing"] = o.EffectivePricing
	if o.RouteHealthStatus.IsSet() {
		toSerialize["route_health_status"] = o.RouteHealthStatus.Get()
	}
	if o.StaleStatus.IsSet() {
		toSerialize["stale_status"] = o.StaleStatus.Get()
	}
	return toSerialize, nil
}

func (o *ModelMappingWithProviderAndBudgetStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bare_alias",
		"created_at",
		"enabled",
		"id",
		"model_alias",
		"priority",
		"provider_auth_type",
		"provider_id",
		"provider_name",
		"retry_on_429_count",
		"retry_on_429_max_wait_secs",
		"source",
		"upstream_model",
		"effective_pricing",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelMappingWithProviderAndBudgetStatus := _ModelMappingWithProviderAndBudgetStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelMappingWithProviderAndBudgetStatus)

	if err != nil {
		return err
	}

	*o = ModelMappingWithProviderAndBudgetStatus(varModelMappingWithProviderAndBudgetStatus)

	return err
}

type NullableModelMappingWithProviderAndBudgetStatus struct {
	value *ModelMappingWithProviderAndBudgetStatus
	isSet bool
}

func (v NullableModelMappingWithProviderAndBudgetStatus) Get() *ModelMappingWithProviderAndBudgetStatus {
	return v.value
}

func (v *NullableModelMappingWithProviderAndBudgetStatus) Set(val *ModelMappingWithProviderAndBudgetStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableModelMappingWithProviderAndBudgetStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableModelMappingWithProviderAndBudgetStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelMappingWithProviderAndBudgetStatus(val *ModelMappingWithProviderAndBudgetStatus) *NullableModelMappingWithProviderAndBudgetStatus {
	return &NullableModelMappingWithProviderAndBudgetStatus{value: val, isSet: true}
}

func (v NullableModelMappingWithProviderAndBudgetStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelMappingWithProviderAndBudgetStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


