/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddRouteGroupMembersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddRouteGroupMembersRequest{}

// AddRouteGroupMembersRequest struct for AddRouteGroupMembersRequest
type AddRouteGroupMembersRequest struct {
	// Optional free-text note explaining why these routes were added (BCP-3998). Recorded on the group, which is where membership attribution lives — see the `ModelRouteGroup::attribution` docs.
	ChangeNote NullableString `json:"change_note,omitempty"`
	ModelAliases []string `json:"model_aliases"`
}

type _AddRouteGroupMembersRequest AddRouteGroupMembersRequest

// NewAddRouteGroupMembersRequest instantiates a new AddRouteGroupMembersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddRouteGroupMembersRequest(modelAliases []string) *AddRouteGroupMembersRequest {
	this := AddRouteGroupMembersRequest{}
	this.ModelAliases = modelAliases
	return &this
}

// NewAddRouteGroupMembersRequestWithDefaults instantiates a new AddRouteGroupMembersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddRouteGroupMembersRequestWithDefaults() *AddRouteGroupMembersRequest {
	this := AddRouteGroupMembersRequest{}
	return &this
}

// GetChangeNote returns the ChangeNote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddRouteGroupMembersRequest) GetChangeNote() string {
	if o == nil || IsNil(o.ChangeNote.Get()) {
		var ret string
		return ret
	}
	return *o.ChangeNote.Get()
}

// GetChangeNoteOk returns a tuple with the ChangeNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddRouteGroupMembersRequest) GetChangeNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeNote.Get(), o.ChangeNote.IsSet()
}

// HasChangeNote returns a boolean if a field has been set.
func (o *AddRouteGroupMembersRequest) HasChangeNote() bool {
	if o != nil && o.ChangeNote.IsSet() {
		return true
	}

	return false
}

// SetChangeNote gets a reference to the given NullableString and assigns it to the ChangeNote field.
func (o *AddRouteGroupMembersRequest) SetChangeNote(v string) {
	o.ChangeNote.Set(&v)
}
// SetChangeNoteNil sets the value for ChangeNote to be an explicit nil
func (o *AddRouteGroupMembersRequest) SetChangeNoteNil() {
	o.ChangeNote.Set(nil)
}

// UnsetChangeNote ensures that no value is present for ChangeNote, not even an explicit nil
func (o *AddRouteGroupMembersRequest) UnsetChangeNote() {
	o.ChangeNote.Unset()
}

// GetModelAliases returns the ModelAliases field value
func (o *AddRouteGroupMembersRequest) GetModelAliases() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ModelAliases
}

// GetModelAliasesOk returns a tuple with the ModelAliases field value
// and a boolean to check if the value has been set.
func (o *AddRouteGroupMembersRequest) GetModelAliasesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModelAliases, true
}

// SetModelAliases sets field value
func (o *AddRouteGroupMembersRequest) SetModelAliases(v []string) {
	o.ModelAliases = v
}

func (o AddRouteGroupMembersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddRouteGroupMembersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ChangeNote.IsSet() {
		toSerialize["change_note"] = o.ChangeNote.Get()
	}
	toSerialize["model_aliases"] = o.ModelAliases
	return toSerialize, nil
}

func (o *AddRouteGroupMembersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model_aliases",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddRouteGroupMembersRequest := _AddRouteGroupMembersRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddRouteGroupMembersRequest)

	if err != nil {
		return err
	}

	*o = AddRouteGroupMembersRequest(varAddRouteGroupMembersRequest)

	return err
}

type NullableAddRouteGroupMembersRequest struct {
	value *AddRouteGroupMembersRequest
	isSet bool
}

func (v NullableAddRouteGroupMembersRequest) Get() *AddRouteGroupMembersRequest {
	return v.value
}

func (v *NullableAddRouteGroupMembersRequest) Set(val *AddRouteGroupMembersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddRouteGroupMembersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddRouteGroupMembersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddRouteGroupMembersRequest(val *AddRouteGroupMembersRequest) *NullableAddRouteGroupMembersRequest {
	return &NullableAddRouteGroupMembersRequest{value: val, isSet: true}
}

func (v NullableAddRouteGroupMembersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddRouteGroupMembersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


