/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRouteGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRouteGroupRequest{}

// CreateRouteGroupRequest struct for CreateRouteGroupRequest
type CreateRouteGroupRequest struct {
	// Optional free-text note explaining why this group was created (BCP-3998). Distinct from `description`, which describes what the group *is* and persists; this describes one change and is replaced by the next edit's note.
	ChangeNote NullableString `json:"change_note,omitempty"`
	Description *string `json:"description,omitempty"`
	// Optional initial membership, so \"create a group from the routes I have selected\" is one request instead of two.
	ModelAliases []string `json:"model_aliases,omitempty"`
	Name string `json:"name"`
}

type _CreateRouteGroupRequest CreateRouteGroupRequest

// NewCreateRouteGroupRequest instantiates a new CreateRouteGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRouteGroupRequest(name string) *CreateRouteGroupRequest {
	this := CreateRouteGroupRequest{}
	this.Name = name
	return &this
}

// NewCreateRouteGroupRequestWithDefaults instantiates a new CreateRouteGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRouteGroupRequestWithDefaults() *CreateRouteGroupRequest {
	this := CreateRouteGroupRequest{}
	return &this
}

// GetChangeNote returns the ChangeNote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateRouteGroupRequest) GetChangeNote() string {
	if o == nil || IsNil(o.ChangeNote.Get()) {
		var ret string
		return ret
	}
	return *o.ChangeNote.Get()
}

// GetChangeNoteOk returns a tuple with the ChangeNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateRouteGroupRequest) GetChangeNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeNote.Get(), o.ChangeNote.IsSet()
}

// HasChangeNote returns a boolean if a field has been set.
func (o *CreateRouteGroupRequest) HasChangeNote() bool {
	if o != nil && o.ChangeNote.IsSet() {
		return true
	}

	return false
}

// SetChangeNote gets a reference to the given NullableString and assigns it to the ChangeNote field.
func (o *CreateRouteGroupRequest) SetChangeNote(v string) {
	o.ChangeNote.Set(&v)
}
// SetChangeNoteNil sets the value for ChangeNote to be an explicit nil
func (o *CreateRouteGroupRequest) SetChangeNoteNil() {
	o.ChangeNote.Set(nil)
}

// UnsetChangeNote ensures that no value is present for ChangeNote, not even an explicit nil
func (o *CreateRouteGroupRequest) UnsetChangeNote() {
	o.ChangeNote.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateRouteGroupRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRouteGroupRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateRouteGroupRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateRouteGroupRequest) SetDescription(v string) {
	o.Description = &v
}

// GetModelAliases returns the ModelAliases field value if set, zero value otherwise.
func (o *CreateRouteGroupRequest) GetModelAliases() []string {
	if o == nil || IsNil(o.ModelAliases) {
		var ret []string
		return ret
	}
	return o.ModelAliases
}

// GetModelAliasesOk returns a tuple with the ModelAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRouteGroupRequest) GetModelAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.ModelAliases) {
		return nil, false
	}
	return o.ModelAliases, true
}

// HasModelAliases returns a boolean if a field has been set.
func (o *CreateRouteGroupRequest) HasModelAliases() bool {
	if o != nil && !IsNil(o.ModelAliases) {
		return true
	}

	return false
}

// SetModelAliases gets a reference to the given []string and assigns it to the ModelAliases field.
func (o *CreateRouteGroupRequest) SetModelAliases(v []string) {
	o.ModelAliases = v
}

// GetName returns the Name field value
func (o *CreateRouteGroupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRouteGroupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRouteGroupRequest) SetName(v string) {
	o.Name = v
}

func (o CreateRouteGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRouteGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ChangeNote.IsSet() {
		toSerialize["change_note"] = o.ChangeNote.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ModelAliases) {
		toSerialize["model_aliases"] = o.ModelAliases
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateRouteGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRouteGroupRequest := _CreateRouteGroupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRouteGroupRequest)

	if err != nil {
		return err
	}

	*o = CreateRouteGroupRequest(varCreateRouteGroupRequest)

	return err
}

type NullableCreateRouteGroupRequest struct {
	value *CreateRouteGroupRequest
	isSet bool
}

func (v NullableCreateRouteGroupRequest) Get() *CreateRouteGroupRequest {
	return v.value
}

func (v *NullableCreateRouteGroupRequest) Set(val *CreateRouteGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRouteGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRouteGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRouteGroupRequest(val *CreateRouteGroupRequest) *NullableCreateRouteGroupRequest {
	return &NullableCreateRouteGroupRequest{value: val, isSet: true}
}

func (v NullableCreateRouteGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRouteGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


