/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiKeyDisabledResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyDisabledResponse{}

// ApiKeyDisabledResponse `PATCH /admin/api-keys/{id}` — echoes the disabled state now in effect.
type ApiKeyDisabledResponse struct {
	// The key's disabled flag after the update, echoing the request.
	Disabled bool `json:"disabled"`
}

type _ApiKeyDisabledResponse ApiKeyDisabledResponse

// NewApiKeyDisabledResponse instantiates a new ApiKeyDisabledResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyDisabledResponse(disabled bool) *ApiKeyDisabledResponse {
	this := ApiKeyDisabledResponse{}
	this.Disabled = disabled
	return &this
}

// NewApiKeyDisabledResponseWithDefaults instantiates a new ApiKeyDisabledResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyDisabledResponseWithDefaults() *ApiKeyDisabledResponse {
	this := ApiKeyDisabledResponse{}
	return &this
}

// GetDisabled returns the Disabled field value
func (o *ApiKeyDisabledResponse) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *ApiKeyDisabledResponse) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *ApiKeyDisabledResponse) SetDisabled(v bool) {
	o.Disabled = v
}

func (o ApiKeyDisabledResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyDisabledResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["disabled"] = o.Disabled
	return toSerialize, nil
}

func (o *ApiKeyDisabledResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"disabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiKeyDisabledResponse := _ApiKeyDisabledResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiKeyDisabledResponse)

	if err != nil {
		return err
	}

	*o = ApiKeyDisabledResponse(varApiKeyDisabledResponse)

	return err
}

type NullableApiKeyDisabledResponse struct {
	value *ApiKeyDisabledResponse
	isSet bool
}

func (v NullableApiKeyDisabledResponse) Get() *ApiKeyDisabledResponse {
	return v.value
}

func (v *NullableApiKeyDisabledResponse) Set(val *ApiKeyDisabledResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyDisabledResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyDisabledResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyDisabledResponse(val *ApiKeyDisabledResponse) *NullableApiKeyDisabledResponse {
	return &NullableApiKeyDisabledResponse{value: val, isSet: true}
}

func (v NullableApiKeyDisabledResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyDisabledResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


