/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ModelAccessTarget - A single restriction target inside a [`ModelAccessPolicy`].  Targets answer the question \"*what* is being allowed/denied?\" — distinct from `scope_type`, which answers \"*who* is the policy applied to?\". A policy's `targets` list is OR-ed when matching: a request matches the policy if any one of its targets matches the (provider, model) pair.  Serialised to JSONB with a `kind` discriminator so it round-trips cleanly through the admin REST API.  `ModelAlias` matches against the literal `model` field in the request. `Model` matches against the *resolved upstream model* — i.e. the underlying model the routed mapping points at. The two are distinct because the admin UI lets admins pick along either dimension: a `goto` alias fanned out across providers is best expressed with `ModelAlias`, while \"block any request that ends up at gpt-4o-mini regardless of the alias used\" is best expressed with `Model` (so it fires even when `goto` resolves to `gpt-4o-mini`).
type ModelAccessTarget struct {
	ModelAccessTargetOneOf *ModelAccessTargetOneOf
	ModelAccessTargetOneOf1 *ModelAccessTargetOneOf1
	ModelAccessTargetOneOf2 *ModelAccessTargetOneOf2
	ModelAccessTargetOneOf3 *ModelAccessTargetOneOf3
	ModelAccessTargetOneOf4 *ModelAccessTargetOneOf4
}

// ModelAccessTargetOneOfAsModelAccessTarget is a convenience function that returns ModelAccessTargetOneOf wrapped in ModelAccessTarget
func ModelAccessTargetOneOfAsModelAccessTarget(v *ModelAccessTargetOneOf) ModelAccessTarget {
	return ModelAccessTarget{
		ModelAccessTargetOneOf: v,
	}
}

// ModelAccessTargetOneOf1AsModelAccessTarget is a convenience function that returns ModelAccessTargetOneOf1 wrapped in ModelAccessTarget
func ModelAccessTargetOneOf1AsModelAccessTarget(v *ModelAccessTargetOneOf1) ModelAccessTarget {
	return ModelAccessTarget{
		ModelAccessTargetOneOf1: v,
	}
}

// ModelAccessTargetOneOf2AsModelAccessTarget is a convenience function that returns ModelAccessTargetOneOf2 wrapped in ModelAccessTarget
func ModelAccessTargetOneOf2AsModelAccessTarget(v *ModelAccessTargetOneOf2) ModelAccessTarget {
	return ModelAccessTarget{
		ModelAccessTargetOneOf2: v,
	}
}

// ModelAccessTargetOneOf3AsModelAccessTarget is a convenience function that returns ModelAccessTargetOneOf3 wrapped in ModelAccessTarget
func ModelAccessTargetOneOf3AsModelAccessTarget(v *ModelAccessTargetOneOf3) ModelAccessTarget {
	return ModelAccessTarget{
		ModelAccessTargetOneOf3: v,
	}
}

// ModelAccessTargetOneOf4AsModelAccessTarget is a convenience function that returns ModelAccessTargetOneOf4 wrapped in ModelAccessTarget
func ModelAccessTargetOneOf4AsModelAccessTarget(v *ModelAccessTargetOneOf4) ModelAccessTarget {
	return ModelAccessTarget{
		ModelAccessTargetOneOf4: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ModelAccessTarget) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ModelAccessTargetOneOf
	err = newStrictDecoder(data).Decode(&dst.ModelAccessTargetOneOf)
	if err == nil {
		jsonModelAccessTargetOneOf, _ := json.Marshal(dst.ModelAccessTargetOneOf)
		if string(jsonModelAccessTargetOneOf) == "{}" { // empty struct
			dst.ModelAccessTargetOneOf = nil
		} else {
			if err = validator.Validate(dst.ModelAccessTargetOneOf); err != nil {
				dst.ModelAccessTargetOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ModelAccessTargetOneOf = nil
	}

	// try to unmarshal data into ModelAccessTargetOneOf1
	err = newStrictDecoder(data).Decode(&dst.ModelAccessTargetOneOf1)
	if err == nil {
		jsonModelAccessTargetOneOf1, _ := json.Marshal(dst.ModelAccessTargetOneOf1)
		if string(jsonModelAccessTargetOneOf1) == "{}" { // empty struct
			dst.ModelAccessTargetOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ModelAccessTargetOneOf1); err != nil {
				dst.ModelAccessTargetOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ModelAccessTargetOneOf1 = nil
	}

	// try to unmarshal data into ModelAccessTargetOneOf2
	err = newStrictDecoder(data).Decode(&dst.ModelAccessTargetOneOf2)
	if err == nil {
		jsonModelAccessTargetOneOf2, _ := json.Marshal(dst.ModelAccessTargetOneOf2)
		if string(jsonModelAccessTargetOneOf2) == "{}" { // empty struct
			dst.ModelAccessTargetOneOf2 = nil
		} else {
			if err = validator.Validate(dst.ModelAccessTargetOneOf2); err != nil {
				dst.ModelAccessTargetOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ModelAccessTargetOneOf2 = nil
	}

	// try to unmarshal data into ModelAccessTargetOneOf3
	err = newStrictDecoder(data).Decode(&dst.ModelAccessTargetOneOf3)
	if err == nil {
		jsonModelAccessTargetOneOf3, _ := json.Marshal(dst.ModelAccessTargetOneOf3)
		if string(jsonModelAccessTargetOneOf3) == "{}" { // empty struct
			dst.ModelAccessTargetOneOf3 = nil
		} else {
			if err = validator.Validate(dst.ModelAccessTargetOneOf3); err != nil {
				dst.ModelAccessTargetOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ModelAccessTargetOneOf3 = nil
	}

	// try to unmarshal data into ModelAccessTargetOneOf4
	err = newStrictDecoder(data).Decode(&dst.ModelAccessTargetOneOf4)
	if err == nil {
		jsonModelAccessTargetOneOf4, _ := json.Marshal(dst.ModelAccessTargetOneOf4)
		if string(jsonModelAccessTargetOneOf4) == "{}" { // empty struct
			dst.ModelAccessTargetOneOf4 = nil
		} else {
			if err = validator.Validate(dst.ModelAccessTargetOneOf4); err != nil {
				dst.ModelAccessTargetOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ModelAccessTargetOneOf4 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ModelAccessTargetOneOf = nil
		dst.ModelAccessTargetOneOf1 = nil
		dst.ModelAccessTargetOneOf2 = nil
		dst.ModelAccessTargetOneOf3 = nil
		dst.ModelAccessTargetOneOf4 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ModelAccessTarget)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(ModelAccessTarget): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(ModelAccessTarget)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ModelAccessTarget) MarshalJSON() ([]byte, error) {
	if src.ModelAccessTargetOneOf != nil {
		return json.Marshal(&src.ModelAccessTargetOneOf)
	}

	if src.ModelAccessTargetOneOf1 != nil {
		return json.Marshal(&src.ModelAccessTargetOneOf1)
	}

	if src.ModelAccessTargetOneOf2 != nil {
		return json.Marshal(&src.ModelAccessTargetOneOf2)
	}

	if src.ModelAccessTargetOneOf3 != nil {
		return json.Marshal(&src.ModelAccessTargetOneOf3)
	}

	if src.ModelAccessTargetOneOf4 != nil {
		return json.Marshal(&src.ModelAccessTargetOneOf4)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ModelAccessTarget) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ModelAccessTargetOneOf != nil {
		return obj.ModelAccessTargetOneOf
	}

	if obj.ModelAccessTargetOneOf1 != nil {
		return obj.ModelAccessTargetOneOf1
	}

	if obj.ModelAccessTargetOneOf2 != nil {
		return obj.ModelAccessTargetOneOf2
	}

	if obj.ModelAccessTargetOneOf3 != nil {
		return obj.ModelAccessTargetOneOf3
	}

	if obj.ModelAccessTargetOneOf4 != nil {
		return obj.ModelAccessTargetOneOf4
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ModelAccessTarget) GetActualInstanceValue() (interface{}) {
	if obj.ModelAccessTargetOneOf != nil {
		return *obj.ModelAccessTargetOneOf
	}

	if obj.ModelAccessTargetOneOf1 != nil {
		return *obj.ModelAccessTargetOneOf1
	}

	if obj.ModelAccessTargetOneOf2 != nil {
		return *obj.ModelAccessTargetOneOf2
	}

	if obj.ModelAccessTargetOneOf3 != nil {
		return *obj.ModelAccessTargetOneOf3
	}

	if obj.ModelAccessTargetOneOf4 != nil {
		return *obj.ModelAccessTargetOneOf4
	}

	// all schemas are nil
	return nil
}

type NullableModelAccessTarget struct {
	value *ModelAccessTarget
	isSet bool
}

func (v NullableModelAccessTarget) Get() *ModelAccessTarget {
	return v.value
}

func (v *NullableModelAccessTarget) Set(val *ModelAccessTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAccessTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAccessTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAccessTarget(val *ModelAccessTarget) *NullableModelAccessTarget {
	return &NullableModelAccessTarget{value: val, isSet: true}
}

func (v NullableModelAccessTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAccessTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


