/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetApiKeyDisabledRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetApiKeyDisabledRequest{}

// SetApiKeyDisabledRequest struct for SetApiKeyDisabledRequest
type SetApiKeyDisabledRequest struct {
	Disabled bool `json:"disabled"`
}

type _SetApiKeyDisabledRequest SetApiKeyDisabledRequest

// NewSetApiKeyDisabledRequest instantiates a new SetApiKeyDisabledRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetApiKeyDisabledRequest(disabled bool) *SetApiKeyDisabledRequest {
	this := SetApiKeyDisabledRequest{}
	this.Disabled = disabled
	return &this
}

// NewSetApiKeyDisabledRequestWithDefaults instantiates a new SetApiKeyDisabledRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetApiKeyDisabledRequestWithDefaults() *SetApiKeyDisabledRequest {
	this := SetApiKeyDisabledRequest{}
	return &this
}

// GetDisabled returns the Disabled field value
func (o *SetApiKeyDisabledRequest) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *SetApiKeyDisabledRequest) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *SetApiKeyDisabledRequest) SetDisabled(v bool) {
	o.Disabled = v
}

func (o SetApiKeyDisabledRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetApiKeyDisabledRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["disabled"] = o.Disabled
	return toSerialize, nil
}

func (o *SetApiKeyDisabledRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"disabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetApiKeyDisabledRequest := _SetApiKeyDisabledRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetApiKeyDisabledRequest)

	if err != nil {
		return err
	}

	*o = SetApiKeyDisabledRequest(varSetApiKeyDisabledRequest)

	return err
}

type NullableSetApiKeyDisabledRequest struct {
	value *SetApiKeyDisabledRequest
	isSet bool
}

func (v NullableSetApiKeyDisabledRequest) Get() *SetApiKeyDisabledRequest {
	return v.value
}

func (v *NullableSetApiKeyDisabledRequest) Set(val *SetApiKeyDisabledRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetApiKeyDisabledRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetApiKeyDisabledRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetApiKeyDisabledRequest(val *SetApiKeyDisabledRequest) *NullableSetApiKeyDisabledRequest {
	return &NullableSetApiKeyDisabledRequest{value: val, isSet: true}
}

func (v NullableSetApiKeyDisabledRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetApiKeyDisabledRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


