/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ApiKeyKind What category of credential a row is (BCP-3510) — the first-class answer to \"is this an ephemeral governed agent-session key?\", which the service used to get by pattern-matching [`AGENT_SESSION_SCOPE`] inside `scopes`.  Distinct from [`ActorKind`], which answers a different question. `kind` is about **lifecycle**: who may list it, who may revoke it, and whether the reaper may delete it. `ActorKind` is about **attribution**: whose name goes on an event. That is why `Machine` here covers both the pure service key and the IdP-group-bound key that `ActorKind` keeps apart — the two are listed, revoked and reaped identically, and only the audit trail cares which is which.
type ApiKeyKind string

// List of ApiKeyKind
const (
	APIKEYKIND_USER ApiKeyKind = "user"
	APIKEYKIND_MACHINE ApiKeyKind = "machine"
	APIKEYKIND_AGENT_SESSION ApiKeyKind = "agent_session"
)

// All allowed values of ApiKeyKind enum
var AllowedApiKeyKindEnumValues = []ApiKeyKind{
	"user",
	"machine",
	"agent_session",
}

func (v *ApiKeyKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ApiKeyKind(value)
	for _, existing := range AllowedApiKeyKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ApiKeyKind", value)
}

// NewApiKeyKindFromValue returns a pointer to a valid ApiKeyKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewApiKeyKindFromValue(v string) (*ApiKeyKind, error) {
	ev := ApiKeyKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ApiKeyKind: valid values are %v", v, AllowedApiKeyKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ApiKeyKind) IsValid() bool {
	for _, existing := range AllowedApiKeyKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ApiKeyKind value
func (v ApiKeyKind) Ptr() *ApiKeyKind {
	return &v
}

type NullableApiKeyKind struct {
	value *ApiKeyKind
	isSet bool
}

func (v NullableApiKeyKind) Get() *ApiKeyKind {
	return v.value
}

func (v *NullableApiKeyKind) Set(val *ApiKeyKind) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyKind) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyKind(val *ApiKeyKind) *NullableApiKeyKind {
	return &NullableApiKeyKind{value: val, isSet: true}
}

func (v NullableApiKeyKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

