/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AWSTrustInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AWSTrustInfoResponse{}

// AWSTrustInfoResponse struct for AWSTrustInfoResponse
type AWSTrustInfoResponse struct {
	ExternalId string `json:"external_id"`
	PrincipalArn string `json:"principal_arn"`
}

type _AWSTrustInfoResponse AWSTrustInfoResponse

// NewAWSTrustInfoResponse instantiates a new AWSTrustInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSTrustInfoResponse(externalId string, principalArn string) *AWSTrustInfoResponse {
	this := AWSTrustInfoResponse{}
	this.ExternalId = externalId
	this.PrincipalArn = principalArn
	return &this
}

// NewAWSTrustInfoResponseWithDefaults instantiates a new AWSTrustInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSTrustInfoResponseWithDefaults() *AWSTrustInfoResponse {
	this := AWSTrustInfoResponse{}
	return &this
}

// GetExternalId returns the ExternalId field value
func (o *AWSTrustInfoResponse) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *AWSTrustInfoResponse) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *AWSTrustInfoResponse) SetExternalId(v string) {
	o.ExternalId = v
}

// GetPrincipalArn returns the PrincipalArn field value
func (o *AWSTrustInfoResponse) GetPrincipalArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalArn
}

// GetPrincipalArnOk returns a tuple with the PrincipalArn field value
// and a boolean to check if the value has been set.
func (o *AWSTrustInfoResponse) GetPrincipalArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalArn, true
}

// SetPrincipalArn sets field value
func (o *AWSTrustInfoResponse) SetPrincipalArn(v string) {
	o.PrincipalArn = v
}

func (o AWSTrustInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AWSTrustInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["external_id"] = o.ExternalId
	toSerialize["principal_arn"] = o.PrincipalArn
	return toSerialize, nil
}

func (o *AWSTrustInfoResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"external_id",
		"principal_arn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAWSTrustInfoResponse := _AWSTrustInfoResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAWSTrustInfoResponse)

	if err != nil {
		return err
	}

	*o = AWSTrustInfoResponse(varAWSTrustInfoResponse)

	return err
}

type NullableAWSTrustInfoResponse struct {
	value *AWSTrustInfoResponse
	isSet bool
}

func (v NullableAWSTrustInfoResponse) Get() *AWSTrustInfoResponse {
	return v.value
}

func (v *NullableAWSTrustInfoResponse) Set(val *AWSTrustInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSTrustInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSTrustInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSTrustInfoResponse(val *AWSTrustInfoResponse) *NullableAWSTrustInfoResponse {
	return &NullableAWSTrustInfoResponse{value: val, isSet: true}
}

func (v NullableAWSTrustInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSTrustInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


