/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExportsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportsResponse{}

// ExportsResponse struct for ExportsResponse
type ExportsResponse struct {
	Exports []ExportResponse `json:"exports"`
}

type _ExportsResponse ExportsResponse

// NewExportsResponse instantiates a new ExportsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportsResponse(exports []ExportResponse) *ExportsResponse {
	this := ExportsResponse{}
	this.Exports = exports
	return &this
}

// NewExportsResponseWithDefaults instantiates a new ExportsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportsResponseWithDefaults() *ExportsResponse {
	this := ExportsResponse{}
	return &this
}

// GetExports returns the Exports field value
// If the value is explicit nil, the zero value for []ExportResponse will be returned
func (o *ExportsResponse) GetExports() []ExportResponse {
	if o == nil {
		var ret []ExportResponse
		return ret
	}

	return o.Exports
}

// GetExportsOk returns a tuple with the Exports field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExportsResponse) GetExportsOk() ([]ExportResponse, bool) {
	if o == nil || IsNil(o.Exports) {
		return nil, false
	}
	return o.Exports, true
}

// SetExports sets field value
func (o *ExportsResponse) SetExports(v []ExportResponse) {
	o.Exports = v
}

func (o ExportsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Exports != nil {
		toSerialize["exports"] = o.Exports
	}
	return toSerialize, nil
}

func (o *ExportsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"exports",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExportsResponse := _ExportsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExportsResponse)

	if err != nil {
		return err
	}

	*o = ExportsResponse(varExportsResponse)

	return err
}

type NullableExportsResponse struct {
	value *ExportsResponse
	isSet bool
}

func (v NullableExportsResponse) Get() *ExportsResponse {
	return v.value
}

func (v *NullableExportsResponse) Set(val *ExportsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExportsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExportsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportsResponse(val *ExportsResponse) *NullableExportsResponse {
	return &NullableExportsResponse{value: val, isSet: true}
}

func (v NullableExportsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


