/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"github.com/barndoor-ai/barndoor-go-sdk/v2/bdtime"
	"bytes"
	"fmt"
)

// checks if the ModelMappingWithBudgetStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelMappingWithBudgetStatus{}

// ModelMappingWithBudgetStatus Wraps a [`ModelMapping`] with the BCP-2813 `budget_status` annotation so the admin Model Mappings page can render a \"disabled by budget\" pill. The inner `ModelMapping` fields are flattened so the response is a drop-in superset of the legacy `Vec<ModelMapping>` shape — older clients that ignore `budget_status` keep working unchanged.
type ModelMappingWithBudgetStatus struct {
	// Cooldown on a 429 with no usable `Retry-After`, seconds.
	Cooldown429DefaultSecs int32 `json:"cooldown_429_default_secs"`
	// First cooldown window, doubled on each failed recovery probe up to `cooldown_max_secs`.
	CooldownBaseSecs int32 `json:"cooldown_base_secs"`
	// Gateway failures within `cooldown_window_secs` that cool the route. `0` disables every cooldown of the shared route.
	CooldownFailureThreshold int32 `json:"cooldown_failure_threshold"`
	// Cap on every cooldown window.
	CooldownMaxSecs int32 `json:"cooldown_max_secs"`
	// Flat cooldown on a 529 \"overloaded\" with no usable `Retry-After`, seconds. `0` counts a 529 as an ordinary gateway failure instead.
	CooldownOverloadedSecs int32 `json:"cooldown_overloaded_secs"`
	// Width of the rolling failure window, seconds.
	CooldownWindowSecs int32 `json:"cooldown_window_secs"`
	CreatedByEmail *string `json:"created_by_email,omitempty"`
	CreatedByName *string `json:"created_by_name,omitempty"`
	CreatedByUserId *string `json:"created_by_user_id,omitempty"`
	// Optional free text explaining *why* the last change was made (\"Raised for the Q3 batch job\", \"Vendor deprecated the old endpoint\").  Admin-authored and rendered in the portal, so it is untrusted input: length-capped here, escaped on render.
	LastChangeNote *string `json:"last_change_note,omitempty"`
	// When the change named by `last_modified_by_*` happened.  Its own column rather than the row's `updated_at`, because `updated_at` is bumped by writes nobody is attributed for -- pairing the two would date a named admin's edit to a background job's clock. See the V75 migration for the full reasoning.
	LastModifiedAt *bdtime.Time `json:"last_modified_at,omitempty"`
	LastModifiedByEmail *string `json:"last_modified_by_email,omitempty"`
	LastModifiedByName *string `json:"last_modified_by_name,omitempty"`
	LastModifiedByUserId *string `json:"last_modified_by_user_id,omitempty"`
	// Set when the *gateway* turned this row off (BCP-3811's `full` sync retiring a model the catalog dropped). `None` means a human decided the `enabled` flag, and the reconciler will not touch it in either direction — see migration V63. Any admin write to `enabled` clears this.  Clearing it is *not* a durable claim on the row, and it is easy to read it that way. It protects a human's **disable** — the re-enable branch requires the marker to be present, so a row a human turned off is never turned back on. It cannot protect a human's **re-enable**: a cleared marker is exactly what makes the row eligible for retirement again, so under `full` a model the catalog still does not list is re-disabled on the next tick. That is `full`'s contract (\"enabled set tracks the catalog\"), not a bug — see `model_sync::tests::re_enabling_a_dropped_model_is_retired_again_on_the_next_tick`.
	AutoDisabledReason *AutoDisabledReason `json:"auto_disabled_reason,omitempty"`
	// When `true` the row participates in bare-name resolution (`POST /v1/chat/completions {\"model\": \"<alias>\"}`). When `false` the row is enablement-only — addressable solely via the explicit `<provider>/<upstream>` form. Custom-alias rows (`model_alias != upstream_model`) are always `true`; 1:1 rows default to `false` and admins opt in by creating an explicit Route on the Model Routes tab.
	BareAlias bool `json:"bare_alias"`
	Enabled bool `json:"enabled"`
	Id string `json:"id"`
	ModelAlias string `json:"model_alias"`
	Priority int32 `json:"priority"`
	ProviderId string `json:"provider_id"`
	// Per-mapping (route-tier / model-tier) total-request timeout for non-streaming requests (streaming responses have no total timeout). Defaults to `TOTAL_REQUEST_TIMEOUT_DEFAULT_SECS` at insert. On a custom-alias row this is the *route* tier; on the 1:1 enablement (anchor) row it is the *model* tier consulted by the resolver for every alias of that model. The range is fixed platform policy (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`), enforced by the column CHECK.
	RequestTimeoutSecs *int32 `json:"request_timeout_secs,omitempty"`
	// Same-route retries on upstream 429. 0 means immediate failover.
	RetryOn429Count int32 `json:"retry_on_429_count"`
	// Cap on honoring upstream `Retry-After` header. 0 means use a small built-in default and ignore the header value.
	RetryOn429MaxWaitSecs int32 `json:"retry_on_429_max_wait_secs"`
	// Whether the model was picked from the provider catalog or typed in by an admin. Stamped once at create time and never recomputed — see [`ModelSource`] and migration V61.
	Source ModelSource `json:"source"`
	// Per-mapping stream-idle (per-chunk) timeout for streaming responses. Defaults to `STREAM_IDLE_TIMEOUT_DEFAULT_SECS` at insert; enforced via `tokio::time::timeout` around each upstream SSE/eventstream chunk read. The range is fixed platform policy (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`), enforced by the column CHECK.
	StreamIdleTimeoutSecs *int32 `json:"stream_idle_timeout_secs,omitempty"`
	UpstreamModel string `json:"upstream_model"`
	// Populated when a `LlmProvider` / `Model` / `ModelAlias` budget with `action_on_exhaust = block` is currently exhausted for the mapping's `(provider_id, upstream_model, model_alias)` triple. Runtime would drop this route from the resolved plan; the pill surfaces the same state without filtering the row out of the listing.
	BudgetStatus NullableBudgetTargetStatus `json:"budget_status,omitempty"`
	// The rate a request against this mapping would be billed at, resolved through the same tier chain the cost calculator uses (BCP-3564). Always present; `source == \"none\"` means unpriced. See [`crate::effective_pricing`].
	EffectivePricing EffectivePricing `json:"effective_pricing"`
	// Populated when the mapping's `(provider_id, upstream_model)` route is in a passive-health cooldown. The page renders a \"temporarily unavailable\" pill; the row stays in the listing.
	RouteHealthStatus NullableRouteHealthStatus `json:"route_health_status,omitempty"`
	// Populated when the model is enabled from a provider catalog that no longer lists it (BCP-3812). Advisory: nothing is disabled on the strength of it — retirement is BCP-3811's `full` mode, which the org opts into. See [`crate::catalog_status`].
	StaleStatus NullableModelStaleStatus `json:"stale_status,omitempty"`
}

type _ModelMappingWithBudgetStatus ModelMappingWithBudgetStatus

// NewModelMappingWithBudgetStatus instantiates a new ModelMappingWithBudgetStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelMappingWithBudgetStatus(cooldown429DefaultSecs int32, cooldownBaseSecs int32, cooldownFailureThreshold int32, cooldownMaxSecs int32, cooldownOverloadedSecs int32, cooldownWindowSecs int32, bareAlias bool, enabled bool, id string, modelAlias string, priority int32, providerId string, retryOn429Count int32, retryOn429MaxWaitSecs int32, source ModelSource, upstreamModel string, effectivePricing EffectivePricing) *ModelMappingWithBudgetStatus {
	this := ModelMappingWithBudgetStatus{}
	this.Cooldown429DefaultSecs = cooldown429DefaultSecs
	this.CooldownBaseSecs = cooldownBaseSecs
	this.CooldownFailureThreshold = cooldownFailureThreshold
	this.CooldownMaxSecs = cooldownMaxSecs
	this.CooldownOverloadedSecs = cooldownOverloadedSecs
	this.CooldownWindowSecs = cooldownWindowSecs
	this.BareAlias = bareAlias
	this.Enabled = enabled
	this.Id = id
	this.ModelAlias = modelAlias
	this.Priority = priority
	this.ProviderId = providerId
	this.RetryOn429Count = retryOn429Count
	this.RetryOn429MaxWaitSecs = retryOn429MaxWaitSecs
	this.Source = source
	this.UpstreamModel = upstreamModel
	this.EffectivePricing = effectivePricing
	return &this
}

// NewModelMappingWithBudgetStatusWithDefaults instantiates a new ModelMappingWithBudgetStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelMappingWithBudgetStatusWithDefaults() *ModelMappingWithBudgetStatus {
	this := ModelMappingWithBudgetStatus{}
	return &this
}

// GetCooldown429DefaultSecs returns the Cooldown429DefaultSecs field value
func (o *ModelMappingWithBudgetStatus) GetCooldown429DefaultSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Cooldown429DefaultSecs
}

// GetCooldown429DefaultSecsOk returns a tuple with the Cooldown429DefaultSecs field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCooldown429DefaultSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cooldown429DefaultSecs, true
}

// SetCooldown429DefaultSecs sets field value
func (o *ModelMappingWithBudgetStatus) SetCooldown429DefaultSecs(v int32) {
	o.Cooldown429DefaultSecs = v
}

// GetCooldownBaseSecs returns the CooldownBaseSecs field value
func (o *ModelMappingWithBudgetStatus) GetCooldownBaseSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CooldownBaseSecs
}

// GetCooldownBaseSecsOk returns a tuple with the CooldownBaseSecs field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCooldownBaseSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CooldownBaseSecs, true
}

// SetCooldownBaseSecs sets field value
func (o *ModelMappingWithBudgetStatus) SetCooldownBaseSecs(v int32) {
	o.CooldownBaseSecs = v
}

// GetCooldownFailureThreshold returns the CooldownFailureThreshold field value
func (o *ModelMappingWithBudgetStatus) GetCooldownFailureThreshold() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CooldownFailureThreshold
}

// GetCooldownFailureThresholdOk returns a tuple with the CooldownFailureThreshold field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCooldownFailureThresholdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CooldownFailureThreshold, true
}

// SetCooldownFailureThreshold sets field value
func (o *ModelMappingWithBudgetStatus) SetCooldownFailureThreshold(v int32) {
	o.CooldownFailureThreshold = v
}

// GetCooldownMaxSecs returns the CooldownMaxSecs field value
func (o *ModelMappingWithBudgetStatus) GetCooldownMaxSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CooldownMaxSecs
}

// GetCooldownMaxSecsOk returns a tuple with the CooldownMaxSecs field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCooldownMaxSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CooldownMaxSecs, true
}

// SetCooldownMaxSecs sets field value
func (o *ModelMappingWithBudgetStatus) SetCooldownMaxSecs(v int32) {
	o.CooldownMaxSecs = v
}

// GetCooldownOverloadedSecs returns the CooldownOverloadedSecs field value
func (o *ModelMappingWithBudgetStatus) GetCooldownOverloadedSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CooldownOverloadedSecs
}

// GetCooldownOverloadedSecsOk returns a tuple with the CooldownOverloadedSecs field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCooldownOverloadedSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CooldownOverloadedSecs, true
}

// SetCooldownOverloadedSecs sets field value
func (o *ModelMappingWithBudgetStatus) SetCooldownOverloadedSecs(v int32) {
	o.CooldownOverloadedSecs = v
}

// GetCooldownWindowSecs returns the CooldownWindowSecs field value
func (o *ModelMappingWithBudgetStatus) GetCooldownWindowSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CooldownWindowSecs
}

// GetCooldownWindowSecsOk returns a tuple with the CooldownWindowSecs field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCooldownWindowSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CooldownWindowSecs, true
}

// SetCooldownWindowSecs sets field value
func (o *ModelMappingWithBudgetStatus) SetCooldownWindowSecs(v int32) {
	o.CooldownWindowSecs = v
}

// GetCreatedByEmail returns the CreatedByEmail field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetCreatedByEmail() string {
	if o == nil || IsNil(o.CreatedByEmail) {
		var ret string
		return ret
	}
	return *o.CreatedByEmail
}

// GetCreatedByEmailOk returns a tuple with the CreatedByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCreatedByEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByEmail) {
		return nil, false
	}
	return o.CreatedByEmail, true
}

// HasCreatedByEmail returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasCreatedByEmail() bool {
	if o != nil && !IsNil(o.CreatedByEmail) {
		return true
	}

	return false
}

// SetCreatedByEmail gets a reference to the given string and assigns it to the CreatedByEmail field.
func (o *ModelMappingWithBudgetStatus) SetCreatedByEmail(v string) {
	o.CreatedByEmail = &v
}

// GetCreatedByName returns the CreatedByName field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetCreatedByName() string {
	if o == nil || IsNil(o.CreatedByName) {
		var ret string
		return ret
	}
	return *o.CreatedByName
}

// GetCreatedByNameOk returns a tuple with the CreatedByName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCreatedByNameOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByName) {
		return nil, false
	}
	return o.CreatedByName, true
}

// HasCreatedByName returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasCreatedByName() bool {
	if o != nil && !IsNil(o.CreatedByName) {
		return true
	}

	return false
}

// SetCreatedByName gets a reference to the given string and assigns it to the CreatedByName field.
func (o *ModelMappingWithBudgetStatus) SetCreatedByName(v string) {
	o.CreatedByName = &v
}

// GetCreatedByUserId returns the CreatedByUserId field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetCreatedByUserId() string {
	if o == nil || IsNil(o.CreatedByUserId) {
		var ret string
		return ret
	}
	return *o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetCreatedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByUserId) {
		return nil, false
	}
	return o.CreatedByUserId, true
}

// HasCreatedByUserId returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasCreatedByUserId() bool {
	if o != nil && !IsNil(o.CreatedByUserId) {
		return true
	}

	return false
}

// SetCreatedByUserId gets a reference to the given string and assigns it to the CreatedByUserId field.
func (o *ModelMappingWithBudgetStatus) SetCreatedByUserId(v string) {
	o.CreatedByUserId = &v
}

// GetLastChangeNote returns the LastChangeNote field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetLastChangeNote() string {
	if o == nil || IsNil(o.LastChangeNote) {
		var ret string
		return ret
	}
	return *o.LastChangeNote
}

// GetLastChangeNoteOk returns a tuple with the LastChangeNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetLastChangeNoteOk() (*string, bool) {
	if o == nil || IsNil(o.LastChangeNote) {
		return nil, false
	}
	return o.LastChangeNote, true
}

// HasLastChangeNote returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasLastChangeNote() bool {
	if o != nil && !IsNil(o.LastChangeNote) {
		return true
	}

	return false
}

// SetLastChangeNote gets a reference to the given string and assigns it to the LastChangeNote field.
func (o *ModelMappingWithBudgetStatus) SetLastChangeNote(v string) {
	o.LastChangeNote = &v
}

// GetLastModifiedAt returns the LastModifiedAt field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedAt() bdtime.Time {
	if o == nil || IsNil(o.LastModifiedAt) {
		var ret bdtime.Time
		return ret
	}
	return *o.LastModifiedAt
}

// GetLastModifiedAtOk returns a tuple with the LastModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedAtOk() (*bdtime.Time, bool) {
	if o == nil || IsNil(o.LastModifiedAt) {
		return nil, false
	}
	return o.LastModifiedAt, true
}

// HasLastModifiedAt returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasLastModifiedAt() bool {
	if o != nil && !IsNil(o.LastModifiedAt) {
		return true
	}

	return false
}

// SetLastModifiedAt gets a reference to the given bdtime.Time and assigns it to the LastModifiedAt field.
func (o *ModelMappingWithBudgetStatus) SetLastModifiedAt(v bdtime.Time) {
	o.LastModifiedAt = &v
}

// GetLastModifiedByEmail returns the LastModifiedByEmail field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedByEmail() string {
	if o == nil || IsNil(o.LastModifiedByEmail) {
		var ret string
		return ret
	}
	return *o.LastModifiedByEmail
}

// GetLastModifiedByEmailOk returns a tuple with the LastModifiedByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedByEmailOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedByEmail) {
		return nil, false
	}
	return o.LastModifiedByEmail, true
}

// HasLastModifiedByEmail returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasLastModifiedByEmail() bool {
	if o != nil && !IsNil(o.LastModifiedByEmail) {
		return true
	}

	return false
}

// SetLastModifiedByEmail gets a reference to the given string and assigns it to the LastModifiedByEmail field.
func (o *ModelMappingWithBudgetStatus) SetLastModifiedByEmail(v string) {
	o.LastModifiedByEmail = &v
}

// GetLastModifiedByName returns the LastModifiedByName field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedByName() string {
	if o == nil || IsNil(o.LastModifiedByName) {
		var ret string
		return ret
	}
	return *o.LastModifiedByName
}

// GetLastModifiedByNameOk returns a tuple with the LastModifiedByName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedByNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedByName) {
		return nil, false
	}
	return o.LastModifiedByName, true
}

// HasLastModifiedByName returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasLastModifiedByName() bool {
	if o != nil && !IsNil(o.LastModifiedByName) {
		return true
	}

	return false
}

// SetLastModifiedByName gets a reference to the given string and assigns it to the LastModifiedByName field.
func (o *ModelMappingWithBudgetStatus) SetLastModifiedByName(v string) {
	o.LastModifiedByName = &v
}

// GetLastModifiedByUserId returns the LastModifiedByUserId field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedByUserId() string {
	if o == nil || IsNil(o.LastModifiedByUserId) {
		var ret string
		return ret
	}
	return *o.LastModifiedByUserId
}

// GetLastModifiedByUserIdOk returns a tuple with the LastModifiedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetLastModifiedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.LastModifiedByUserId) {
		return nil, false
	}
	return o.LastModifiedByUserId, true
}

// HasLastModifiedByUserId returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasLastModifiedByUserId() bool {
	if o != nil && !IsNil(o.LastModifiedByUserId) {
		return true
	}

	return false
}

// SetLastModifiedByUserId gets a reference to the given string and assigns it to the LastModifiedByUserId field.
func (o *ModelMappingWithBudgetStatus) SetLastModifiedByUserId(v string) {
	o.LastModifiedByUserId = &v
}

// GetAutoDisabledReason returns the AutoDisabledReason field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetAutoDisabledReason() AutoDisabledReason {
	if o == nil || IsNil(o.AutoDisabledReason) {
		var ret AutoDisabledReason
		return ret
	}
	return *o.AutoDisabledReason
}

// GetAutoDisabledReasonOk returns a tuple with the AutoDisabledReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetAutoDisabledReasonOk() (*AutoDisabledReason, bool) {
	if o == nil || IsNil(o.AutoDisabledReason) {
		return nil, false
	}
	return o.AutoDisabledReason, true
}

// HasAutoDisabledReason returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasAutoDisabledReason() bool {
	if o != nil && !IsNil(o.AutoDisabledReason) {
		return true
	}

	return false
}

// SetAutoDisabledReason gets a reference to the given AutoDisabledReason and assigns it to the AutoDisabledReason field.
func (o *ModelMappingWithBudgetStatus) SetAutoDisabledReason(v AutoDisabledReason) {
	o.AutoDisabledReason = &v
}

// GetBareAlias returns the BareAlias field value
func (o *ModelMappingWithBudgetStatus) GetBareAlias() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BareAlias
}

// GetBareAliasOk returns a tuple with the BareAlias field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetBareAliasOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BareAlias, true
}

// SetBareAlias sets field value
func (o *ModelMappingWithBudgetStatus) SetBareAlias(v bool) {
	o.BareAlias = v
}

// GetEnabled returns the Enabled field value
func (o *ModelMappingWithBudgetStatus) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ModelMappingWithBudgetStatus) SetEnabled(v bool) {
	o.Enabled = v
}

// GetId returns the Id field value
func (o *ModelMappingWithBudgetStatus) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ModelMappingWithBudgetStatus) SetId(v string) {
	o.Id = v
}

// GetModelAlias returns the ModelAlias field value
func (o *ModelMappingWithBudgetStatus) GetModelAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelAlias
}

// GetModelAliasOk returns a tuple with the ModelAlias field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetModelAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelAlias, true
}

// SetModelAlias sets field value
func (o *ModelMappingWithBudgetStatus) SetModelAlias(v string) {
	o.ModelAlias = v
}

// GetPriority returns the Priority field value
func (o *ModelMappingWithBudgetStatus) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *ModelMappingWithBudgetStatus) SetPriority(v int32) {
	o.Priority = v
}

// GetProviderId returns the ProviderId field value
func (o *ModelMappingWithBudgetStatus) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *ModelMappingWithBudgetStatus) SetProviderId(v string) {
	o.ProviderId = v
}

// GetRequestTimeoutSecs returns the RequestTimeoutSecs field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetRequestTimeoutSecs() int32 {
	if o == nil || IsNil(o.RequestTimeoutSecs) {
		var ret int32
		return ret
	}
	return *o.RequestTimeoutSecs
}

// GetRequestTimeoutSecsOk returns a tuple with the RequestTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetRequestTimeoutSecsOk() (*int32, bool) {
	if o == nil || IsNil(o.RequestTimeoutSecs) {
		return nil, false
	}
	return o.RequestTimeoutSecs, true
}

// HasRequestTimeoutSecs returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasRequestTimeoutSecs() bool {
	if o != nil && !IsNil(o.RequestTimeoutSecs) {
		return true
	}

	return false
}

// SetRequestTimeoutSecs gets a reference to the given int32 and assigns it to the RequestTimeoutSecs field.
func (o *ModelMappingWithBudgetStatus) SetRequestTimeoutSecs(v int32) {
	o.RequestTimeoutSecs = &v
}

// GetRetryOn429Count returns the RetryOn429Count field value
func (o *ModelMappingWithBudgetStatus) GetRetryOn429Count() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetryOn429Count
}

// GetRetryOn429CountOk returns a tuple with the RetryOn429Count field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetRetryOn429CountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryOn429Count, true
}

// SetRetryOn429Count sets field value
func (o *ModelMappingWithBudgetStatus) SetRetryOn429Count(v int32) {
	o.RetryOn429Count = v
}

// GetRetryOn429MaxWaitSecs returns the RetryOn429MaxWaitSecs field value
func (o *ModelMappingWithBudgetStatus) GetRetryOn429MaxWaitSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetryOn429MaxWaitSecs
}

// GetRetryOn429MaxWaitSecsOk returns a tuple with the RetryOn429MaxWaitSecs field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetRetryOn429MaxWaitSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryOn429MaxWaitSecs, true
}

// SetRetryOn429MaxWaitSecs sets field value
func (o *ModelMappingWithBudgetStatus) SetRetryOn429MaxWaitSecs(v int32) {
	o.RetryOn429MaxWaitSecs = v
}

// GetSource returns the Source field value
func (o *ModelMappingWithBudgetStatus) GetSource() ModelSource {
	if o == nil {
		var ret ModelSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetSourceOk() (*ModelSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ModelMappingWithBudgetStatus) SetSource(v ModelSource) {
	o.Source = v
}

// GetStreamIdleTimeoutSecs returns the StreamIdleTimeoutSecs field value if set, zero value otherwise.
func (o *ModelMappingWithBudgetStatus) GetStreamIdleTimeoutSecs() int32 {
	if o == nil || IsNil(o.StreamIdleTimeoutSecs) {
		var ret int32
		return ret
	}
	return *o.StreamIdleTimeoutSecs
}

// GetStreamIdleTimeoutSecsOk returns a tuple with the StreamIdleTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetStreamIdleTimeoutSecsOk() (*int32, bool) {
	if o == nil || IsNil(o.StreamIdleTimeoutSecs) {
		return nil, false
	}
	return o.StreamIdleTimeoutSecs, true
}

// HasStreamIdleTimeoutSecs returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasStreamIdleTimeoutSecs() bool {
	if o != nil && !IsNil(o.StreamIdleTimeoutSecs) {
		return true
	}

	return false
}

// SetStreamIdleTimeoutSecs gets a reference to the given int32 and assigns it to the StreamIdleTimeoutSecs field.
func (o *ModelMappingWithBudgetStatus) SetStreamIdleTimeoutSecs(v int32) {
	o.StreamIdleTimeoutSecs = &v
}

// GetUpstreamModel returns the UpstreamModel field value
func (o *ModelMappingWithBudgetStatus) GetUpstreamModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpstreamModel
}

// GetUpstreamModelOk returns a tuple with the UpstreamModel field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetUpstreamModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpstreamModel, true
}

// SetUpstreamModel sets field value
func (o *ModelMappingWithBudgetStatus) SetUpstreamModel(v string) {
	o.UpstreamModel = v
}

// GetBudgetStatus returns the BudgetStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelMappingWithBudgetStatus) GetBudgetStatus() BudgetTargetStatus {
	if o == nil || IsNil(o.BudgetStatus.Get()) {
		var ret BudgetTargetStatus
		return ret
	}
	return *o.BudgetStatus.Get()
}

// GetBudgetStatusOk returns a tuple with the BudgetStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelMappingWithBudgetStatus) GetBudgetStatusOk() (*BudgetTargetStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.BudgetStatus.Get(), o.BudgetStatus.IsSet()
}

// HasBudgetStatus returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasBudgetStatus() bool {
	if o != nil && o.BudgetStatus.IsSet() {
		return true
	}

	return false
}

// SetBudgetStatus gets a reference to the given NullableBudgetTargetStatus and assigns it to the BudgetStatus field.
func (o *ModelMappingWithBudgetStatus) SetBudgetStatus(v BudgetTargetStatus) {
	o.BudgetStatus.Set(&v)
}
// SetBudgetStatusNil sets the value for BudgetStatus to be an explicit nil
func (o *ModelMappingWithBudgetStatus) SetBudgetStatusNil() {
	o.BudgetStatus.Set(nil)
}

// UnsetBudgetStatus ensures that no value is present for BudgetStatus, not even an explicit nil
func (o *ModelMappingWithBudgetStatus) UnsetBudgetStatus() {
	o.BudgetStatus.Unset()
}

// GetEffectivePricing returns the EffectivePricing field value
func (o *ModelMappingWithBudgetStatus) GetEffectivePricing() EffectivePricing {
	if o == nil {
		var ret EffectivePricing
		return ret
	}

	return o.EffectivePricing
}

// GetEffectivePricingOk returns a tuple with the EffectivePricing field value
// and a boolean to check if the value has been set.
func (o *ModelMappingWithBudgetStatus) GetEffectivePricingOk() (*EffectivePricing, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectivePricing, true
}

// SetEffectivePricing sets field value
func (o *ModelMappingWithBudgetStatus) SetEffectivePricing(v EffectivePricing) {
	o.EffectivePricing = v
}

// GetRouteHealthStatus returns the RouteHealthStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelMappingWithBudgetStatus) GetRouteHealthStatus() RouteHealthStatus {
	if o == nil || IsNil(o.RouteHealthStatus.Get()) {
		var ret RouteHealthStatus
		return ret
	}
	return *o.RouteHealthStatus.Get()
}

// GetRouteHealthStatusOk returns a tuple with the RouteHealthStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelMappingWithBudgetStatus) GetRouteHealthStatusOk() (*RouteHealthStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteHealthStatus.Get(), o.RouteHealthStatus.IsSet()
}

// HasRouteHealthStatus returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasRouteHealthStatus() bool {
	if o != nil && o.RouteHealthStatus.IsSet() {
		return true
	}

	return false
}

// SetRouteHealthStatus gets a reference to the given NullableRouteHealthStatus and assigns it to the RouteHealthStatus field.
func (o *ModelMappingWithBudgetStatus) SetRouteHealthStatus(v RouteHealthStatus) {
	o.RouteHealthStatus.Set(&v)
}
// SetRouteHealthStatusNil sets the value for RouteHealthStatus to be an explicit nil
func (o *ModelMappingWithBudgetStatus) SetRouteHealthStatusNil() {
	o.RouteHealthStatus.Set(nil)
}

// UnsetRouteHealthStatus ensures that no value is present for RouteHealthStatus, not even an explicit nil
func (o *ModelMappingWithBudgetStatus) UnsetRouteHealthStatus() {
	o.RouteHealthStatus.Unset()
}

// GetStaleStatus returns the StaleStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelMappingWithBudgetStatus) GetStaleStatus() ModelStaleStatus {
	if o == nil || IsNil(o.StaleStatus.Get()) {
		var ret ModelStaleStatus
		return ret
	}
	return *o.StaleStatus.Get()
}

// GetStaleStatusOk returns a tuple with the StaleStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelMappingWithBudgetStatus) GetStaleStatusOk() (*ModelStaleStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.StaleStatus.Get(), o.StaleStatus.IsSet()
}

// HasStaleStatus returns a boolean if a field has been set.
func (o *ModelMappingWithBudgetStatus) HasStaleStatus() bool {
	if o != nil && o.StaleStatus.IsSet() {
		return true
	}

	return false
}

// SetStaleStatus gets a reference to the given NullableModelStaleStatus and assigns it to the StaleStatus field.
func (o *ModelMappingWithBudgetStatus) SetStaleStatus(v ModelStaleStatus) {
	o.StaleStatus.Set(&v)
}
// SetStaleStatusNil sets the value for StaleStatus to be an explicit nil
func (o *ModelMappingWithBudgetStatus) SetStaleStatusNil() {
	o.StaleStatus.Set(nil)
}

// UnsetStaleStatus ensures that no value is present for StaleStatus, not even an explicit nil
func (o *ModelMappingWithBudgetStatus) UnsetStaleStatus() {
	o.StaleStatus.Unset()
}

func (o ModelMappingWithBudgetStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelMappingWithBudgetStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cooldown_429_default_secs"] = o.Cooldown429DefaultSecs
	toSerialize["cooldown_base_secs"] = o.CooldownBaseSecs
	toSerialize["cooldown_failure_threshold"] = o.CooldownFailureThreshold
	toSerialize["cooldown_max_secs"] = o.CooldownMaxSecs
	toSerialize["cooldown_overloaded_secs"] = o.CooldownOverloadedSecs
	toSerialize["cooldown_window_secs"] = o.CooldownWindowSecs
	if !IsNil(o.CreatedByEmail) {
		toSerialize["created_by_email"] = o.CreatedByEmail
	}
	if !IsNil(o.CreatedByName) {
		toSerialize["created_by_name"] = o.CreatedByName
	}
	if !IsNil(o.CreatedByUserId) {
		toSerialize["created_by_user_id"] = o.CreatedByUserId
	}
	if !IsNil(o.LastChangeNote) {
		toSerialize["last_change_note"] = o.LastChangeNote
	}
	if !IsNil(o.LastModifiedAt) {
		toSerialize["last_modified_at"] = o.LastModifiedAt
	}
	if !IsNil(o.LastModifiedByEmail) {
		toSerialize["last_modified_by_email"] = o.LastModifiedByEmail
	}
	if !IsNil(o.LastModifiedByName) {
		toSerialize["last_modified_by_name"] = o.LastModifiedByName
	}
	if !IsNil(o.LastModifiedByUserId) {
		toSerialize["last_modified_by_user_id"] = o.LastModifiedByUserId
	}
	if !IsNil(o.AutoDisabledReason) {
		toSerialize["auto_disabled_reason"] = o.AutoDisabledReason
	}
	toSerialize["bare_alias"] = o.BareAlias
	toSerialize["enabled"] = o.Enabled
	toSerialize["id"] = o.Id
	toSerialize["model_alias"] = o.ModelAlias
	toSerialize["priority"] = o.Priority
	toSerialize["provider_id"] = o.ProviderId
	if !IsNil(o.RequestTimeoutSecs) {
		toSerialize["request_timeout_secs"] = o.RequestTimeoutSecs
	}
	toSerialize["retry_on_429_count"] = o.RetryOn429Count
	toSerialize["retry_on_429_max_wait_secs"] = o.RetryOn429MaxWaitSecs
	toSerialize["source"] = o.Source
	if !IsNil(o.StreamIdleTimeoutSecs) {
		toSerialize["stream_idle_timeout_secs"] = o.StreamIdleTimeoutSecs
	}
	toSerialize["upstream_model"] = o.UpstreamModel
	if o.BudgetStatus.IsSet() {
		toSerialize["budget_status"] = o.BudgetStatus.Get()
	}
	toSerialize["effective_pricing"] = o.EffectivePricing
	if o.RouteHealthStatus.IsSet() {
		toSerialize["route_health_status"] = o.RouteHealthStatus.Get()
	}
	if o.StaleStatus.IsSet() {
		toSerialize["stale_status"] = o.StaleStatus.Get()
	}
	return toSerialize, nil
}

func (o *ModelMappingWithBudgetStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cooldown_429_default_secs",
		"cooldown_base_secs",
		"cooldown_failure_threshold",
		"cooldown_max_secs",
		"cooldown_overloaded_secs",
		"cooldown_window_secs",
		"bare_alias",
		"enabled",
		"id",
		"model_alias",
		"priority",
		"provider_id",
		"retry_on_429_count",
		"retry_on_429_max_wait_secs",
		"source",
		"upstream_model",
		"effective_pricing",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelMappingWithBudgetStatus := _ModelMappingWithBudgetStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelMappingWithBudgetStatus)

	if err != nil {
		return err
	}

	*o = ModelMappingWithBudgetStatus(varModelMappingWithBudgetStatus)

	return err
}

type NullableModelMappingWithBudgetStatus struct {
	value *ModelMappingWithBudgetStatus
	isSet bool
}

func (v NullableModelMappingWithBudgetStatus) Get() *ModelMappingWithBudgetStatus {
	return v.value
}

func (v *NullableModelMappingWithBudgetStatus) Set(val *ModelMappingWithBudgetStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableModelMappingWithBudgetStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableModelMappingWithBudgetStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelMappingWithBudgetStatus(val *ModelMappingWithBudgetStatus) *NullableModelMappingWithBudgetStatus {
	return &NullableModelMappingWithBudgetStatus{value: val, isSet: true}
}

func (v NullableModelMappingWithBudgetStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelMappingWithBudgetStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


