/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// PricingChangeSource How a `model_pricing` version was produced. Persisted as a `VARCHAR(20)` constrained to one of these eight values (see migrations V34 + V35). Surfaced to admins as the \"source\" badge on each entry of the `PricingHistoryDialog`.
type PricingChangeSource string

// List of PricingChangeSource
const (
	PRICINGCHANGESOURCE_ADMIN_CREATE PricingChangeSource = "admin_create"
	PRICINGCHANGESOURCE_ADMIN_EDIT PricingChangeSource = "admin_edit"
	PRICINGCHANGESOURCE_ADMIN_SCHEDULE PricingChangeSource = "admin_schedule"
	PRICINGCHANGESOURCE_IMPORT PricingChangeSource = "import"
	PRICINGCHANGESOURCE_SYNC_MANUAL PricingChangeSource = "sync_manual"
	PRICINGCHANGESOURCE_SYNC_AUTO PricingChangeSource = "sync_auto"
	PRICINGCHANGESOURCE_ADMIN_ARCHIVE PricingChangeSource = "admin_archive"
	PRICINGCHANGESOURCE_ADMIN_RESTORE PricingChangeSource = "admin_restore"
)

// All allowed values of PricingChangeSource enum
var AllowedPricingChangeSourceEnumValues = []PricingChangeSource{
	"admin_create",
	"admin_edit",
	"admin_schedule",
	"import",
	"sync_manual",
	"sync_auto",
	"admin_archive",
	"admin_restore",
}

func (v *PricingChangeSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PricingChangeSource(value)
	for _, existing := range AllowedPricingChangeSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PricingChangeSource", value)
}

// NewPricingChangeSourceFromValue returns a pointer to a valid PricingChangeSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPricingChangeSourceFromValue(v string) (*PricingChangeSource, error) {
	ev := PricingChangeSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PricingChangeSource: valid values are %v", v, AllowedPricingChangeSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PricingChangeSource) IsValid() bool {
	for _, existing := range AllowedPricingChangeSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PricingChangeSource value
func (v PricingChangeSource) Ptr() *PricingChangeSource {
	return &v
}

type NullablePricingChangeSource struct {
	value *PricingChangeSource
	isSet bool
}

func (v NullablePricingChangeSource) Get() *PricingChangeSource {
	return v.value
}

func (v *NullablePricingChangeSource) Set(val *PricingChangeSource) {
	v.value = val
	v.isSet = true
}

func (v NullablePricingChangeSource) IsSet() bool {
	return v.isSet
}

func (v *NullablePricingChangeSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricingChangeSource(val *PricingChangeSource) *NullablePricingChangeSource {
	return &NullablePricingChangeSource{value: val, isSet: true}
}

func (v NullablePricingChangeSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricingChangeSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

