/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProviderConnectionResponseOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderConnectionResponseOneOf3{}

// ProviderConnectionResponseOneOf3 struct for ProviderConnectionResponseOneOf3
type ProviderConnectionResponseOneOf3 struct {
	AccessKeyId *string `json:"access_key_id,omitempty"`
	AuthType string `json:"auth_type"`
	Endpoint *string `json:"endpoint,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	HasCredentials bool `json:"has_credentials"`
	IamRoleArn *string `json:"iam_role_arn,omitempty"`
	Language string `json:"language"`
	OrgId string `json:"org_id"`
	Region string `json:"region"`
	Provider string `json:"provider"`
}

type _ProviderConnectionResponseOneOf3 ProviderConnectionResponseOneOf3

// NewProviderConnectionResponseOneOf3 instantiates a new ProviderConnectionResponseOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderConnectionResponseOneOf3(authType string, hasCredentials bool, language string, orgId string, region string, provider string) *ProviderConnectionResponseOneOf3 {
	this := ProviderConnectionResponseOneOf3{}
	this.AuthType = authType
	this.HasCredentials = hasCredentials
	this.Language = language
	this.OrgId = orgId
	this.Region = region
	this.Provider = provider
	return &this
}

// NewProviderConnectionResponseOneOf3WithDefaults instantiates a new ProviderConnectionResponseOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderConnectionResponseOneOf3WithDefaults() *ProviderConnectionResponseOneOf3 {
	this := ProviderConnectionResponseOneOf3{}
	return &this
}

// GetAccessKeyId returns the AccessKeyId field value if set, zero value otherwise.
func (o *ProviderConnectionResponseOneOf3) GetAccessKeyId() string {
	if o == nil || IsNil(o.AccessKeyId) {
		var ret string
		return ret
	}
	return *o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetAccessKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccessKeyId) {
		return nil, false
	}
	return o.AccessKeyId, true
}

// HasAccessKeyId returns a boolean if a field has been set.
func (o *ProviderConnectionResponseOneOf3) HasAccessKeyId() bool {
	if o != nil && !IsNil(o.AccessKeyId) {
		return true
	}

	return false
}

// SetAccessKeyId gets a reference to the given string and assigns it to the AccessKeyId field.
func (o *ProviderConnectionResponseOneOf3) SetAccessKeyId(v string) {
	o.AccessKeyId = &v
}

// GetAuthType returns the AuthType field value
func (o *ProviderConnectionResponseOneOf3) GetAuthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *ProviderConnectionResponseOneOf3) SetAuthType(v string) {
	o.AuthType = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *ProviderConnectionResponseOneOf3) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *ProviderConnectionResponseOneOf3) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *ProviderConnectionResponseOneOf3) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *ProviderConnectionResponseOneOf3) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *ProviderConnectionResponseOneOf3) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *ProviderConnectionResponseOneOf3) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetHasCredentials returns the HasCredentials field value
func (o *ProviderConnectionResponseOneOf3) GetHasCredentials() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasCredentials
}

// GetHasCredentialsOk returns a tuple with the HasCredentials field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetHasCredentialsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasCredentials, true
}

// SetHasCredentials sets field value
func (o *ProviderConnectionResponseOneOf3) SetHasCredentials(v bool) {
	o.HasCredentials = v
}

// GetIamRoleArn returns the IamRoleArn field value if set, zero value otherwise.
func (o *ProviderConnectionResponseOneOf3) GetIamRoleArn() string {
	if o == nil || IsNil(o.IamRoleArn) {
		var ret string
		return ret
	}
	return *o.IamRoleArn
}

// GetIamRoleArnOk returns a tuple with the IamRoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetIamRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.IamRoleArn) {
		return nil, false
	}
	return o.IamRoleArn, true
}

// HasIamRoleArn returns a boolean if a field has been set.
func (o *ProviderConnectionResponseOneOf3) HasIamRoleArn() bool {
	if o != nil && !IsNil(o.IamRoleArn) {
		return true
	}

	return false
}

// SetIamRoleArn gets a reference to the given string and assigns it to the IamRoleArn field.
func (o *ProviderConnectionResponseOneOf3) SetIamRoleArn(v string) {
	o.IamRoleArn = &v
}

// GetLanguage returns the Language field value
func (o *ProviderConnectionResponseOneOf3) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *ProviderConnectionResponseOneOf3) SetLanguage(v string) {
	o.Language = v
}

// GetOrgId returns the OrgId field value
func (o *ProviderConnectionResponseOneOf3) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ProviderConnectionResponseOneOf3) SetOrgId(v string) {
	o.OrgId = v
}

// GetRegion returns the Region field value
func (o *ProviderConnectionResponseOneOf3) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *ProviderConnectionResponseOneOf3) SetRegion(v string) {
	o.Region = v
}

// GetProvider returns the Provider field value
func (o *ProviderConnectionResponseOneOf3) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf3) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ProviderConnectionResponseOneOf3) SetProvider(v string) {
	o.Provider = v
}

func (o ProviderConnectionResponseOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderConnectionResponseOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessKeyId) {
		toSerialize["access_key_id"] = o.AccessKeyId
	}
	toSerialize["auth_type"] = o.AuthType
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	toSerialize["has_credentials"] = o.HasCredentials
	if !IsNil(o.IamRoleArn) {
		toSerialize["iam_role_arn"] = o.IamRoleArn
	}
	toSerialize["language"] = o.Language
	toSerialize["org_id"] = o.OrgId
	toSerialize["region"] = o.Region
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *ProviderConnectionResponseOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auth_type",
		"has_credentials",
		"language",
		"org_id",
		"region",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderConnectionResponseOneOf3 := _ProviderConnectionResponseOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderConnectionResponseOneOf3)

	if err != nil {
		return err
	}

	*o = ProviderConnectionResponseOneOf3(varProviderConnectionResponseOneOf3)

	return err
}

type NullableProviderConnectionResponseOneOf3 struct {
	value *ProviderConnectionResponseOneOf3
	isSet bool
}

func (v NullableProviderConnectionResponseOneOf3) Get() *ProviderConnectionResponseOneOf3 {
	return v.value
}

func (v *NullableProviderConnectionResponseOneOf3) Set(val *ProviderConnectionResponseOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderConnectionResponseOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderConnectionResponseOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderConnectionResponseOneOf3(val *ProviderConnectionResponseOneOf3) *NullableProviderConnectionResponseOneOf3 {
	return &NullableProviderConnectionResponseOneOf3{value: val, isSet: true}
}

func (v NullableProviderConnectionResponseOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderConnectionResponseOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


