/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateModelMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateModelMappingRequest{}

// CreateModelMappingRequest struct for CreateModelMappingRequest
type CreateModelMappingRequest struct {
	// Whether this row should participate in bare-name resolution. The admin handler treats `None` as \"infer from alias shape\" — custom aliases imply `true`, 1:1 enablement rows imply `false`. Pass `Some(true)` explicitly from the Model Routes tab to opt a 1:1 row into bare resolution.
	BareAlias NullableBool `json:"bare_alias,omitempty"`
	// Optional free-text note explaining why this route was added (BCP-3998). Surfaced on the row and mirrored into the audit event.
	ChangeNote NullableString `json:"change_note,omitempty"`
	// Cooldown on an upstream 429 that carries no usable `Retry-After` (a `Retry-After` sets the window instead). Range 1-3600, and at most `cooldown_max_secs`; default 30.
	Cooldown429DefaultSecs NullableInt32 `json:"cooldown_429_default_secs,omitempty"`
	// First cooldown window once the threshold trips, doubled on each failed recovery probe up to `cooldown_max_secs`. Range 1-3600, and at most `cooldown_max_secs`; default 30.
	CooldownBaseSecs NullableInt32 `json:"cooldown_base_secs,omitempty"`
	// Gateway failures (5xx, timeouts, connection errors, managed-key 401/403) within `cooldown_window_secs` that cool the route. `0` disables every cooldown of the shared route (rolling failures, 429 and 529); per-user credential cooldowns on passthrough routes still apply. Range 0-100; default 10.
	CooldownFailureThreshold NullableInt32 `json:"cooldown_failure_threshold,omitempty"`
	// Cap on every cooldown window: doubling, 429 and 529. Range 1-86400; default 300.
	CooldownMaxSecs NullableInt32 `json:"cooldown_max_secs,omitempty"`
	// Flat cooldown on an upstream 529 \"overloaded\" with no usable `Retry-After`; it does not spend the failure budget. `0` counts a 529 as an ordinary gateway failure instead. Range 0-3600, and at most `cooldown_max_secs` unless 0; default 10.
	CooldownOverloadedSecs NullableInt32 `json:"cooldown_overloaded_secs,omitempty"`
	// Width of the rolling failure window, seconds. Range 1-3600; default 60.
	CooldownWindowSecs NullableInt32 `json:"cooldown_window_secs,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	ModelAlias string `json:"model_alias"`
	Priority *int32 `json:"priority,omitempty"`
	ProviderId string `json:"provider_id"`
	// Per-mapping total-request timeout for non-streaming responses (streaming responses have no total timeout). On a custom-alias row this sets the *route* tier; on a 1:1 enablement (anchor) row it sets the *model* tier consulted for every alias of that model. `None` (the default) lets `model_mappings.create` write the platform default (`TOTAL_REQUEST_TIMEOUT_DEFAULT_SECS`) at the route tier. The range is fixed platform policy (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`); see [`crate::proxy::timeouts`].
	RequestTimeoutSecs NullableInt32 `json:"request_timeout_secs,omitempty"`
	// Same-route retries on upstream 429. 0 means immediate failover.
	RetryOn429Count *int32 `json:"retry_on_429_count,omitempty"`
	// Cap on honoring upstream `Retry-After`. 0 means use a small default.
	RetryOn429MaxWaitSecs *int32 `json:"retry_on_429_max_wait_secs,omitempty"`
	// Where this model came from. The Add Models dialog sends `Custom` from its free-text branch and `Catalog` from the picker; those two paths already differ client-side, and this is what carries the difference through to storage.  `None` means \"infer\": the handler inherits the anchor's provenance when one exists (so a route created on Model Routes agrees with the enablement it points at), and otherwise falls back to `Catalog`. SDK and curl callers therefore land on `Catalog` by default — accepted, since the pill exists to catch a typo in the UI and an API caller is not its audience.
	Source NullableModelSource `json:"source,omitempty"`
	// Per-mapping stream-idle (per-chunk) timeout for streaming responses. `None` (the default) lets `model_mappings.create` write the platform default (`STREAM_IDLE_TIMEOUT_DEFAULT_SECS`) at the route tier. The range is fixed platform policy (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`); see [`crate::proxy::timeouts`].
	StreamIdleTimeoutSecs NullableInt32 `json:"stream_idle_timeout_secs,omitempty"`
	UpstreamModel string `json:"upstream_model"`
}

type _CreateModelMappingRequest CreateModelMappingRequest

// NewCreateModelMappingRequest instantiates a new CreateModelMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateModelMappingRequest(modelAlias string, providerId string, upstreamModel string) *CreateModelMappingRequest {
	this := CreateModelMappingRequest{}
	this.ModelAlias = modelAlias
	this.ProviderId = providerId
	this.UpstreamModel = upstreamModel
	return &this
}

// NewCreateModelMappingRequestWithDefaults instantiates a new CreateModelMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateModelMappingRequestWithDefaults() *CreateModelMappingRequest {
	this := CreateModelMappingRequest{}
	return &this
}

// GetBareAlias returns the BareAlias field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetBareAlias() bool {
	if o == nil || IsNil(o.BareAlias.Get()) {
		var ret bool
		return ret
	}
	return *o.BareAlias.Get()
}

// GetBareAliasOk returns a tuple with the BareAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetBareAliasOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BareAlias.Get(), o.BareAlias.IsSet()
}

// HasBareAlias returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasBareAlias() bool {
	if o != nil && o.BareAlias.IsSet() {
		return true
	}

	return false
}

// SetBareAlias gets a reference to the given NullableBool and assigns it to the BareAlias field.
func (o *CreateModelMappingRequest) SetBareAlias(v bool) {
	o.BareAlias.Set(&v)
}
// SetBareAliasNil sets the value for BareAlias to be an explicit nil
func (o *CreateModelMappingRequest) SetBareAliasNil() {
	o.BareAlias.Set(nil)
}

// UnsetBareAlias ensures that no value is present for BareAlias, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetBareAlias() {
	o.BareAlias.Unset()
}

// GetChangeNote returns the ChangeNote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetChangeNote() string {
	if o == nil || IsNil(o.ChangeNote.Get()) {
		var ret string
		return ret
	}
	return *o.ChangeNote.Get()
}

// GetChangeNoteOk returns a tuple with the ChangeNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetChangeNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeNote.Get(), o.ChangeNote.IsSet()
}

// HasChangeNote returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasChangeNote() bool {
	if o != nil && o.ChangeNote.IsSet() {
		return true
	}

	return false
}

// SetChangeNote gets a reference to the given NullableString and assigns it to the ChangeNote field.
func (o *CreateModelMappingRequest) SetChangeNote(v string) {
	o.ChangeNote.Set(&v)
}
// SetChangeNoteNil sets the value for ChangeNote to be an explicit nil
func (o *CreateModelMappingRequest) SetChangeNoteNil() {
	o.ChangeNote.Set(nil)
}

// UnsetChangeNote ensures that no value is present for ChangeNote, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetChangeNote() {
	o.ChangeNote.Unset()
}

// GetCooldown429DefaultSecs returns the Cooldown429DefaultSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetCooldown429DefaultSecs() int32 {
	if o == nil || IsNil(o.Cooldown429DefaultSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.Cooldown429DefaultSecs.Get()
}

// GetCooldown429DefaultSecsOk returns a tuple with the Cooldown429DefaultSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetCooldown429DefaultSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cooldown429DefaultSecs.Get(), o.Cooldown429DefaultSecs.IsSet()
}

// HasCooldown429DefaultSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasCooldown429DefaultSecs() bool {
	if o != nil && o.Cooldown429DefaultSecs.IsSet() {
		return true
	}

	return false
}

// SetCooldown429DefaultSecs gets a reference to the given NullableInt32 and assigns it to the Cooldown429DefaultSecs field.
func (o *CreateModelMappingRequest) SetCooldown429DefaultSecs(v int32) {
	o.Cooldown429DefaultSecs.Set(&v)
}
// SetCooldown429DefaultSecsNil sets the value for Cooldown429DefaultSecs to be an explicit nil
func (o *CreateModelMappingRequest) SetCooldown429DefaultSecsNil() {
	o.Cooldown429DefaultSecs.Set(nil)
}

// UnsetCooldown429DefaultSecs ensures that no value is present for Cooldown429DefaultSecs, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetCooldown429DefaultSecs() {
	o.Cooldown429DefaultSecs.Unset()
}

// GetCooldownBaseSecs returns the CooldownBaseSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetCooldownBaseSecs() int32 {
	if o == nil || IsNil(o.CooldownBaseSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.CooldownBaseSecs.Get()
}

// GetCooldownBaseSecsOk returns a tuple with the CooldownBaseSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetCooldownBaseSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CooldownBaseSecs.Get(), o.CooldownBaseSecs.IsSet()
}

// HasCooldownBaseSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasCooldownBaseSecs() bool {
	if o != nil && o.CooldownBaseSecs.IsSet() {
		return true
	}

	return false
}

// SetCooldownBaseSecs gets a reference to the given NullableInt32 and assigns it to the CooldownBaseSecs field.
func (o *CreateModelMappingRequest) SetCooldownBaseSecs(v int32) {
	o.CooldownBaseSecs.Set(&v)
}
// SetCooldownBaseSecsNil sets the value for CooldownBaseSecs to be an explicit nil
func (o *CreateModelMappingRequest) SetCooldownBaseSecsNil() {
	o.CooldownBaseSecs.Set(nil)
}

// UnsetCooldownBaseSecs ensures that no value is present for CooldownBaseSecs, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetCooldownBaseSecs() {
	o.CooldownBaseSecs.Unset()
}

// GetCooldownFailureThreshold returns the CooldownFailureThreshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetCooldownFailureThreshold() int32 {
	if o == nil || IsNil(o.CooldownFailureThreshold.Get()) {
		var ret int32
		return ret
	}
	return *o.CooldownFailureThreshold.Get()
}

// GetCooldownFailureThresholdOk returns a tuple with the CooldownFailureThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetCooldownFailureThresholdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CooldownFailureThreshold.Get(), o.CooldownFailureThreshold.IsSet()
}

// HasCooldownFailureThreshold returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasCooldownFailureThreshold() bool {
	if o != nil && o.CooldownFailureThreshold.IsSet() {
		return true
	}

	return false
}

// SetCooldownFailureThreshold gets a reference to the given NullableInt32 and assigns it to the CooldownFailureThreshold field.
func (o *CreateModelMappingRequest) SetCooldownFailureThreshold(v int32) {
	o.CooldownFailureThreshold.Set(&v)
}
// SetCooldownFailureThresholdNil sets the value for CooldownFailureThreshold to be an explicit nil
func (o *CreateModelMappingRequest) SetCooldownFailureThresholdNil() {
	o.CooldownFailureThreshold.Set(nil)
}

// UnsetCooldownFailureThreshold ensures that no value is present for CooldownFailureThreshold, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetCooldownFailureThreshold() {
	o.CooldownFailureThreshold.Unset()
}

// GetCooldownMaxSecs returns the CooldownMaxSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetCooldownMaxSecs() int32 {
	if o == nil || IsNil(o.CooldownMaxSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.CooldownMaxSecs.Get()
}

// GetCooldownMaxSecsOk returns a tuple with the CooldownMaxSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetCooldownMaxSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CooldownMaxSecs.Get(), o.CooldownMaxSecs.IsSet()
}

// HasCooldownMaxSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasCooldownMaxSecs() bool {
	if o != nil && o.CooldownMaxSecs.IsSet() {
		return true
	}

	return false
}

// SetCooldownMaxSecs gets a reference to the given NullableInt32 and assigns it to the CooldownMaxSecs field.
func (o *CreateModelMappingRequest) SetCooldownMaxSecs(v int32) {
	o.CooldownMaxSecs.Set(&v)
}
// SetCooldownMaxSecsNil sets the value for CooldownMaxSecs to be an explicit nil
func (o *CreateModelMappingRequest) SetCooldownMaxSecsNil() {
	o.CooldownMaxSecs.Set(nil)
}

// UnsetCooldownMaxSecs ensures that no value is present for CooldownMaxSecs, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetCooldownMaxSecs() {
	o.CooldownMaxSecs.Unset()
}

// GetCooldownOverloadedSecs returns the CooldownOverloadedSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetCooldownOverloadedSecs() int32 {
	if o == nil || IsNil(o.CooldownOverloadedSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.CooldownOverloadedSecs.Get()
}

// GetCooldownOverloadedSecsOk returns a tuple with the CooldownOverloadedSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetCooldownOverloadedSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CooldownOverloadedSecs.Get(), o.CooldownOverloadedSecs.IsSet()
}

// HasCooldownOverloadedSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasCooldownOverloadedSecs() bool {
	if o != nil && o.CooldownOverloadedSecs.IsSet() {
		return true
	}

	return false
}

// SetCooldownOverloadedSecs gets a reference to the given NullableInt32 and assigns it to the CooldownOverloadedSecs field.
func (o *CreateModelMappingRequest) SetCooldownOverloadedSecs(v int32) {
	o.CooldownOverloadedSecs.Set(&v)
}
// SetCooldownOverloadedSecsNil sets the value for CooldownOverloadedSecs to be an explicit nil
func (o *CreateModelMappingRequest) SetCooldownOverloadedSecsNil() {
	o.CooldownOverloadedSecs.Set(nil)
}

// UnsetCooldownOverloadedSecs ensures that no value is present for CooldownOverloadedSecs, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetCooldownOverloadedSecs() {
	o.CooldownOverloadedSecs.Unset()
}

// GetCooldownWindowSecs returns the CooldownWindowSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetCooldownWindowSecs() int32 {
	if o == nil || IsNil(o.CooldownWindowSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.CooldownWindowSecs.Get()
}

// GetCooldownWindowSecsOk returns a tuple with the CooldownWindowSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetCooldownWindowSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CooldownWindowSecs.Get(), o.CooldownWindowSecs.IsSet()
}

// HasCooldownWindowSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasCooldownWindowSecs() bool {
	if o != nil && o.CooldownWindowSecs.IsSet() {
		return true
	}

	return false
}

// SetCooldownWindowSecs gets a reference to the given NullableInt32 and assigns it to the CooldownWindowSecs field.
func (o *CreateModelMappingRequest) SetCooldownWindowSecs(v int32) {
	o.CooldownWindowSecs.Set(&v)
}
// SetCooldownWindowSecsNil sets the value for CooldownWindowSecs to be an explicit nil
func (o *CreateModelMappingRequest) SetCooldownWindowSecsNil() {
	o.CooldownWindowSecs.Set(nil)
}

// UnsetCooldownWindowSecs ensures that no value is present for CooldownWindowSecs, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetCooldownWindowSecs() {
	o.CooldownWindowSecs.Unset()
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateModelMappingRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateModelMappingRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateModelMappingRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetModelAlias returns the ModelAlias field value
func (o *CreateModelMappingRequest) GetModelAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelAlias
}

// GetModelAliasOk returns a tuple with the ModelAlias field value
// and a boolean to check if the value has been set.
func (o *CreateModelMappingRequest) GetModelAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelAlias, true
}

// SetModelAlias sets field value
func (o *CreateModelMappingRequest) SetModelAlias(v string) {
	o.ModelAlias = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *CreateModelMappingRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateModelMappingRequest) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *CreateModelMappingRequest) SetPriority(v int32) {
	o.Priority = &v
}

// GetProviderId returns the ProviderId field value
func (o *CreateModelMappingRequest) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *CreateModelMappingRequest) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *CreateModelMappingRequest) SetProviderId(v string) {
	o.ProviderId = v
}

// GetRequestTimeoutSecs returns the RequestTimeoutSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetRequestTimeoutSecs() int32 {
	if o == nil || IsNil(o.RequestTimeoutSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.RequestTimeoutSecs.Get()
}

// GetRequestTimeoutSecsOk returns a tuple with the RequestTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetRequestTimeoutSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestTimeoutSecs.Get(), o.RequestTimeoutSecs.IsSet()
}

// HasRequestTimeoutSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasRequestTimeoutSecs() bool {
	if o != nil && o.RequestTimeoutSecs.IsSet() {
		return true
	}

	return false
}

// SetRequestTimeoutSecs gets a reference to the given NullableInt32 and assigns it to the RequestTimeoutSecs field.
func (o *CreateModelMappingRequest) SetRequestTimeoutSecs(v int32) {
	o.RequestTimeoutSecs.Set(&v)
}
// SetRequestTimeoutSecsNil sets the value for RequestTimeoutSecs to be an explicit nil
func (o *CreateModelMappingRequest) SetRequestTimeoutSecsNil() {
	o.RequestTimeoutSecs.Set(nil)
}

// UnsetRequestTimeoutSecs ensures that no value is present for RequestTimeoutSecs, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetRequestTimeoutSecs() {
	o.RequestTimeoutSecs.Unset()
}

// GetRetryOn429Count returns the RetryOn429Count field value if set, zero value otherwise.
func (o *CreateModelMappingRequest) GetRetryOn429Count() int32 {
	if o == nil || IsNil(o.RetryOn429Count) {
		var ret int32
		return ret
	}
	return *o.RetryOn429Count
}

// GetRetryOn429CountOk returns a tuple with the RetryOn429Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateModelMappingRequest) GetRetryOn429CountOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryOn429Count) {
		return nil, false
	}
	return o.RetryOn429Count, true
}

// HasRetryOn429Count returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasRetryOn429Count() bool {
	if o != nil && !IsNil(o.RetryOn429Count) {
		return true
	}

	return false
}

// SetRetryOn429Count gets a reference to the given int32 and assigns it to the RetryOn429Count field.
func (o *CreateModelMappingRequest) SetRetryOn429Count(v int32) {
	o.RetryOn429Count = &v
}

// GetRetryOn429MaxWaitSecs returns the RetryOn429MaxWaitSecs field value if set, zero value otherwise.
func (o *CreateModelMappingRequest) GetRetryOn429MaxWaitSecs() int32 {
	if o == nil || IsNil(o.RetryOn429MaxWaitSecs) {
		var ret int32
		return ret
	}
	return *o.RetryOn429MaxWaitSecs
}

// GetRetryOn429MaxWaitSecsOk returns a tuple with the RetryOn429MaxWaitSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateModelMappingRequest) GetRetryOn429MaxWaitSecsOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryOn429MaxWaitSecs) {
		return nil, false
	}
	return o.RetryOn429MaxWaitSecs, true
}

// HasRetryOn429MaxWaitSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasRetryOn429MaxWaitSecs() bool {
	if o != nil && !IsNil(o.RetryOn429MaxWaitSecs) {
		return true
	}

	return false
}

// SetRetryOn429MaxWaitSecs gets a reference to the given int32 and assigns it to the RetryOn429MaxWaitSecs field.
func (o *CreateModelMappingRequest) SetRetryOn429MaxWaitSecs(v int32) {
	o.RetryOn429MaxWaitSecs = &v
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetSource() ModelSource {
	if o == nil || IsNil(o.Source.Get()) {
		var ret ModelSource
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetSourceOk() (*ModelSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableModelSource and assigns it to the Source field.
func (o *CreateModelMappingRequest) SetSource(v ModelSource) {
	o.Source.Set(&v)
}
// SetSourceNil sets the value for Source to be an explicit nil
func (o *CreateModelMappingRequest) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetSource() {
	o.Source.Unset()
}

// GetStreamIdleTimeoutSecs returns the StreamIdleTimeoutSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateModelMappingRequest) GetStreamIdleTimeoutSecs() int32 {
	if o == nil || IsNil(o.StreamIdleTimeoutSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.StreamIdleTimeoutSecs.Get()
}

// GetStreamIdleTimeoutSecsOk returns a tuple with the StreamIdleTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateModelMappingRequest) GetStreamIdleTimeoutSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StreamIdleTimeoutSecs.Get(), o.StreamIdleTimeoutSecs.IsSet()
}

// HasStreamIdleTimeoutSecs returns a boolean if a field has been set.
func (o *CreateModelMappingRequest) HasStreamIdleTimeoutSecs() bool {
	if o != nil && o.StreamIdleTimeoutSecs.IsSet() {
		return true
	}

	return false
}

// SetStreamIdleTimeoutSecs gets a reference to the given NullableInt32 and assigns it to the StreamIdleTimeoutSecs field.
func (o *CreateModelMappingRequest) SetStreamIdleTimeoutSecs(v int32) {
	o.StreamIdleTimeoutSecs.Set(&v)
}
// SetStreamIdleTimeoutSecsNil sets the value for StreamIdleTimeoutSecs to be an explicit nil
func (o *CreateModelMappingRequest) SetStreamIdleTimeoutSecsNil() {
	o.StreamIdleTimeoutSecs.Set(nil)
}

// UnsetStreamIdleTimeoutSecs ensures that no value is present for StreamIdleTimeoutSecs, not even an explicit nil
func (o *CreateModelMappingRequest) UnsetStreamIdleTimeoutSecs() {
	o.StreamIdleTimeoutSecs.Unset()
}

// GetUpstreamModel returns the UpstreamModel field value
func (o *CreateModelMappingRequest) GetUpstreamModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpstreamModel
}

// GetUpstreamModelOk returns a tuple with the UpstreamModel field value
// and a boolean to check if the value has been set.
func (o *CreateModelMappingRequest) GetUpstreamModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpstreamModel, true
}

// SetUpstreamModel sets field value
func (o *CreateModelMappingRequest) SetUpstreamModel(v string) {
	o.UpstreamModel = v
}

func (o CreateModelMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateModelMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BareAlias.IsSet() {
		toSerialize["bare_alias"] = o.BareAlias.Get()
	}
	if o.ChangeNote.IsSet() {
		toSerialize["change_note"] = o.ChangeNote.Get()
	}
	if o.Cooldown429DefaultSecs.IsSet() {
		toSerialize["cooldown_429_default_secs"] = o.Cooldown429DefaultSecs.Get()
	}
	if o.CooldownBaseSecs.IsSet() {
		toSerialize["cooldown_base_secs"] = o.CooldownBaseSecs.Get()
	}
	if o.CooldownFailureThreshold.IsSet() {
		toSerialize["cooldown_failure_threshold"] = o.CooldownFailureThreshold.Get()
	}
	if o.CooldownMaxSecs.IsSet() {
		toSerialize["cooldown_max_secs"] = o.CooldownMaxSecs.Get()
	}
	if o.CooldownOverloadedSecs.IsSet() {
		toSerialize["cooldown_overloaded_secs"] = o.CooldownOverloadedSecs.Get()
	}
	if o.CooldownWindowSecs.IsSet() {
		toSerialize["cooldown_window_secs"] = o.CooldownWindowSecs.Get()
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	toSerialize["model_alias"] = o.ModelAlias
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	toSerialize["provider_id"] = o.ProviderId
	if o.RequestTimeoutSecs.IsSet() {
		toSerialize["request_timeout_secs"] = o.RequestTimeoutSecs.Get()
	}
	if !IsNil(o.RetryOn429Count) {
		toSerialize["retry_on_429_count"] = o.RetryOn429Count
	}
	if !IsNil(o.RetryOn429MaxWaitSecs) {
		toSerialize["retry_on_429_max_wait_secs"] = o.RetryOn429MaxWaitSecs
	}
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	if o.StreamIdleTimeoutSecs.IsSet() {
		toSerialize["stream_idle_timeout_secs"] = o.StreamIdleTimeoutSecs.Get()
	}
	toSerialize["upstream_model"] = o.UpstreamModel
	return toSerialize, nil
}

func (o *CreateModelMappingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model_alias",
		"provider_id",
		"upstream_model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateModelMappingRequest := _CreateModelMappingRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateModelMappingRequest)

	if err != nil {
		return err
	}

	*o = CreateModelMappingRequest(varCreateModelMappingRequest)

	return err
}

type NullableCreateModelMappingRequest struct {
	value *CreateModelMappingRequest
	isSet bool
}

func (v NullableCreateModelMappingRequest) Get() *CreateModelMappingRequest {
	return v.value
}

func (v *NullableCreateModelMappingRequest) Set(val *CreateModelMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateModelMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateModelMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateModelMappingRequest(val *CreateModelMappingRequest) *NullableCreateModelMappingRequest {
	return &NullableCreateModelMappingRequest{value: val, isSet: true}
}

func (v NullableCreateModelMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateModelMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


