/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AzureAiLanguagePiiConnectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureAiLanguagePiiConnectionResponse{}

// AzureAiLanguagePiiConnectionResponse struct for AzureAiLanguagePiiConnectionResponse
type AzureAiLanguagePiiConnectionResponse struct {
	ApiVersion string `json:"api_version"`
	Endpoint string `json:"endpoint"`
	HasApiKey bool `json:"has_api_key"`
	Language string `json:"language"`
	OrgId string `json:"org_id"`
}

type _AzureAiLanguagePiiConnectionResponse AzureAiLanguagePiiConnectionResponse

// NewAzureAiLanguagePiiConnectionResponse instantiates a new AzureAiLanguagePiiConnectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureAiLanguagePiiConnectionResponse(apiVersion string, endpoint string, hasApiKey bool, language string, orgId string) *AzureAiLanguagePiiConnectionResponse {
	this := AzureAiLanguagePiiConnectionResponse{}
	this.ApiVersion = apiVersion
	this.Endpoint = endpoint
	this.HasApiKey = hasApiKey
	this.Language = language
	this.OrgId = orgId
	return &this
}

// NewAzureAiLanguagePiiConnectionResponseWithDefaults instantiates a new AzureAiLanguagePiiConnectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureAiLanguagePiiConnectionResponseWithDefaults() *AzureAiLanguagePiiConnectionResponse {
	this := AzureAiLanguagePiiConnectionResponse{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *AzureAiLanguagePiiConnectionResponse) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *AzureAiLanguagePiiConnectionResponse) GetApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *AzureAiLanguagePiiConnectionResponse) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetEndpoint returns the Endpoint field value
func (o *AzureAiLanguagePiiConnectionResponse) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *AzureAiLanguagePiiConnectionResponse) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *AzureAiLanguagePiiConnectionResponse) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetHasApiKey returns the HasApiKey field value
func (o *AzureAiLanguagePiiConnectionResponse) GetHasApiKey() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasApiKey
}

// GetHasApiKeyOk returns a tuple with the HasApiKey field value
// and a boolean to check if the value has been set.
func (o *AzureAiLanguagePiiConnectionResponse) GetHasApiKeyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasApiKey, true
}

// SetHasApiKey sets field value
func (o *AzureAiLanguagePiiConnectionResponse) SetHasApiKey(v bool) {
	o.HasApiKey = v
}

// GetLanguage returns the Language field value
func (o *AzureAiLanguagePiiConnectionResponse) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *AzureAiLanguagePiiConnectionResponse) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *AzureAiLanguagePiiConnectionResponse) SetLanguage(v string) {
	o.Language = v
}

// GetOrgId returns the OrgId field value
func (o *AzureAiLanguagePiiConnectionResponse) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *AzureAiLanguagePiiConnectionResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *AzureAiLanguagePiiConnectionResponse) SetOrgId(v string) {
	o.OrgId = v
}

func (o AzureAiLanguagePiiConnectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureAiLanguagePiiConnectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_version"] = o.ApiVersion
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["has_api_key"] = o.HasApiKey
	toSerialize["language"] = o.Language
	toSerialize["org_id"] = o.OrgId
	return toSerialize, nil
}

func (o *AzureAiLanguagePiiConnectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_version",
		"endpoint",
		"has_api_key",
		"language",
		"org_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureAiLanguagePiiConnectionResponse := _AzureAiLanguagePiiConnectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAzureAiLanguagePiiConnectionResponse)

	if err != nil {
		return err
	}

	*o = AzureAiLanguagePiiConnectionResponse(varAzureAiLanguagePiiConnectionResponse)

	return err
}

type NullableAzureAiLanguagePiiConnectionResponse struct {
	value *AzureAiLanguagePiiConnectionResponse
	isSet bool
}

func (v NullableAzureAiLanguagePiiConnectionResponse) Get() *AzureAiLanguagePiiConnectionResponse {
	return v.value
}

func (v *NullableAzureAiLanguagePiiConnectionResponse) Set(val *AzureAiLanguagePiiConnectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureAiLanguagePiiConnectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureAiLanguagePiiConnectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureAiLanguagePiiConnectionResponse(val *AzureAiLanguagePiiConnectionResponse) *NullableAzureAiLanguagePiiConnectionResponse {
	return &NullableAzureAiLanguagePiiConnectionResponse{value: val, isSet: true}
}

func (v NullableAzureAiLanguagePiiConnectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureAiLanguagePiiConnectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


