/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateModelMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateModelMappingRequest{}

// UpdateModelMappingRequest struct for UpdateModelMappingRequest
type UpdateModelMappingRequest struct {
	BareAlias NullableBool `json:"bare_alias,omitempty"`
	// Optional free-text note explaining why this edit was made (BCP-3998).  Deliberately *not* tri-state like the timeout overrides above: omitting it clears the previous note, because the note describes the latest change and an unrelated later edit must not inherit an explanation written for a different one.
	ChangeNote NullableString `json:"change_note,omitempty"`
	Enabled NullableBool `json:"enabled,omitempty"`
	ModelAlias NullableString `json:"model_alias,omitempty"`
	Priority NullableInt32 `json:"priority,omitempty"`
	// `None` (omitted) leaves the column unchanged. `Some(None)` (JSON `null`) clears the override. `Some(Some(secs))` sets the non-streaming total-request timeout; the range is fixed platform policy (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`, see [`crate::proxy::timeouts`]).
	RequestTimeoutSecs NullableInt32 `json:"request_timeout_secs,omitempty"`
	RetryOn429Count NullableInt32 `json:"retry_on_429_count,omitempty"`
	RetryOn429MaxWaitSecs NullableInt32 `json:"retry_on_429_max_wait_secs,omitempty"`
	// `None` (omitted) leaves the column unchanged. `Some(None)` (JSON `null`) clears the override. `Some(Some(secs))` sets the streaming per-chunk timeout; the range is fixed platform policy (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`, see [`crate::proxy::timeouts`]).
	StreamIdleTimeoutSecs NullableInt32 `json:"stream_idle_timeout_secs,omitempty"`
	UpstreamModel NullableString `json:"upstream_model,omitempty"`
}

// NewUpdateModelMappingRequest instantiates a new UpdateModelMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateModelMappingRequest() *UpdateModelMappingRequest {
	this := UpdateModelMappingRequest{}
	return &this
}

// NewUpdateModelMappingRequestWithDefaults instantiates a new UpdateModelMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateModelMappingRequestWithDefaults() *UpdateModelMappingRequest {
	this := UpdateModelMappingRequest{}
	return &this
}

// GetBareAlias returns the BareAlias field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetBareAlias() bool {
	if o == nil || IsNil(o.BareAlias.Get()) {
		var ret bool
		return ret
	}
	return *o.BareAlias.Get()
}

// GetBareAliasOk returns a tuple with the BareAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetBareAliasOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BareAlias.Get(), o.BareAlias.IsSet()
}

// HasBareAlias returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasBareAlias() bool {
	if o != nil && o.BareAlias.IsSet() {
		return true
	}

	return false
}

// SetBareAlias gets a reference to the given NullableBool and assigns it to the BareAlias field.
func (o *UpdateModelMappingRequest) SetBareAlias(v bool) {
	o.BareAlias.Set(&v)
}
// SetBareAliasNil sets the value for BareAlias to be an explicit nil
func (o *UpdateModelMappingRequest) SetBareAliasNil() {
	o.BareAlias.Set(nil)
}

// UnsetBareAlias ensures that no value is present for BareAlias, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetBareAlias() {
	o.BareAlias.Unset()
}

// GetChangeNote returns the ChangeNote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetChangeNote() string {
	if o == nil || IsNil(o.ChangeNote.Get()) {
		var ret string
		return ret
	}
	return *o.ChangeNote.Get()
}

// GetChangeNoteOk returns a tuple with the ChangeNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetChangeNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeNote.Get(), o.ChangeNote.IsSet()
}

// HasChangeNote returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasChangeNote() bool {
	if o != nil && o.ChangeNote.IsSet() {
		return true
	}

	return false
}

// SetChangeNote gets a reference to the given NullableString and assigns it to the ChangeNote field.
func (o *UpdateModelMappingRequest) SetChangeNote(v string) {
	o.ChangeNote.Set(&v)
}
// SetChangeNoteNil sets the value for ChangeNote to be an explicit nil
func (o *UpdateModelMappingRequest) SetChangeNoteNil() {
	o.ChangeNote.Set(nil)
}

// UnsetChangeNote ensures that no value is present for ChangeNote, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetChangeNote() {
	o.ChangeNote.Unset()
}

// GetEnabled returns the Enabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled.Get()) {
		var ret bool
		return ret
	}
	return *o.Enabled.Get()
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enabled.Get(), o.Enabled.IsSet()
}

// HasEnabled returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasEnabled() bool {
	if o != nil && o.Enabled.IsSet() {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given NullableBool and assigns it to the Enabled field.
func (o *UpdateModelMappingRequest) SetEnabled(v bool) {
	o.Enabled.Set(&v)
}
// SetEnabledNil sets the value for Enabled to be an explicit nil
func (o *UpdateModelMappingRequest) SetEnabledNil() {
	o.Enabled.Set(nil)
}

// UnsetEnabled ensures that no value is present for Enabled, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetEnabled() {
	o.Enabled.Unset()
}

// GetModelAlias returns the ModelAlias field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetModelAlias() string {
	if o == nil || IsNil(o.ModelAlias.Get()) {
		var ret string
		return ret
	}
	return *o.ModelAlias.Get()
}

// GetModelAliasOk returns a tuple with the ModelAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetModelAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModelAlias.Get(), o.ModelAlias.IsSet()
}

// HasModelAlias returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasModelAlias() bool {
	if o != nil && o.ModelAlias.IsSet() {
		return true
	}

	return false
}

// SetModelAlias gets a reference to the given NullableString and assigns it to the ModelAlias field.
func (o *UpdateModelMappingRequest) SetModelAlias(v string) {
	o.ModelAlias.Set(&v)
}
// SetModelAliasNil sets the value for ModelAlias to be an explicit nil
func (o *UpdateModelMappingRequest) SetModelAliasNil() {
	o.ModelAlias.Set(nil)
}

// UnsetModelAlias ensures that no value is present for ModelAlias, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetModelAlias() {
	o.ModelAlias.Unset()
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority.Get()) {
		var ret int32
		return ret
	}
	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// HasPriority returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasPriority() bool {
	if o != nil && o.Priority.IsSet() {
		return true
	}

	return false
}

// SetPriority gets a reference to the given NullableInt32 and assigns it to the Priority field.
func (o *UpdateModelMappingRequest) SetPriority(v int32) {
	o.Priority.Set(&v)
}
// SetPriorityNil sets the value for Priority to be an explicit nil
func (o *UpdateModelMappingRequest) SetPriorityNil() {
	o.Priority.Set(nil)
}

// UnsetPriority ensures that no value is present for Priority, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetPriority() {
	o.Priority.Unset()
}

// GetRequestTimeoutSecs returns the RequestTimeoutSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetRequestTimeoutSecs() int32 {
	if o == nil || IsNil(o.RequestTimeoutSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.RequestTimeoutSecs.Get()
}

// GetRequestTimeoutSecsOk returns a tuple with the RequestTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetRequestTimeoutSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestTimeoutSecs.Get(), o.RequestTimeoutSecs.IsSet()
}

// HasRequestTimeoutSecs returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasRequestTimeoutSecs() bool {
	if o != nil && o.RequestTimeoutSecs.IsSet() {
		return true
	}

	return false
}

// SetRequestTimeoutSecs gets a reference to the given NullableInt32 and assigns it to the RequestTimeoutSecs field.
func (o *UpdateModelMappingRequest) SetRequestTimeoutSecs(v int32) {
	o.RequestTimeoutSecs.Set(&v)
}
// SetRequestTimeoutSecsNil sets the value for RequestTimeoutSecs to be an explicit nil
func (o *UpdateModelMappingRequest) SetRequestTimeoutSecsNil() {
	o.RequestTimeoutSecs.Set(nil)
}

// UnsetRequestTimeoutSecs ensures that no value is present for RequestTimeoutSecs, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetRequestTimeoutSecs() {
	o.RequestTimeoutSecs.Unset()
}

// GetRetryOn429Count returns the RetryOn429Count field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetRetryOn429Count() int32 {
	if o == nil || IsNil(o.RetryOn429Count.Get()) {
		var ret int32
		return ret
	}
	return *o.RetryOn429Count.Get()
}

// GetRetryOn429CountOk returns a tuple with the RetryOn429Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetRetryOn429CountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetryOn429Count.Get(), o.RetryOn429Count.IsSet()
}

// HasRetryOn429Count returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasRetryOn429Count() bool {
	if o != nil && o.RetryOn429Count.IsSet() {
		return true
	}

	return false
}

// SetRetryOn429Count gets a reference to the given NullableInt32 and assigns it to the RetryOn429Count field.
func (o *UpdateModelMappingRequest) SetRetryOn429Count(v int32) {
	o.RetryOn429Count.Set(&v)
}
// SetRetryOn429CountNil sets the value for RetryOn429Count to be an explicit nil
func (o *UpdateModelMappingRequest) SetRetryOn429CountNil() {
	o.RetryOn429Count.Set(nil)
}

// UnsetRetryOn429Count ensures that no value is present for RetryOn429Count, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetRetryOn429Count() {
	o.RetryOn429Count.Unset()
}

// GetRetryOn429MaxWaitSecs returns the RetryOn429MaxWaitSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetRetryOn429MaxWaitSecs() int32 {
	if o == nil || IsNil(o.RetryOn429MaxWaitSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.RetryOn429MaxWaitSecs.Get()
}

// GetRetryOn429MaxWaitSecsOk returns a tuple with the RetryOn429MaxWaitSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetRetryOn429MaxWaitSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetryOn429MaxWaitSecs.Get(), o.RetryOn429MaxWaitSecs.IsSet()
}

// HasRetryOn429MaxWaitSecs returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasRetryOn429MaxWaitSecs() bool {
	if o != nil && o.RetryOn429MaxWaitSecs.IsSet() {
		return true
	}

	return false
}

// SetRetryOn429MaxWaitSecs gets a reference to the given NullableInt32 and assigns it to the RetryOn429MaxWaitSecs field.
func (o *UpdateModelMappingRequest) SetRetryOn429MaxWaitSecs(v int32) {
	o.RetryOn429MaxWaitSecs.Set(&v)
}
// SetRetryOn429MaxWaitSecsNil sets the value for RetryOn429MaxWaitSecs to be an explicit nil
func (o *UpdateModelMappingRequest) SetRetryOn429MaxWaitSecsNil() {
	o.RetryOn429MaxWaitSecs.Set(nil)
}

// UnsetRetryOn429MaxWaitSecs ensures that no value is present for RetryOn429MaxWaitSecs, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetRetryOn429MaxWaitSecs() {
	o.RetryOn429MaxWaitSecs.Unset()
}

// GetStreamIdleTimeoutSecs returns the StreamIdleTimeoutSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetStreamIdleTimeoutSecs() int32 {
	if o == nil || IsNil(o.StreamIdleTimeoutSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.StreamIdleTimeoutSecs.Get()
}

// GetStreamIdleTimeoutSecsOk returns a tuple with the StreamIdleTimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetStreamIdleTimeoutSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StreamIdleTimeoutSecs.Get(), o.StreamIdleTimeoutSecs.IsSet()
}

// HasStreamIdleTimeoutSecs returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasStreamIdleTimeoutSecs() bool {
	if o != nil && o.StreamIdleTimeoutSecs.IsSet() {
		return true
	}

	return false
}

// SetStreamIdleTimeoutSecs gets a reference to the given NullableInt32 and assigns it to the StreamIdleTimeoutSecs field.
func (o *UpdateModelMappingRequest) SetStreamIdleTimeoutSecs(v int32) {
	o.StreamIdleTimeoutSecs.Set(&v)
}
// SetStreamIdleTimeoutSecsNil sets the value for StreamIdleTimeoutSecs to be an explicit nil
func (o *UpdateModelMappingRequest) SetStreamIdleTimeoutSecsNil() {
	o.StreamIdleTimeoutSecs.Set(nil)
}

// UnsetStreamIdleTimeoutSecs ensures that no value is present for StreamIdleTimeoutSecs, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetStreamIdleTimeoutSecs() {
	o.StreamIdleTimeoutSecs.Unset()
}

// GetUpstreamModel returns the UpstreamModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateModelMappingRequest) GetUpstreamModel() string {
	if o == nil || IsNil(o.UpstreamModel.Get()) {
		var ret string
		return ret
	}
	return *o.UpstreamModel.Get()
}

// GetUpstreamModelOk returns a tuple with the UpstreamModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateModelMappingRequest) GetUpstreamModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpstreamModel.Get(), o.UpstreamModel.IsSet()
}

// HasUpstreamModel returns a boolean if a field has been set.
func (o *UpdateModelMappingRequest) HasUpstreamModel() bool {
	if o != nil && o.UpstreamModel.IsSet() {
		return true
	}

	return false
}

// SetUpstreamModel gets a reference to the given NullableString and assigns it to the UpstreamModel field.
func (o *UpdateModelMappingRequest) SetUpstreamModel(v string) {
	o.UpstreamModel.Set(&v)
}
// SetUpstreamModelNil sets the value for UpstreamModel to be an explicit nil
func (o *UpdateModelMappingRequest) SetUpstreamModelNil() {
	o.UpstreamModel.Set(nil)
}

// UnsetUpstreamModel ensures that no value is present for UpstreamModel, not even an explicit nil
func (o *UpdateModelMappingRequest) UnsetUpstreamModel() {
	o.UpstreamModel.Unset()
}

func (o UpdateModelMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateModelMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BareAlias.IsSet() {
		toSerialize["bare_alias"] = o.BareAlias.Get()
	}
	if o.ChangeNote.IsSet() {
		toSerialize["change_note"] = o.ChangeNote.Get()
	}
	if o.Enabled.IsSet() {
		toSerialize["enabled"] = o.Enabled.Get()
	}
	if o.ModelAlias.IsSet() {
		toSerialize["model_alias"] = o.ModelAlias.Get()
	}
	if o.Priority.IsSet() {
		toSerialize["priority"] = o.Priority.Get()
	}
	if o.RequestTimeoutSecs.IsSet() {
		toSerialize["request_timeout_secs"] = o.RequestTimeoutSecs.Get()
	}
	if o.RetryOn429Count.IsSet() {
		toSerialize["retry_on_429_count"] = o.RetryOn429Count.Get()
	}
	if o.RetryOn429MaxWaitSecs.IsSet() {
		toSerialize["retry_on_429_max_wait_secs"] = o.RetryOn429MaxWaitSecs.Get()
	}
	if o.StreamIdleTimeoutSecs.IsSet() {
		toSerialize["stream_idle_timeout_secs"] = o.StreamIdleTimeoutSecs.Get()
	}
	if o.UpstreamModel.IsSet() {
		toSerialize["upstream_model"] = o.UpstreamModel.Get()
	}
	return toSerialize, nil
}

type NullableUpdateModelMappingRequest struct {
	value *UpdateModelMappingRequest
	isSet bool
}

func (v NullableUpdateModelMappingRequest) Get() *UpdateModelMappingRequest {
	return v.value
}

func (v *NullableUpdateModelMappingRequest) Set(val *UpdateModelMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateModelMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateModelMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateModelMappingRequest(val *UpdateModelMappingRequest) *NullableUpdateModelMappingRequest {
	return &NullableUpdateModelMappingRequest{value: val, isSet: true}
}

func (v NullableUpdateModelMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateModelMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


