/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResolvedProtectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolvedProtectionResponse{}

// ResolvedProtectionResponse struct for ResolvedProtectionResponse
type ResolvedProtectionResponse struct {
	Rules []ResolvedProtectionRuleResponse `json:"rules"`
}

type _ResolvedProtectionResponse ResolvedProtectionResponse

// NewResolvedProtectionResponse instantiates a new ResolvedProtectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolvedProtectionResponse(rules []ResolvedProtectionRuleResponse) *ResolvedProtectionResponse {
	this := ResolvedProtectionResponse{}
	this.Rules = rules
	return &this
}

// NewResolvedProtectionResponseWithDefaults instantiates a new ResolvedProtectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolvedProtectionResponseWithDefaults() *ResolvedProtectionResponse {
	this := ResolvedProtectionResponse{}
	return &this
}

// GetRules returns the Rules field value
func (o *ResolvedProtectionResponse) GetRules() []ResolvedProtectionRuleResponse {
	if o == nil {
		var ret []ResolvedProtectionRuleResponse
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *ResolvedProtectionResponse) GetRulesOk() ([]ResolvedProtectionRuleResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules, true
}

// SetRules sets field value
func (o *ResolvedProtectionResponse) SetRules(v []ResolvedProtectionRuleResponse) {
	o.Rules = v
}

func (o ResolvedProtectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolvedProtectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rules"] = o.Rules
	return toSerialize, nil
}

func (o *ResolvedProtectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolvedProtectionResponse := _ResolvedProtectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResolvedProtectionResponse)

	if err != nil {
		return err
	}

	*o = ResolvedProtectionResponse(varResolvedProtectionResponse)

	return err
}

type NullableResolvedProtectionResponse struct {
	value *ResolvedProtectionResponse
	isSet bool
}

func (v NullableResolvedProtectionResponse) Get() *ResolvedProtectionResponse {
	return v.value
}

func (v *NullableResolvedProtectionResponse) Set(val *ResolvedProtectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResolvedProtectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResolvedProtectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolvedProtectionResponse(val *ResolvedProtectionResponse) *NullableResolvedProtectionResponse {
	return &NullableResolvedProtectionResponse{value: val, isSet: true}
}

func (v NullableResolvedProtectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolvedProtectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


