/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateConnectionRequest{}

// UpdateConnectionRequest struct for UpdateConnectionRequest
type UpdateConnectionRequest struct {
	ApiKey NullableString `json:"api_key,omitempty"`
	AuthType NullableString `json:"auth_type,omitempty"`
	BaseUrl NullableString `json:"base_url,omitempty"`
	// Optional free-text note explaining why this edit was made. Omitting it clears any previous note, which is deliberate: the note describes the latest change, so keeping the old one would explain the wrong edit.
	ChangeNote NullableString `json:"change_note,omitempty"`
	Credentials interface{} `json:"credentials,omitempty"`
	Name NullableString `json:"name,omitempty"`
	Settings interface{} `json:"settings,omitempty"`
}

// NewUpdateConnectionRequest instantiates a new UpdateConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConnectionRequest() *UpdateConnectionRequest {
	this := UpdateConnectionRequest{}
	return &this
}

// NewUpdateConnectionRequestWithDefaults instantiates a new UpdateConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConnectionRequestWithDefaults() *UpdateConnectionRequest {
	this := UpdateConnectionRequest{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConnectionRequest) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey.Get()) {
		var ret string
		return ret
	}
	return *o.ApiKey.Get()
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConnectionRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiKey.Get(), o.ApiKey.IsSet()
}

// HasApiKey returns a boolean if a field has been set.
func (o *UpdateConnectionRequest) HasApiKey() bool {
	if o != nil && o.ApiKey.IsSet() {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given NullableString and assigns it to the ApiKey field.
func (o *UpdateConnectionRequest) SetApiKey(v string) {
	o.ApiKey.Set(&v)
}
// SetApiKeyNil sets the value for ApiKey to be an explicit nil
func (o *UpdateConnectionRequest) SetApiKeyNil() {
	o.ApiKey.Set(nil)
}

// UnsetApiKey ensures that no value is present for ApiKey, not even an explicit nil
func (o *UpdateConnectionRequest) UnsetApiKey() {
	o.ApiKey.Unset()
}

// GetAuthType returns the AuthType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConnectionRequest) GetAuthType() string {
	if o == nil || IsNil(o.AuthType.Get()) {
		var ret string
		return ret
	}
	return *o.AuthType.Get()
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConnectionRequest) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthType.Get(), o.AuthType.IsSet()
}

// HasAuthType returns a boolean if a field has been set.
func (o *UpdateConnectionRequest) HasAuthType() bool {
	if o != nil && o.AuthType.IsSet() {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given NullableString and assigns it to the AuthType field.
func (o *UpdateConnectionRequest) SetAuthType(v string) {
	o.AuthType.Set(&v)
}
// SetAuthTypeNil sets the value for AuthType to be an explicit nil
func (o *UpdateConnectionRequest) SetAuthTypeNil() {
	o.AuthType.Set(nil)
}

// UnsetAuthType ensures that no value is present for AuthType, not even an explicit nil
func (o *UpdateConnectionRequest) UnsetAuthType() {
	o.AuthType.Unset()
}

// GetBaseUrl returns the BaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConnectionRequest) GetBaseUrl() string {
	if o == nil || IsNil(o.BaseUrl.Get()) {
		var ret string
		return ret
	}
	return *o.BaseUrl.Get()
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConnectionRequest) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseUrl.Get(), o.BaseUrl.IsSet()
}

// HasBaseUrl returns a boolean if a field has been set.
func (o *UpdateConnectionRequest) HasBaseUrl() bool {
	if o != nil && o.BaseUrl.IsSet() {
		return true
	}

	return false
}

// SetBaseUrl gets a reference to the given NullableString and assigns it to the BaseUrl field.
func (o *UpdateConnectionRequest) SetBaseUrl(v string) {
	o.BaseUrl.Set(&v)
}
// SetBaseUrlNil sets the value for BaseUrl to be an explicit nil
func (o *UpdateConnectionRequest) SetBaseUrlNil() {
	o.BaseUrl.Set(nil)
}

// UnsetBaseUrl ensures that no value is present for BaseUrl, not even an explicit nil
func (o *UpdateConnectionRequest) UnsetBaseUrl() {
	o.BaseUrl.Unset()
}

// GetChangeNote returns the ChangeNote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConnectionRequest) GetChangeNote() string {
	if o == nil || IsNil(o.ChangeNote.Get()) {
		var ret string
		return ret
	}
	return *o.ChangeNote.Get()
}

// GetChangeNoteOk returns a tuple with the ChangeNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConnectionRequest) GetChangeNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeNote.Get(), o.ChangeNote.IsSet()
}

// HasChangeNote returns a boolean if a field has been set.
func (o *UpdateConnectionRequest) HasChangeNote() bool {
	if o != nil && o.ChangeNote.IsSet() {
		return true
	}

	return false
}

// SetChangeNote gets a reference to the given NullableString and assigns it to the ChangeNote field.
func (o *UpdateConnectionRequest) SetChangeNote(v string) {
	o.ChangeNote.Set(&v)
}
// SetChangeNoteNil sets the value for ChangeNote to be an explicit nil
func (o *UpdateConnectionRequest) SetChangeNoteNil() {
	o.ChangeNote.Set(nil)
}

// UnsetChangeNote ensures that no value is present for ChangeNote, not even an explicit nil
func (o *UpdateConnectionRequest) UnsetChangeNote() {
	o.ChangeNote.Unset()
}

// GetCredentials returns the Credentials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConnectionRequest) GetCredentials() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConnectionRequest) GetCredentialsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return &o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *UpdateConnectionRequest) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given interface{} and assigns it to the Credentials field.
func (o *UpdateConnectionRequest) SetCredentials(v interface{}) {
	o.Credentials = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConnectionRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConnectionRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateConnectionRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateConnectionRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateConnectionRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateConnectionRequest) UnsetName() {
	o.Name.Unset()
}

// GetSettings returns the Settings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConnectionRequest) GetSettings() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConnectionRequest) GetSettingsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return &o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *UpdateConnectionRequest) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given interface{} and assigns it to the Settings field.
func (o *UpdateConnectionRequest) SetSettings(v interface{}) {
	o.Settings = v
}

func (o UpdateConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKey.IsSet() {
		toSerialize["api_key"] = o.ApiKey.Get()
	}
	if o.AuthType.IsSet() {
		toSerialize["auth_type"] = o.AuthType.Get()
	}
	if o.BaseUrl.IsSet() {
		toSerialize["base_url"] = o.BaseUrl.Get()
	}
	if o.ChangeNote.IsSet() {
		toSerialize["change_note"] = o.ChangeNote.Get()
	}
	if o.Credentials != nil {
		toSerialize["credentials"] = o.Credentials
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Settings != nil {
		toSerialize["settings"] = o.Settings
	}
	return toSerialize, nil
}

type NullableUpdateConnectionRequest struct {
	value *UpdateConnectionRequest
	isSet bool
}

func (v NullableUpdateConnectionRequest) Get() *UpdateConnectionRequest {
	return v.value
}

func (v *NullableUpdateConnectionRequest) Set(val *UpdateConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConnectionRequest(val *UpdateConnectionRequest) *NullableUpdateConnectionRequest {
	return &NullableUpdateConnectionRequest{value: val, isSet: true}
}

func (v NullableUpdateConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


