/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEnforcementPolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnforcementPolicyRequest{}

// CreateEnforcementPolicyRequest struct for CreateEnforcementPolicyRequest
type CreateEnforcementPolicyRequest struct {
	Action string `json:"action"`
	DetectionEngineIds []string `json:"detection_engine_ids,omitempty"`
	DryRun *bool `json:"dry_run,omitempty"`
	// Partial-redaction shape; only valid with `POLICY_ACTION_MASK`.
	MaskFormat NullableMaskFormat `json:"mask_format,omitempty"`
	McpTargets []EnforcementPolicyMcpTargetRequest `json:"mcp_targets,omitempty"`
	ModelAlias NullableString `json:"model_alias,omitempty"`
	Name string `json:"name"`
	Principals []EnforcementPolicyPrincipalRequest `json:"principals,omitempty"`
	Priority NullableInt32 `json:"priority,omitempty"`
	ProviderIds []string `json:"provider_ids,omitempty"`
	RuntimeStage NullableString `json:"runtime_stage,omitempty"`
	TargetKind NullableString `json:"target_kind,omitempty"`
}

type _CreateEnforcementPolicyRequest CreateEnforcementPolicyRequest

// NewCreateEnforcementPolicyRequest instantiates a new CreateEnforcementPolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnforcementPolicyRequest(action string, name string) *CreateEnforcementPolicyRequest {
	this := CreateEnforcementPolicyRequest{}
	this.Action = action
	this.Name = name
	return &this
}

// NewCreateEnforcementPolicyRequestWithDefaults instantiates a new CreateEnforcementPolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnforcementPolicyRequestWithDefaults() *CreateEnforcementPolicyRequest {
	this := CreateEnforcementPolicyRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *CreateEnforcementPolicyRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CreateEnforcementPolicyRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CreateEnforcementPolicyRequest) SetAction(v string) {
	o.Action = v
}

// GetDetectionEngineIds returns the DetectionEngineIds field value if set, zero value otherwise.
func (o *CreateEnforcementPolicyRequest) GetDetectionEngineIds() []string {
	if o == nil || IsNil(o.DetectionEngineIds) {
		var ret []string
		return ret
	}
	return o.DetectionEngineIds
}

// GetDetectionEngineIdsOk returns a tuple with the DetectionEngineIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnforcementPolicyRequest) GetDetectionEngineIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DetectionEngineIds) {
		return nil, false
	}
	return o.DetectionEngineIds, true
}

// HasDetectionEngineIds returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasDetectionEngineIds() bool {
	if o != nil && !IsNil(o.DetectionEngineIds) {
		return true
	}

	return false
}

// SetDetectionEngineIds gets a reference to the given []string and assigns it to the DetectionEngineIds field.
func (o *CreateEnforcementPolicyRequest) SetDetectionEngineIds(v []string) {
	o.DetectionEngineIds = v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *CreateEnforcementPolicyRequest) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnforcementPolicyRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *CreateEnforcementPolicyRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetMaskFormat returns the MaskFormat field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEnforcementPolicyRequest) GetMaskFormat() MaskFormat {
	if o == nil || IsNil(o.MaskFormat.Get()) {
		var ret MaskFormat
		return ret
	}
	return *o.MaskFormat.Get()
}

// GetMaskFormatOk returns a tuple with the MaskFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEnforcementPolicyRequest) GetMaskFormatOk() (*MaskFormat, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaskFormat.Get(), o.MaskFormat.IsSet()
}

// HasMaskFormat returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasMaskFormat() bool {
	if o != nil && o.MaskFormat.IsSet() {
		return true
	}

	return false
}

// SetMaskFormat gets a reference to the given NullableMaskFormat and assigns it to the MaskFormat field.
func (o *CreateEnforcementPolicyRequest) SetMaskFormat(v MaskFormat) {
	o.MaskFormat.Set(&v)
}
// SetMaskFormatNil sets the value for MaskFormat to be an explicit nil
func (o *CreateEnforcementPolicyRequest) SetMaskFormatNil() {
	o.MaskFormat.Set(nil)
}

// UnsetMaskFormat ensures that no value is present for MaskFormat, not even an explicit nil
func (o *CreateEnforcementPolicyRequest) UnsetMaskFormat() {
	o.MaskFormat.Unset()
}

// GetMcpTargets returns the McpTargets field value if set, zero value otherwise.
func (o *CreateEnforcementPolicyRequest) GetMcpTargets() []EnforcementPolicyMcpTargetRequest {
	if o == nil || IsNil(o.McpTargets) {
		var ret []EnforcementPolicyMcpTargetRequest
		return ret
	}
	return o.McpTargets
}

// GetMcpTargetsOk returns a tuple with the McpTargets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnforcementPolicyRequest) GetMcpTargetsOk() ([]EnforcementPolicyMcpTargetRequest, bool) {
	if o == nil || IsNil(o.McpTargets) {
		return nil, false
	}
	return o.McpTargets, true
}

// HasMcpTargets returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasMcpTargets() bool {
	if o != nil && !IsNil(o.McpTargets) {
		return true
	}

	return false
}

// SetMcpTargets gets a reference to the given []EnforcementPolicyMcpTargetRequest and assigns it to the McpTargets field.
func (o *CreateEnforcementPolicyRequest) SetMcpTargets(v []EnforcementPolicyMcpTargetRequest) {
	o.McpTargets = v
}

// GetModelAlias returns the ModelAlias field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEnforcementPolicyRequest) GetModelAlias() string {
	if o == nil || IsNil(o.ModelAlias.Get()) {
		var ret string
		return ret
	}
	return *o.ModelAlias.Get()
}

// GetModelAliasOk returns a tuple with the ModelAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEnforcementPolicyRequest) GetModelAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModelAlias.Get(), o.ModelAlias.IsSet()
}

// HasModelAlias returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasModelAlias() bool {
	if o != nil && o.ModelAlias.IsSet() {
		return true
	}

	return false
}

// SetModelAlias gets a reference to the given NullableString and assigns it to the ModelAlias field.
func (o *CreateEnforcementPolicyRequest) SetModelAlias(v string) {
	o.ModelAlias.Set(&v)
}
// SetModelAliasNil sets the value for ModelAlias to be an explicit nil
func (o *CreateEnforcementPolicyRequest) SetModelAliasNil() {
	o.ModelAlias.Set(nil)
}

// UnsetModelAlias ensures that no value is present for ModelAlias, not even an explicit nil
func (o *CreateEnforcementPolicyRequest) UnsetModelAlias() {
	o.ModelAlias.Unset()
}

// GetName returns the Name field value
func (o *CreateEnforcementPolicyRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEnforcementPolicyRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEnforcementPolicyRequest) SetName(v string) {
	o.Name = v
}

// GetPrincipals returns the Principals field value if set, zero value otherwise.
func (o *CreateEnforcementPolicyRequest) GetPrincipals() []EnforcementPolicyPrincipalRequest {
	if o == nil || IsNil(o.Principals) {
		var ret []EnforcementPolicyPrincipalRequest
		return ret
	}
	return o.Principals
}

// GetPrincipalsOk returns a tuple with the Principals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnforcementPolicyRequest) GetPrincipalsOk() ([]EnforcementPolicyPrincipalRequest, bool) {
	if o == nil || IsNil(o.Principals) {
		return nil, false
	}
	return o.Principals, true
}

// HasPrincipals returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasPrincipals() bool {
	if o != nil && !IsNil(o.Principals) {
		return true
	}

	return false
}

// SetPrincipals gets a reference to the given []EnforcementPolicyPrincipalRequest and assigns it to the Principals field.
func (o *CreateEnforcementPolicyRequest) SetPrincipals(v []EnforcementPolicyPrincipalRequest) {
	o.Principals = v
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEnforcementPolicyRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority.Get()) {
		var ret int32
		return ret
	}
	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEnforcementPolicyRequest) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasPriority() bool {
	if o != nil && o.Priority.IsSet() {
		return true
	}

	return false
}

// SetPriority gets a reference to the given NullableInt32 and assigns it to the Priority field.
func (o *CreateEnforcementPolicyRequest) SetPriority(v int32) {
	o.Priority.Set(&v)
}
// SetPriorityNil sets the value for Priority to be an explicit nil
func (o *CreateEnforcementPolicyRequest) SetPriorityNil() {
	o.Priority.Set(nil)
}

// UnsetPriority ensures that no value is present for Priority, not even an explicit nil
func (o *CreateEnforcementPolicyRequest) UnsetPriority() {
	o.Priority.Unset()
}

// GetProviderIds returns the ProviderIds field value if set, zero value otherwise.
func (o *CreateEnforcementPolicyRequest) GetProviderIds() []string {
	if o == nil || IsNil(o.ProviderIds) {
		var ret []string
		return ret
	}
	return o.ProviderIds
}

// GetProviderIdsOk returns a tuple with the ProviderIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnforcementPolicyRequest) GetProviderIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProviderIds) {
		return nil, false
	}
	return o.ProviderIds, true
}

// HasProviderIds returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasProviderIds() bool {
	if o != nil && !IsNil(o.ProviderIds) {
		return true
	}

	return false
}

// SetProviderIds gets a reference to the given []string and assigns it to the ProviderIds field.
func (o *CreateEnforcementPolicyRequest) SetProviderIds(v []string) {
	o.ProviderIds = v
}

// GetRuntimeStage returns the RuntimeStage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEnforcementPolicyRequest) GetRuntimeStage() string {
	if o == nil || IsNil(o.RuntimeStage.Get()) {
		var ret string
		return ret
	}
	return *o.RuntimeStage.Get()
}

// GetRuntimeStageOk returns a tuple with the RuntimeStage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEnforcementPolicyRequest) GetRuntimeStageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuntimeStage.Get(), o.RuntimeStage.IsSet()
}

// HasRuntimeStage returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasRuntimeStage() bool {
	if o != nil && o.RuntimeStage.IsSet() {
		return true
	}

	return false
}

// SetRuntimeStage gets a reference to the given NullableString and assigns it to the RuntimeStage field.
func (o *CreateEnforcementPolicyRequest) SetRuntimeStage(v string) {
	o.RuntimeStage.Set(&v)
}
// SetRuntimeStageNil sets the value for RuntimeStage to be an explicit nil
func (o *CreateEnforcementPolicyRequest) SetRuntimeStageNil() {
	o.RuntimeStage.Set(nil)
}

// UnsetRuntimeStage ensures that no value is present for RuntimeStage, not even an explicit nil
func (o *CreateEnforcementPolicyRequest) UnsetRuntimeStage() {
	o.RuntimeStage.Unset()
}

// GetTargetKind returns the TargetKind field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEnforcementPolicyRequest) GetTargetKind() string {
	if o == nil || IsNil(o.TargetKind.Get()) {
		var ret string
		return ret
	}
	return *o.TargetKind.Get()
}

// GetTargetKindOk returns a tuple with the TargetKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEnforcementPolicyRequest) GetTargetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetKind.Get(), o.TargetKind.IsSet()
}

// HasTargetKind returns a boolean if a field has been set.
func (o *CreateEnforcementPolicyRequest) HasTargetKind() bool {
	if o != nil && o.TargetKind.IsSet() {
		return true
	}

	return false
}

// SetTargetKind gets a reference to the given NullableString and assigns it to the TargetKind field.
func (o *CreateEnforcementPolicyRequest) SetTargetKind(v string) {
	o.TargetKind.Set(&v)
}
// SetTargetKindNil sets the value for TargetKind to be an explicit nil
func (o *CreateEnforcementPolicyRequest) SetTargetKindNil() {
	o.TargetKind.Set(nil)
}

// UnsetTargetKind ensures that no value is present for TargetKind, not even an explicit nil
func (o *CreateEnforcementPolicyRequest) UnsetTargetKind() {
	o.TargetKind.Unset()
}

func (o CreateEnforcementPolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnforcementPolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.DetectionEngineIds) {
		toSerialize["detection_engine_ids"] = o.DetectionEngineIds
	}
	if !IsNil(o.DryRun) {
		toSerialize["dry_run"] = o.DryRun
	}
	if o.MaskFormat.IsSet() {
		toSerialize["mask_format"] = o.MaskFormat.Get()
	}
	if !IsNil(o.McpTargets) {
		toSerialize["mcp_targets"] = o.McpTargets
	}
	if o.ModelAlias.IsSet() {
		toSerialize["model_alias"] = o.ModelAlias.Get()
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Principals) {
		toSerialize["principals"] = o.Principals
	}
	if o.Priority.IsSet() {
		toSerialize["priority"] = o.Priority.Get()
	}
	if !IsNil(o.ProviderIds) {
		toSerialize["provider_ids"] = o.ProviderIds
	}
	if o.RuntimeStage.IsSet() {
		toSerialize["runtime_stage"] = o.RuntimeStage.Get()
	}
	if o.TargetKind.IsSet() {
		toSerialize["target_kind"] = o.TargetKind.Get()
	}
	return toSerialize, nil
}

func (o *CreateEnforcementPolicyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEnforcementPolicyRequest := _CreateEnforcementPolicyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEnforcementPolicyRequest)

	if err != nil {
		return err
	}

	*o = CreateEnforcementPolicyRequest(varCreateEnforcementPolicyRequest)

	return err
}

type NullableCreateEnforcementPolicyRequest struct {
	value *CreateEnforcementPolicyRequest
	isSet bool
}

func (v NullableCreateEnforcementPolicyRequest) Get() *CreateEnforcementPolicyRequest {
	return v.value
}

func (v *NullableCreateEnforcementPolicyRequest) Set(val *CreateEnforcementPolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnforcementPolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnforcementPolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnforcementPolicyRequest(val *CreateEnforcementPolicyRequest) *NullableCreateEnforcementPolicyRequest {
	return &NullableCreateEnforcementPolicyRequest{value: val, isSet: true}
}

func (v NullableCreateEnforcementPolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnforcementPolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


