/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArchivePricingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArchivePricingResponse{}

// ArchivePricingResponse `DELETE /admin/model-pricing/{id}` — archiving a pricing rule is not a plain delete, so the response says what it actually did.
type ArchivePricingResponse struct {
	// Whether an active version was archived. A count would be wrong: the handler sets this from a boolean.
	Archived bool `json:"archived"`
	// How many scheduled future versions were cancelled.
	CancelledScheduled int64 `json:"cancelled_scheduled"`
	// Always true.
	Deleted bool `json:"deleted"`
	// Which action was taken, e.g. whether a scheduled change was cancelled rather than an active rule archived.
	Mode string `json:"mode"`
}

type _ArchivePricingResponse ArchivePricingResponse

// NewArchivePricingResponse instantiates a new ArchivePricingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArchivePricingResponse(archived bool, cancelledScheduled int64, deleted bool, mode string) *ArchivePricingResponse {
	this := ArchivePricingResponse{}
	this.Archived = archived
	this.CancelledScheduled = cancelledScheduled
	this.Deleted = deleted
	this.Mode = mode
	return &this
}

// NewArchivePricingResponseWithDefaults instantiates a new ArchivePricingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArchivePricingResponseWithDefaults() *ArchivePricingResponse {
	this := ArchivePricingResponse{}
	return &this
}

// GetArchived returns the Archived field value
func (o *ArchivePricingResponse) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *ArchivePricingResponse) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *ArchivePricingResponse) SetArchived(v bool) {
	o.Archived = v
}

// GetCancelledScheduled returns the CancelledScheduled field value
func (o *ArchivePricingResponse) GetCancelledScheduled() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CancelledScheduled
}

// GetCancelledScheduledOk returns a tuple with the CancelledScheduled field value
// and a boolean to check if the value has been set.
func (o *ArchivePricingResponse) GetCancelledScheduledOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancelledScheduled, true
}

// SetCancelledScheduled sets field value
func (o *ArchivePricingResponse) SetCancelledScheduled(v int64) {
	o.CancelledScheduled = v
}

// GetDeleted returns the Deleted field value
func (o *ArchivePricingResponse) GetDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value
// and a boolean to check if the value has been set.
func (o *ArchivePricingResponse) GetDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deleted, true
}

// SetDeleted sets field value
func (o *ArchivePricingResponse) SetDeleted(v bool) {
	o.Deleted = v
}

// GetMode returns the Mode field value
func (o *ArchivePricingResponse) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *ArchivePricingResponse) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *ArchivePricingResponse) SetMode(v string) {
	o.Mode = v
}

func (o ArchivePricingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArchivePricingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["archived"] = o.Archived
	toSerialize["cancelled_scheduled"] = o.CancelledScheduled
	toSerialize["deleted"] = o.Deleted
	toSerialize["mode"] = o.Mode
	return toSerialize, nil
}

func (o *ArchivePricingResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"archived",
		"cancelled_scheduled",
		"deleted",
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArchivePricingResponse := _ArchivePricingResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArchivePricingResponse)

	if err != nil {
		return err
	}

	*o = ArchivePricingResponse(varArchivePricingResponse)

	return err
}

type NullableArchivePricingResponse struct {
	value *ArchivePricingResponse
	isSet bool
}

func (v NullableArchivePricingResponse) Get() *ArchivePricingResponse {
	return v.value
}

func (v *NullableArchivePricingResponse) Set(val *ArchivePricingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableArchivePricingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableArchivePricingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArchivePricingResponse(val *ArchivePricingResponse) *NullableArchivePricingResponse {
	return &NullableArchivePricingResponse{value: val, isSet: true}
}

func (v NullableArchivePricingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArchivePricingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


