/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// BudgetPeriod How often a budget's counter resets.  **Every period boundary is UTC**, with no per-org configuration: `key_suffix` formats `Utc::now()`, so `Daily` rolls at 00:00 UTC, `Weekly` at Monday 00:00 UTC (ISO-8601 week), and `Monthly` on the 1st at 00:00 UTC. An admin in a western timezone therefore sees their \"daily\" cap reset in the afternoon — [`Self::period_end`] exists so the UI can say so rather than leave them to infer it (BCP-4204).
type BudgetPeriod string

// List of BudgetPeriod
const (
	BUDGETPERIOD_DAILY BudgetPeriod = "daily"
	BUDGETPERIOD_WEEKLY BudgetPeriod = "weekly"
	BUDGETPERIOD_MONTHLY BudgetPeriod = "monthly"
)

// All allowed values of BudgetPeriod enum
var AllowedBudgetPeriodEnumValues = []BudgetPeriod{
	"daily",
	"weekly",
	"monthly",
}

func (v *BudgetPeriod) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BudgetPeriod(value)
	for _, existing := range AllowedBudgetPeriodEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BudgetPeriod", value)
}

// NewBudgetPeriodFromValue returns a pointer to a valid BudgetPeriod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBudgetPeriodFromValue(v string) (*BudgetPeriod, error) {
	ev := BudgetPeriod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BudgetPeriod: valid values are %v", v, AllowedBudgetPeriodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BudgetPeriod) IsValid() bool {
	for _, existing := range AllowedBudgetPeriodEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BudgetPeriod value
func (v BudgetPeriod) Ptr() *BudgetPeriod {
	return &v
}

type NullableBudgetPeriod struct {
	value *BudgetPeriod
	isSet bool
}

func (v NullableBudgetPeriod) Get() *BudgetPeriod {
	return v.value
}

func (v *NullableBudgetPeriod) Set(val *BudgetPeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableBudgetPeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableBudgetPeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBudgetPeriod(val *BudgetPeriod) *NullableBudgetPeriod {
	return &NullableBudgetPeriod{value: val, isSet: true}
}

func (v NullableBudgetPeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBudgetPeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

