/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefaultSetupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSetupRequest{}

// DefaultSetupRequest struct for DefaultSetupRequest
type DefaultSetupRequest struct {
	Client string `json:"client"`
	ProviderId string `json:"provider_id"`
}

type _DefaultSetupRequest DefaultSetupRequest

// NewDefaultSetupRequest instantiates a new DefaultSetupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSetupRequest(client string, providerId string) *DefaultSetupRequest {
	this := DefaultSetupRequest{}
	this.Client = client
	this.ProviderId = providerId
	return &this
}

// NewDefaultSetupRequestWithDefaults instantiates a new DefaultSetupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSetupRequestWithDefaults() *DefaultSetupRequest {
	this := DefaultSetupRequest{}
	return &this
}

// GetClient returns the Client field value
func (o *DefaultSetupRequest) GetClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Client
}

// GetClientOk returns a tuple with the Client field value
// and a boolean to check if the value has been set.
func (o *DefaultSetupRequest) GetClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Client, true
}

// SetClient sets field value
func (o *DefaultSetupRequest) SetClient(v string) {
	o.Client = v
}

// GetProviderId returns the ProviderId field value
func (o *DefaultSetupRequest) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *DefaultSetupRequest) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *DefaultSetupRequest) SetProviderId(v string) {
	o.ProviderId = v
}

func (o DefaultSetupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSetupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client"] = o.Client
	toSerialize["provider_id"] = o.ProviderId
	return toSerialize, nil
}

func (o *DefaultSetupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client",
		"provider_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSetupRequest := _DefaultSetupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSetupRequest)

	if err != nil {
		return err
	}

	*o = DefaultSetupRequest(varDefaultSetupRequest)

	return err
}

type NullableDefaultSetupRequest struct {
	value *DefaultSetupRequest
	isSet bool
}

func (v NullableDefaultSetupRequest) Get() *DefaultSetupRequest {
	return v.value
}

func (v *NullableDefaultSetupRequest) Set(val *DefaultSetupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSetupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSetupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSetupRequest(val *DefaultSetupRequest) *NullableDefaultSetupRequest {
	return &NullableDefaultSetupRequest{value: val, isSet: true}
}

func (v NullableDefaultSetupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSetupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


