/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelAccessTargetOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAccessTargetOneOf3{}

// ModelAccessTargetOneOf3 Match the (provider, model alias) combination — used to allow/deny a specific model only when it goes through a specific provider.
type ModelAccessTargetOneOf3 struct {
	Kind string `json:"kind"`
	Model string `json:"model"`
	ProviderId string `json:"provider_id"`
}

type _ModelAccessTargetOneOf3 ModelAccessTargetOneOf3

// NewModelAccessTargetOneOf3 instantiates a new ModelAccessTargetOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAccessTargetOneOf3(kind string, model string, providerId string) *ModelAccessTargetOneOf3 {
	this := ModelAccessTargetOneOf3{}
	this.Kind = kind
	this.Model = model
	this.ProviderId = providerId
	return &this
}

// NewModelAccessTargetOneOf3WithDefaults instantiates a new ModelAccessTargetOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAccessTargetOneOf3WithDefaults() *ModelAccessTargetOneOf3 {
	this := ModelAccessTargetOneOf3{}
	return &this
}

// GetKind returns the Kind field value
func (o *ModelAccessTargetOneOf3) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ModelAccessTargetOneOf3) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ModelAccessTargetOneOf3) SetKind(v string) {
	o.Kind = v
}

// GetModel returns the Model field value
func (o *ModelAccessTargetOneOf3) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *ModelAccessTargetOneOf3) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *ModelAccessTargetOneOf3) SetModel(v string) {
	o.Model = v
}

// GetProviderId returns the ProviderId field value
func (o *ModelAccessTargetOneOf3) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *ModelAccessTargetOneOf3) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *ModelAccessTargetOneOf3) SetProviderId(v string) {
	o.ProviderId = v
}

func (o ModelAccessTargetOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAccessTargetOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["model"] = o.Model
	toSerialize["provider_id"] = o.ProviderId
	return toSerialize, nil
}

func (o *ModelAccessTargetOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"model",
		"provider_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelAccessTargetOneOf3 := _ModelAccessTargetOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelAccessTargetOneOf3)

	if err != nil {
		return err
	}

	*o = ModelAccessTargetOneOf3(varModelAccessTargetOneOf3)

	return err
}

type NullableModelAccessTargetOneOf3 struct {
	value *ModelAccessTargetOneOf3
	isSet bool
}

func (v NullableModelAccessTargetOneOf3) Get() *ModelAccessTargetOneOf3 {
	return v.value
}

func (v *NullableModelAccessTargetOneOf3) Set(val *ModelAccessTargetOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAccessTargetOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAccessTargetOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAccessTargetOneOf3(val *ModelAccessTargetOneOf3) *NullableModelAccessTargetOneOf3 {
	return &NullableModelAccessTargetOneOf3{value: val, isSet: true}
}

func (v NullableModelAccessTargetOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAccessTargetOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


