/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProviderConnectionResponseOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderConnectionResponseOneOf4{}

// ProviderConnectionResponseOneOf4 struct for ProviderConnectionResponseOneOf4
type ProviderConnectionResponseOneOf4 struct {
	ApiVersion string `json:"api_version"`
	Endpoint string `json:"endpoint"`
	HasApiKey bool `json:"has_api_key"`
	Language string `json:"language"`
	OrgId string `json:"org_id"`
	Provider string `json:"provider"`
}

type _ProviderConnectionResponseOneOf4 ProviderConnectionResponseOneOf4

// NewProviderConnectionResponseOneOf4 instantiates a new ProviderConnectionResponseOneOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderConnectionResponseOneOf4(apiVersion string, endpoint string, hasApiKey bool, language string, orgId string, provider string) *ProviderConnectionResponseOneOf4 {
	this := ProviderConnectionResponseOneOf4{}
	this.ApiVersion = apiVersion
	this.Endpoint = endpoint
	this.HasApiKey = hasApiKey
	this.Language = language
	this.OrgId = orgId
	this.Provider = provider
	return &this
}

// NewProviderConnectionResponseOneOf4WithDefaults instantiates a new ProviderConnectionResponseOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderConnectionResponseOneOf4WithDefaults() *ProviderConnectionResponseOneOf4 {
	this := ProviderConnectionResponseOneOf4{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *ProviderConnectionResponseOneOf4) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf4) GetApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *ProviderConnectionResponseOneOf4) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetEndpoint returns the Endpoint field value
func (o *ProviderConnectionResponseOneOf4) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf4) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *ProviderConnectionResponseOneOf4) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetHasApiKey returns the HasApiKey field value
func (o *ProviderConnectionResponseOneOf4) GetHasApiKey() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasApiKey
}

// GetHasApiKeyOk returns a tuple with the HasApiKey field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf4) GetHasApiKeyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasApiKey, true
}

// SetHasApiKey sets field value
func (o *ProviderConnectionResponseOneOf4) SetHasApiKey(v bool) {
	o.HasApiKey = v
}

// GetLanguage returns the Language field value
func (o *ProviderConnectionResponseOneOf4) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf4) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *ProviderConnectionResponseOneOf4) SetLanguage(v string) {
	o.Language = v
}

// GetOrgId returns the OrgId field value
func (o *ProviderConnectionResponseOneOf4) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf4) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ProviderConnectionResponseOneOf4) SetOrgId(v string) {
	o.OrgId = v
}

// GetProvider returns the Provider field value
func (o *ProviderConnectionResponseOneOf4) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf4) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ProviderConnectionResponseOneOf4) SetProvider(v string) {
	o.Provider = v
}

func (o ProviderConnectionResponseOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderConnectionResponseOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_version"] = o.ApiVersion
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["has_api_key"] = o.HasApiKey
	toSerialize["language"] = o.Language
	toSerialize["org_id"] = o.OrgId
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *ProviderConnectionResponseOneOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_version",
		"endpoint",
		"has_api_key",
		"language",
		"org_id",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderConnectionResponseOneOf4 := _ProviderConnectionResponseOneOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderConnectionResponseOneOf4)

	if err != nil {
		return err
	}

	*o = ProviderConnectionResponseOneOf4(varProviderConnectionResponseOneOf4)

	return err
}

type NullableProviderConnectionResponseOneOf4 struct {
	value *ProviderConnectionResponseOneOf4
	isSet bool
}

func (v NullableProviderConnectionResponseOneOf4) Get() *ProviderConnectionResponseOneOf4 {
	return v.value
}

func (v *NullableProviderConnectionResponseOneOf4) Set(val *ProviderConnectionResponseOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderConnectionResponseOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderConnectionResponseOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderConnectionResponseOneOf4(val *ProviderConnectionResponseOneOf4) *NullableProviderConnectionResponseOneOf4 {
	return &NullableProviderConnectionResponseOneOf4{value: val, isSet: true}
}

func (v NullableProviderConnectionResponseOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderConnectionResponseOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


