/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProviderConnectionResponseOneOf6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderConnectionResponseOneOf6{}

// ProviderConnectionResponseOneOf6 struct for ProviderConnectionResponseOneOf6
type ProviderConnectionResponseOneOf6 struct {
	ApiVersion string `json:"api_version"`
	Endpoint string `json:"endpoint"`
	HasApiKey bool `json:"has_api_key"`
	OrgId string `json:"org_id"`
	SeverityThreshold int32 `json:"severity_threshold"`
	Provider string `json:"provider"`
}

type _ProviderConnectionResponseOneOf6 ProviderConnectionResponseOneOf6

// NewProviderConnectionResponseOneOf6 instantiates a new ProviderConnectionResponseOneOf6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderConnectionResponseOneOf6(apiVersion string, endpoint string, hasApiKey bool, orgId string, severityThreshold int32, provider string) *ProviderConnectionResponseOneOf6 {
	this := ProviderConnectionResponseOneOf6{}
	this.ApiVersion = apiVersion
	this.Endpoint = endpoint
	this.HasApiKey = hasApiKey
	this.OrgId = orgId
	this.SeverityThreshold = severityThreshold
	this.Provider = provider
	return &this
}

// NewProviderConnectionResponseOneOf6WithDefaults instantiates a new ProviderConnectionResponseOneOf6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderConnectionResponseOneOf6WithDefaults() *ProviderConnectionResponseOneOf6 {
	this := ProviderConnectionResponseOneOf6{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *ProviderConnectionResponseOneOf6) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf6) GetApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *ProviderConnectionResponseOneOf6) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetEndpoint returns the Endpoint field value
func (o *ProviderConnectionResponseOneOf6) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf6) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *ProviderConnectionResponseOneOf6) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetHasApiKey returns the HasApiKey field value
func (o *ProviderConnectionResponseOneOf6) GetHasApiKey() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasApiKey
}

// GetHasApiKeyOk returns a tuple with the HasApiKey field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf6) GetHasApiKeyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasApiKey, true
}

// SetHasApiKey sets field value
func (o *ProviderConnectionResponseOneOf6) SetHasApiKey(v bool) {
	o.HasApiKey = v
}

// GetOrgId returns the OrgId field value
func (o *ProviderConnectionResponseOneOf6) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf6) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ProviderConnectionResponseOneOf6) SetOrgId(v string) {
	o.OrgId = v
}

// GetSeverityThreshold returns the SeverityThreshold field value
func (o *ProviderConnectionResponseOneOf6) GetSeverityThreshold() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SeverityThreshold
}

// GetSeverityThresholdOk returns a tuple with the SeverityThreshold field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf6) GetSeverityThresholdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeverityThreshold, true
}

// SetSeverityThreshold sets field value
func (o *ProviderConnectionResponseOneOf6) SetSeverityThreshold(v int32) {
	o.SeverityThreshold = v
}

// GetProvider returns the Provider field value
func (o *ProviderConnectionResponseOneOf6) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ProviderConnectionResponseOneOf6) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ProviderConnectionResponseOneOf6) SetProvider(v string) {
	o.Provider = v
}

func (o ProviderConnectionResponseOneOf6) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderConnectionResponseOneOf6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_version"] = o.ApiVersion
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["has_api_key"] = o.HasApiKey
	toSerialize["org_id"] = o.OrgId
	toSerialize["severity_threshold"] = o.SeverityThreshold
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *ProviderConnectionResponseOneOf6) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_version",
		"endpoint",
		"has_api_key",
		"org_id",
		"severity_threshold",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderConnectionResponseOneOf6 := _ProviderConnectionResponseOneOf6{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderConnectionResponseOneOf6)

	if err != nil {
		return err
	}

	*o = ProviderConnectionResponseOneOf6(varProviderConnectionResponseOneOf6)

	return err
}

type NullableProviderConnectionResponseOneOf6 struct {
	value *ProviderConnectionResponseOneOf6
	isSet bool
}

func (v NullableProviderConnectionResponseOneOf6) Get() *ProviderConnectionResponseOneOf6 {
	return v.value
}

func (v *NullableProviderConnectionResponseOneOf6) Set(val *ProviderConnectionResponseOneOf6) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderConnectionResponseOneOf6) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderConnectionResponseOneOf6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderConnectionResponseOneOf6(val *ProviderConnectionResponseOneOf6) *NullableProviderConnectionResponseOneOf6 {
	return &NullableProviderConnectionResponseOneOf6{value: val, isSet: true}
}

func (v NullableProviderConnectionResponseOneOf6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderConnectionResponseOneOf6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


