/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelAccessTargetOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAccessTargetOneOf{}

// ModelAccessTargetOneOf Match by user-facing model alias (with optional trailing `*` wildcard) — i.e. whatever the caller put in the `model` field.  Use this for aliases that may map to multiple providers (e.g. a `goto` alias fanned out across OpenAI and Anthropic): the policy fires whenever a request uses that alias, regardless of routing.
type ModelAccessTargetOneOf struct {
	Alias string `json:"alias"`
	Kind string `json:"kind"`
}

type _ModelAccessTargetOneOf ModelAccessTargetOneOf

// NewModelAccessTargetOneOf instantiates a new ModelAccessTargetOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAccessTargetOneOf(alias string, kind string) *ModelAccessTargetOneOf {
	this := ModelAccessTargetOneOf{}
	this.Alias = alias
	this.Kind = kind
	return &this
}

// NewModelAccessTargetOneOfWithDefaults instantiates a new ModelAccessTargetOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAccessTargetOneOfWithDefaults() *ModelAccessTargetOneOf {
	this := ModelAccessTargetOneOf{}
	return &this
}

// GetAlias returns the Alias field value
func (o *ModelAccessTargetOneOf) GetAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Alias
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
func (o *ModelAccessTargetOneOf) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alias, true
}

// SetAlias sets field value
func (o *ModelAccessTargetOneOf) SetAlias(v string) {
	o.Alias = v
}

// GetKind returns the Kind field value
func (o *ModelAccessTargetOneOf) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ModelAccessTargetOneOf) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ModelAccessTargetOneOf) SetKind(v string) {
	o.Kind = v
}

func (o ModelAccessTargetOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAccessTargetOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alias"] = o.Alias
	toSerialize["kind"] = o.Kind
	return toSerialize, nil
}

func (o *ModelAccessTargetOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alias",
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelAccessTargetOneOf := _ModelAccessTargetOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelAccessTargetOneOf)

	if err != nil {
		return err
	}

	*o = ModelAccessTargetOneOf(varModelAccessTargetOneOf)

	return err
}

type NullableModelAccessTargetOneOf struct {
	value *ModelAccessTargetOneOf
	isSet bool
}

func (v NullableModelAccessTargetOneOf) Get() *ModelAccessTargetOneOf {
	return v.value
}

func (v *NullableModelAccessTargetOneOf) Set(val *ModelAccessTargetOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAccessTargetOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAccessTargetOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAccessTargetOneOf(val *ModelAccessTargetOneOf) *NullableModelAccessTargetOneOf {
	return &NullableModelAccessTargetOneOf{value: val, isSet: true}
}

func (v NullableModelAccessTargetOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAccessTargetOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


