/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the OAuthConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthConfig{}

// OAuthConfig struct for OAuthConfig
type OAuthConfig struct {
	Callbacks []string `json:"callbacks,omitempty"`
	AllowedLogoutUrls []string `json:"allowed_logout_urls,omitempty"`
	AppType NullableAppType `json:"app_type,omitempty"`
}

// NewOAuthConfig instantiates a new OAuthConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthConfig() *OAuthConfig {
	this := OAuthConfig{}
	return &this
}

// NewOAuthConfigWithDefaults instantiates a new OAuthConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthConfigWithDefaults() *OAuthConfig {
	this := OAuthConfig{}
	return &this
}

// GetCallbacks returns the Callbacks field value if set, zero value otherwise.
func (o *OAuthConfig) GetCallbacks() []string {
	if o == nil || IsNil(o.Callbacks) {
		var ret []string
		return ret
	}
	return o.Callbacks
}

// GetCallbacksOk returns a tuple with the Callbacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfig) GetCallbacksOk() ([]string, bool) {
	if o == nil || IsNil(o.Callbacks) {
		return nil, false
	}
	return o.Callbacks, true
}

// HasCallbacks returns a boolean if a field has been set.
func (o *OAuthConfig) HasCallbacks() bool {
	if o != nil && !IsNil(o.Callbacks) {
		return true
	}

	return false
}

// SetCallbacks gets a reference to the given []string and assigns it to the Callbacks field.
func (o *OAuthConfig) SetCallbacks(v []string) {
	o.Callbacks = v
}

// GetAllowedLogoutUrls returns the AllowedLogoutUrls field value if set, zero value otherwise.
func (o *OAuthConfig) GetAllowedLogoutUrls() []string {
	if o == nil || IsNil(o.AllowedLogoutUrls) {
		var ret []string
		return ret
	}
	return o.AllowedLogoutUrls
}

// GetAllowedLogoutUrlsOk returns a tuple with the AllowedLogoutUrls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfig) GetAllowedLogoutUrlsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedLogoutUrls) {
		return nil, false
	}
	return o.AllowedLogoutUrls, true
}

// HasAllowedLogoutUrls returns a boolean if a field has been set.
func (o *OAuthConfig) HasAllowedLogoutUrls() bool {
	if o != nil && !IsNil(o.AllowedLogoutUrls) {
		return true
	}

	return false
}

// SetAllowedLogoutUrls gets a reference to the given []string and assigns it to the AllowedLogoutUrls field.
func (o *OAuthConfig) SetAllowedLogoutUrls(v []string) {
	o.AllowedLogoutUrls = v
}

// GetAppType returns the AppType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OAuthConfig) GetAppType() AppType {
	if o == nil || IsNil(o.AppType.Get()) {
		var ret AppType
		return ret
	}
	return *o.AppType.Get()
}

// GetAppTypeOk returns a tuple with the AppType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OAuthConfig) GetAppTypeOk() (*AppType, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppType.Get(), o.AppType.IsSet()
}

// HasAppType returns a boolean if a field has been set.
func (o *OAuthConfig) HasAppType() bool {
	if o != nil && o.AppType.IsSet() {
		return true
	}

	return false
}

// SetAppType gets a reference to the given NullableAppType and assigns it to the AppType field.
func (o *OAuthConfig) SetAppType(v AppType) {
	o.AppType.Set(&v)
}
// SetAppTypeNil sets the value for AppType to be an explicit nil
func (o *OAuthConfig) SetAppTypeNil() {
	o.AppType.Set(nil)
}

// UnsetAppType ensures that no value is present for AppType, not even an explicit nil
func (o *OAuthConfig) UnsetAppType() {
	o.AppType.Unset()
}

func (o OAuthConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Callbacks) {
		toSerialize["callbacks"] = o.Callbacks
	}
	if !IsNil(o.AllowedLogoutUrls) {
		toSerialize["allowed_logout_urls"] = o.AllowedLogoutUrls
	}
	if o.AppType.IsSet() {
		toSerialize["app_type"] = o.AppType.Get()
	}
	return toSerialize, nil
}

type NullableOAuthConfig struct {
	value *OAuthConfig
	isSet bool
}

func (v NullableOAuthConfig) Get() *OAuthConfig {
	return v.value
}

func (v *NullableOAuthConfig) Set(val *OAuthConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthConfig(val *OAuthConfig) *NullableOAuthConfig {
	return &NullableOAuthConfig{value: val, isSet: true}
}

func (v NullableOAuthConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


