/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpsertConnectionRequestOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertConnectionRequestOneOf2{}

// UpsertConnectionRequestOneOf2 struct for UpsertConnectionRequestOneOf2
type UpsertConnectionRequestOneOf2 struct {
	// Supply to set or rotate the token; omit to leave unchanged.
	BearerToken *string `json:"bearer_token,omitempty"`
	Endpoint *string `json:"endpoint,omitempty"`
	Location *string `json:"location,omitempty"`
	ProjectId string `json:"project_id"`
	Provider string `json:"provider"`
}

type _UpsertConnectionRequestOneOf2 UpsertConnectionRequestOneOf2

// NewUpsertConnectionRequestOneOf2 instantiates a new UpsertConnectionRequestOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertConnectionRequestOneOf2(projectId string, provider string) *UpsertConnectionRequestOneOf2 {
	this := UpsertConnectionRequestOneOf2{}
	this.ProjectId = projectId
	this.Provider = provider
	return &this
}

// NewUpsertConnectionRequestOneOf2WithDefaults instantiates a new UpsertConnectionRequestOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertConnectionRequestOneOf2WithDefaults() *UpsertConnectionRequestOneOf2 {
	this := UpsertConnectionRequestOneOf2{}
	return &this
}

// GetBearerToken returns the BearerToken field value if set, zero value otherwise.
func (o *UpsertConnectionRequestOneOf2) GetBearerToken() string {
	if o == nil || IsNil(o.BearerToken) {
		var ret string
		return ret
	}
	return *o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertConnectionRequestOneOf2) GetBearerTokenOk() (*string, bool) {
	if o == nil || IsNil(o.BearerToken) {
		return nil, false
	}
	return o.BearerToken, true
}

// HasBearerToken returns a boolean if a field has been set.
func (o *UpsertConnectionRequestOneOf2) HasBearerToken() bool {
	if o != nil && !IsNil(o.BearerToken) {
		return true
	}

	return false
}

// SetBearerToken gets a reference to the given string and assigns it to the BearerToken field.
func (o *UpsertConnectionRequestOneOf2) SetBearerToken(v string) {
	o.BearerToken = &v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *UpsertConnectionRequestOneOf2) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertConnectionRequestOneOf2) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *UpsertConnectionRequestOneOf2) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *UpsertConnectionRequestOneOf2) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *UpsertConnectionRequestOneOf2) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertConnectionRequestOneOf2) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *UpsertConnectionRequestOneOf2) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *UpsertConnectionRequestOneOf2) SetLocation(v string) {
	o.Location = &v
}

// GetProjectId returns the ProjectId field value
func (o *UpsertConnectionRequestOneOf2) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *UpsertConnectionRequestOneOf2) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *UpsertConnectionRequestOneOf2) SetProjectId(v string) {
	o.ProjectId = v
}

// GetProvider returns the Provider field value
func (o *UpsertConnectionRequestOneOf2) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *UpsertConnectionRequestOneOf2) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *UpsertConnectionRequestOneOf2) SetProvider(v string) {
	o.Provider = v
}

func (o UpsertConnectionRequestOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertConnectionRequestOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BearerToken) {
		toSerialize["bearer_token"] = o.BearerToken
	}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *UpsertConnectionRequestOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsertConnectionRequestOneOf2 := _UpsertConnectionRequestOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpsertConnectionRequestOneOf2)

	if err != nil {
		return err
	}

	*o = UpsertConnectionRequestOneOf2(varUpsertConnectionRequestOneOf2)

	return err
}

type NullableUpsertConnectionRequestOneOf2 struct {
	value *UpsertConnectionRequestOneOf2
	isSet bool
}

func (v NullableUpsertConnectionRequestOneOf2) Get() *UpsertConnectionRequestOneOf2 {
	return v.value
}

func (v *NullableUpsertConnectionRequestOneOf2) Set(val *UpsertConnectionRequestOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertConnectionRequestOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertConnectionRequestOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertConnectionRequestOneOf2(val *UpsertConnectionRequestOneOf2) *NullableUpsertConnectionRequestOneOf2 {
	return &NullableUpsertConnectionRequestOneOf2{value: val, isSet: true}
}

func (v NullableUpsertConnectionRequestOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertConnectionRequestOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


