/*
Barndoor.ai Public API

Unified public API specification for Barndoor.ai platform

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProfileRequest{}

// CreateProfileRequest struct for CreateProfileRequest
type CreateProfileRequest struct {
	Capabilities *AgentRuntimeCapabilities `json:"capabilities,omitempty"`
	Client string `json:"client"`
	Config map[string]string `json:"config"`
	DisplayName string `json:"display_name"`
	Slug string `json:"slug"`
}

type _CreateProfileRequest CreateProfileRequest

// NewCreateProfileRequest instantiates a new CreateProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProfileRequest(client string, config map[string]string, displayName string, slug string) *CreateProfileRequest {
	this := CreateProfileRequest{}
	this.Client = client
	this.Config = config
	this.DisplayName = displayName
	this.Slug = slug
	return &this
}

// NewCreateProfileRequestWithDefaults instantiates a new CreateProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProfileRequestWithDefaults() *CreateProfileRequest {
	this := CreateProfileRequest{}
	return &this
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *CreateProfileRequest) GetCapabilities() AgentRuntimeCapabilities {
	if o == nil || IsNil(o.Capabilities) {
		var ret AgentRuntimeCapabilities
		return ret
	}
	return *o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProfileRequest) GetCapabilitiesOk() (*AgentRuntimeCapabilities, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *CreateProfileRequest) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given AgentRuntimeCapabilities and assigns it to the Capabilities field.
func (o *CreateProfileRequest) SetCapabilities(v AgentRuntimeCapabilities) {
	o.Capabilities = &v
}

// GetClient returns the Client field value
func (o *CreateProfileRequest) GetClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Client
}

// GetClientOk returns a tuple with the Client field value
// and a boolean to check if the value has been set.
func (o *CreateProfileRequest) GetClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Client, true
}

// SetClient sets field value
func (o *CreateProfileRequest) SetClient(v string) {
	o.Client = v
}

// GetConfig returns the Config field value
func (o *CreateProfileRequest) GetConfig() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *CreateProfileRequest) GetConfigOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *CreateProfileRequest) SetConfig(v map[string]string) {
	o.Config = v
}

// GetDisplayName returns the DisplayName field value
func (o *CreateProfileRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CreateProfileRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CreateProfileRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetSlug returns the Slug field value
func (o *CreateProfileRequest) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *CreateProfileRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *CreateProfileRequest) SetSlug(v string) {
	o.Slug = v
}

func (o CreateProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	toSerialize["client"] = o.Client
	toSerialize["config"] = o.Config
	toSerialize["display_name"] = o.DisplayName
	toSerialize["slug"] = o.Slug
	return toSerialize, nil
}

func (o *CreateProfileRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client",
		"config",
		"display_name",
		"slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProfileRequest := _CreateProfileRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProfileRequest)

	if err != nil {
		return err
	}

	*o = CreateProfileRequest(varCreateProfileRequest)

	return err
}

type NullableCreateProfileRequest struct {
	value *CreateProfileRequest
	isSet bool
}

func (v NullableCreateProfileRequest) Get() *CreateProfileRequest {
	return v.value
}

func (v *NullableCreateProfileRequest) Set(val *CreateProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProfileRequest(val *CreateProfileRequest) *NullableCreateProfileRequest {
	return &NullableCreateProfileRequest{value: val, isSet: true}
}

func (v NullableCreateProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


